### ISSUE TITLE
Python 3.8: ImportError: DLL load failed while importing _psycopg: The specified module could not be found.

### ISSUE THREAD

**Issue by BrendanMartin** [psycopg/psycopg2#1014]
```Traceback (most recent call last):
  File "C:\...\db.py", line 1, in <module>
    import psycopg2
  File "C:\...\venv\lib\site-packages\psycopg2\__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: DLL load failed while importing _psycopg: The specified module could not be found.
```

Just installed Python 3.8 64-bit and was able to successfully install psycopg2 with `pip install psycopg2`. I received this ImportError when trying to run my project.

**Comment by dvarrazzo** [comment]
You already said it #1006. Please follow #990.

**Comment by BrendanMartin** [comment]
Unlike in #990, I am able to install psycopg2 with Python 3.8 64 on Windows 10

**Comment by jerickso** [comment]
The error indicates it is unable to load the psycopg DLL.

Based upon what I believe your file structure is, the file should exist here:
`C:\...\venv\lib\site-packages\psycopg2\_psycopg.cp38-win_amd64.pyd`

Also, you should be able to look in Windows Event viewer and find an error message that maybe describes the reason a little better why it failed (ie unable to find, corrupt file, etc).

The other thing, with every command prompt (or however you run your project), you need to 'activate' the venv, otherwise the paths will not be setup correctly, and it will not be able to find the DLL.

**Comment by leilei1881** [comment]
![image](https://user-images.githubusercontent.com/39149870/72595461-d9089880-3944-11ea-93c0-5cd8acca5afa.png)
@BrendanMartin, it should be pycharm's bug, however, you can run through by up pic.
I use python3.8.1-64bit ,win10, pycharm 2019.3.1 version.

**Comment by rafid0007** [comment]
I was having the same problem.I was using pycharm on windows 10...I stuck 3 days for this problem...I just went to my pycharm setting>project interpreter and then uninstalled psycopg2 and then again installed through pycharm's project interpreter..Problems gone...

**Comment by dvarrazzo** [comment]
If anybody else has problems with psycopg in pycharm, go tell to the pycharm people, thank you.
