### ISSUE TITLE
Does async and simpleconnection pooling work together in psycopg2?

### ISSUE THREAD

**Issue by AnandDev8** [psycopg/psycopg2#1020]
Does asynchronous communication and connection pooling can be used together in  psyscopg2. Is this valid ?
I would like to know if async is supported in connection pooling?
```
class Connnect:
    def __init__(self): 
        #Setting asychronous connection
        self.connectionpool = SimpleConnectionPool(1, 10, user=os.environ['dbpostgressuname'],password=os.environ['dbpostgresspwd'],host=os.environ['dbpostgresshost'],port=int(os.environ['dbpostgressport']),dbname=os.environ['dbpostgressname'],async_=1)
        logging.info('Connection Pool : {}'.format(self.connectionpool))
    @contextmanager
    def getConnection(self):
       logger.info('getting connection')
       con = self.connectionpool.getconn()
       try:
          yield con
       except Exception as ex:
           logging.error('Error while Connecting with Database')
           logging.error(ex)
       finally:
          if con:
             logging.info("Connection available")
             self.connectionpool.putconn(con)
          else:
             logging.info("No connection")
             self.getConnection()
```
It is kind of working for me but sometimes it would give the following error

```
ERROR:root:Error while Connecting with Database
ERROR:root:server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```
How to fix this ?
How can i get another connection if my current connection fails ??

**Comment by dvarrazzo** [comment]
I don't think pool and async work together. Async connection are pretty much different in every possible aspect and don't respect the DBAPI interface.

**Comment by AnandDev8** [comment]
Async option is specified while opening a new connection, and it is applicable within a connection (An asynchronous communication style is established passing the parameter async=1 to the connect() function)
.  So, pool can pass the 'async' option while creating connections initially and they should be able to operate asynchronous. Can this be achieved?

**Comment by dvarrazzo** [comment]
Sure you can pass async to the connection, and syntactically will work, but I doubt the connection will work ok because the async connection needs to be kickstarted with a `poll()` loop and the pool won't do that for you.

I think the psycopg.pool is the wrong abstraction to support both sync and async connections. Furthermore these pools implement some policies which were right for certain projects and environment but I doubt they are so uniformly valid that they deserve being part of this library. I suggest you to can subclass it or write your own pool working with async connections and with the policy your project requires.
