### ISSUE TITLE
ImportError: /usr/local/lib/python2.7/site-packages/psycopg2/_psycopg.so: Undefined symbol "PQencryptPasswordConn"

### ISSUE THREAD

**Issue by poojatr** [psycopg/psycopg2#1035]
Hi,

Any way to solve this problem with
python - 2.7
postgres- 9.6.5
and
psycopg2 - 2.8.4

Error message is : ImportError: /usr/local/lib/python2.7/site-packages/psycopg2/_psycopg.so: Undefined symbol "PQencryptPasswordConn"

Is there any way to use this without upgrading postgres, since I have a major dependancy of postgres with 9.6.5

**Comment by dvarrazzo** [comment]
The dependency of psycopg is on the client-side library. As long as you are sure that the client library you use at install time is the same psycopg will find at build time you shouldn't hit that error. If `pg_config` finds you a libpq >= 10, but then at import time psycopg imports a libpq.so < 10, you may get that error.

This is the only place the function is used: you can see that it has a compile guard:

https://github.com/psycopg/psycopg2/blob/9bcca1a7b0e2cb793be0d4c7d98fdbaeba069128/psycopg/psycopgmodule.c#L475-L492

What `PG_VERSION_NUM` is used depends on what `pg_config` is found on the path at install time. For instance in this case it wouldn't be compiled:

    $ pg_config --version
    PostgreSQL 9.4.25

you can see the version really used if you install psycopg:
```
$ pip install --verbose psycopg2 | grep PG_VERSION_NUM
  x86_64-linux-gnu-gcc [...] -DPG_VERSION_NUM=90425 [...] /psycopg/psycopgmodule.o
[...]
```

Try reinstalling psycopg:

- if you have a `PG_VERSION_NUMBER` < 100000 then you shouldn't have the above error whatever library is found at import time.
- if you have a `PG_VERSION_NUMBER` >= 100000 then there must be a libpq > 10.0 at import time too, otherwise you'll have the error.

Hope this helps. How is that you are installing and then using psycopg?

**Comment by poojatr** [comment]
Hi,


I have a strict use case of using postgres-9.6.5, But the dependancy of postgres11 was there in the Manisfest , which I removed 

`deps":{"postgresql11-client":{"origin":"databases/postgresql11-client","version":"11.6"},`

Created the package using the tar files extracted , modified MANIFEST and with the command

`pkg create -r #{folder_name} -m #{folder_name} -o /tmp -v`

The outputs for the following command is as below,
 pg_config --version
PostgreSQL 9.6.15

and 

import ctypes
libpq = ctypes.cdll.LoadLibrary("libpq.so")
print(libpq.PQlibVersion())

90615

Am i doing anything wrong , still hitting the same issue of PQencryptPasswordConn

**Comment by dvarrazzo** [comment]
I don't know what is the manifest, that is outside the psycopg build, and I don't know what is `pkg`. I can only guide up to install things in bash: how to adapt it to other contexts I don't know details about is up to you.

Can I see a line in the build log of psycopg, where `PG_VERSION_NUMBER` is displayed?

**Comment by poojatr** [comment]
Is there any other way to find out the PG_VERSION_NUMBER , as I dint use a pip install --verbose to build the package and not able to find the build log.

**Comment by dvarrazzo** [comment]
That's generated by `python setup.py build`, or other commands resulting in a build, in psycopg2. I have no idea how your build system works.

My point is that you have to make sure that what you build and what you install is the same stuff, and that the libpq found when you build and when you install is the same. You have to dig it yourself into our system.

**Comment by dvarrazzo** [comment]
Closing with the assumption the above worked. Please let us know if it didn't.
