### ISSUE TITLE
Possible documentation change: Connections not closed when exception is thrown inside of with context

### ISSUE THREAD

**Issue by chris-allnutt** [psycopg/psycopg2#1044]
Python Version: 3.7

Current Documentation:
https://www.psycopg.org/docs/usage.html?highlight=gunpoint#with-statement  Later in the documentation it states connections aren't closed, but in my testing they appear to be, or at least they're released fairly quickly if there are no exceptions within the block.

If an exception is thrown inside a with context the connection is not closed, instead it times out eventually (about 10 seconds).

Example:
```
while True:
    try:
        with psycopg2.connect(DSN) as conn:
            with conn.cursor() as curs:
                curs.execute(SQL)
                raise SomeRandomException
    except Exceptions as _ex:
        pass

    time.sleep(1)
```

Watching database connections count the connections will continue to increase till timing out.  If you add exception handling within the with cursor context the connections are immediately closed, or are closed fast enough that i they don't continue to increase the active connection count.

Example:
```
while True:
    with psycopg2.connect(DSN) as conn:
        with conn.cursor() as curs:
            try:
                curs.execute(SQL)
                raise SomeRandomException
            except Exceptions as _ex:
                pass
    time.sleep(1)
```

It would be less confusing to make the with conn work as expected like file descriptors and the like or drop the first example and just provide the second example which has connection management as per normal psycopg2 usage to reduce confusion.  I will be changing my usage to the following for all code where I'm currently using psycopg2.  It is still nicely pythonic to have the automatic cursor rollback commit but with for connections doesn't work as I would intuitively expect.

```
conn = psycopg2.connect(DSN)
try:
    with conn:
        with conn.cursor() as curs:
            curs.execute(SQL1)

    with conn:
        with conn.cursor() as curs:
            curs.execute(SQL2)
except Exception as _ex:
  logging.error(str(_ex))
finally:
    conn.close()
```

**Comment by dvarrazzo** [comment]
The connection is not closed by the end of the context: in your case it is closed when it goes out of scope. This is consistent with what documented. The connection in your test is likely kept alive by the scope of your variable and is closed when the variable is overwritten; it might be kept alive by the exception, but I am not sure about that. Surely it is not related to the context manager and it is not closed by leaving it (unless the variable is lost).

I agree that the behaviour is different from what experienced by other resource-wrapping objects. In my experience leaving a transaction open is a worse outcome than keeping a connection open (you see a server on its knees pretty quickly and filling with bloat). For all the love I have for symmetry with the way files and other resources are treated in python I prefer to have 300 leaking connections open than 3 transactions forgot open on a busy server.

You can understand though that it would be a deep change in the behaviour of the program so it cannot happen as a bug fix, and to me it cannot even happen in psycopg2. I would be happy to make it happen in psycopg3, but there should be a secondary mechanism to wrap a transaction in a block. Like:

```python
with psycopg2.connect() as cnn:
    with cnn.transaction():
        with cnn.cursor() as cur:
            do something()
```

**Comment by chris-allnutt** [comment]
@dvarrazzo thank you for your response, in our instance connections are our premium, for now I'm going to explicitly manage my connections, but I was really excited about with usage.  That would be great to see in psycopg3!

**Comment by asqui** [comment]
@dvarrazzo : I don't understand why you started talking about transactions, since the OP was only talking about connections (as far as I can see).

But since you bring up the question of transaction context manager: I've written just this at [asqui/psycopg-nestedtransactions](https://github.com/asqui/psycopg-nestedtransactions); we've been using it in production for over a year and it also supports transaction nesting via savepoints (allowing you to rollback an inner context and allowing an outer context to continue).

Do you have any appetite for including this in psycopg2? Should I ask on the mailing list?

**Comment by dvarrazzo** [comment]
> @dvarrazzo : I don't understand why you started talking about transactions, since the OP was only talking about connections (as far as I can see).

Because the reason at the moment `with connection` cannot be used to `close()` on exit is that the mechanism is already used to commit/rollback, as [documented](https://www.psycopg.org/docs/usage.html?highlight=gunpoint#with-statement). It's not because I think it's a bad idea.

> Do you have any appetite for including this in psycopg2? Should I ask on the mailing list?

It sounds a nice feature. It would be nice to have a conversation about what to do about nested transactions. Maybe it would be useful to have this conversation with the DB-SIG group too (the DBAPI has not been updated or re-discussed in ages, and Python has changed a lot since then).
