### ISSUE TITLE
Remove dependency on pg_config

### ISSUE THREAD

**Issue by JuergenSimon** [psycopg/psycopg2#1077]
The dependency on pg_config in the installation process has too heavyweight dependencies.

**Comment by dvarrazzo** [comment]
You might want to review the tone of this ticket before I explain you an point out where you are wrong, otherwise I'll just close the ticket, block you, report you, and use you an example of how not to behave on a public tracker.

**Comment by JuergenSimon** [comment]
I apologise if the hyperbole note of humour was lost on you. Let me elaborate then on the issue some more, because it is serious and causes trouble: in order to have `pg_config` at your disposal, you force every user of the package to install postgres. To spell it out: to have a client library installed for the purpose of making connections to a server system, I need to install the server system itself. 

Of course this system then comes with numerous dependencies of it's own (for example: gcc). The entire procedure weighs in heavily in terms of dependent packages, space and time consumed in building docker containers for python applications that rely on psychopg2 to make connections to PostgresSQL databases.

Surely there must be a way to eliminate this dependency?

**Comment by fogzot** [comment]
You are insanely wrong (if the hyperbole note of humour was lost on you).

To have a working `pg_config` you don't need to install the PostgreSQL server. Sane distributions, Debian for example, provide the headers (needed to build psycopg) and `pg_config` in a package that does not depend on the server itself.

It is possible to build psycopg inside a Docker container with just a few dependencies (OpenSSL, GCC, etc.) but even it that wasn't the case you could always build a base image with psycopg installed *once* and then derive from it in other projects.

**Comment by JuergenSimon** [comment]
I would consider python-slim a sensible distribution to start a python project. Nonetheless one needs to install at least postgres client libs (and a bunch of attached, heavyweight dependencies such as gcc) to make it work. Of course I can remove the packages again after the installation of psychopg2, but that adds additional burden on each project to drag through. None of which would be necessary if psychopg2 didn't depend on pg_config. 

The same goes for maintaining chains of base containers which are a pain to maintain in the long run and are not a practical and sane solution. The best option imho would be to remove the dependency of psychopg2 on pg_config altogether.

**Comment by JuergenSimon** [comment]
@dvarrazzo I revised the issue. Apologies again for the hyperbole.

**Comment by dvarrazzo** [comment]
@JuergenSimon psycopg2 is built in C and wraps the postgres client library (not "the postgres system" as you wrote: it wraps the client bit because, you know, it's a client bit). You need the libpq dev packages for that, and the pg_config comes together with that package. If you don't have pg_config you don't have the required client-side library.

I'll give you a piece of good news: we are writing a new major version of psycopg which doesn't depend on pg_config. And I give you another good news: you can contribute to the project. You can stop the insanity yourself, ain't it great?

The project is explained [in this post](https://www.varrazzo.com/blog/2020/03/06/thinking-psycopg3/) and I am looking forward for [your contribution to the project](https://github.com/sponsors/dvarrazzo/) so that we can stop the madness together. I count on that, otherwise it's all hyperboles, and you sound just like a random keyboard warrior who wants everything on a silver plate but falls quiet as soon as they are told to put their money where their mouth is.

By the way, what you describe, use a docker to build, yadda yadda: it's already there: `pip install psycopg2-binary` and off you go. Did you read the install page of the documentation perchance? However the wheel package has its ows ways to suck: I suggest you to be an hero and support financially the project.

**Comment by JuergenSimon** [comment]
Thanks for the good news. I take it. Keep the rest.

**Comment by dvarrazzo** [comment]
I had no doubt about that. Dupe of #1032 anyway.

**Comment by JuergenSimon** [comment]
Frankly I don't care what you think. I am programming for more than 30 years and have absolutely nothing to prove, in addition to very little time to spare. Being annoyed by bad choices in design does not justify unprofessional exclamation in the heat of the moment, for that I apologized and amended the ticket. As for the issue: it's obviously known and a common problem (as a cursory google search demonstrated) and also low on your list of priorities. Ergo the best conclusion is to remove the ticket, since it obviously does not serve any purpose, not to mention is a reminder of getting off on the wrong foot. So to me: matter closed with the ticket.

**Comment by dvarrazzo** [comment]
As per above: ticket #1032 opened by me, and [a whole article with a diagram](https://www.varrazzo.com/blog/2020/03/06/thinking-psycopg3/) showing the architecture of the system and why that's not a trivial change, and countless hours spent trying to make the wheel package work (take a look at the [wheels tickets](https://github.com/psycopg/psycopg2/issues?q=is%3Aissue+label%3Awheel)), should show the care we have for the issue more than "a cursory look on google".
