### ISSUE TITLE
Test if connection is open before getconn():

### ISSUE THREAD

**Issue by hivemall** [psycopg/psycopg2#1082]
Overnight database connections can timeout. Coming back one gets InterfaceErrors if not checking `closed` == 1. Can the pool please only hand out open connections, currently there is no check on `closed`. Meaning using it eg with pool.getconn() might raise. I see no point in a pool handing out broken connections, or me missed sth.?

https://github.com/psycopg/psycopg2/blob/cb3353be1f10590cdc2a894ada42c3b4c171feb7/lib/pool.py#L86

**Comment by dvarrazzo** [comment]
That would add overhead. In order to see if a connection is broken you need a network roundtrip: checking if closed = True doesn't really check it. The point of using a connection pool is to get a connection as fast as possible.

If for you the overhead of a roundtrip is sustainable you can subclass the connection pooler and add a check on getconn (a connection.poll() or a "select 1").
