### ISSUE TITLE
ImportError: undefined symbol: PQencryptPasswordConn

### ISSUE THREAD

**Issue by AndreFCruz** [psycopg/psycopg2#1093]
While using sqlalchemy on a remote computer I ran into this ImportError (which Ican get just by running ```import psycopg2```):
![image](https://user-images.githubusercontent.com/13498941/80509884-e4228a00-8971-11ea-92db-2ea06b5c7de8.png)

Python is running on a conda environment, which was packed (`conda pack`) `scp`ed and unpacked (`conda-unpack`) into the remote computer.
Python packages are on `~/<conda-env>/lib/python3.7/site-packages`

I have these psycopg packages installed from pypi:
```
psycopg2==2.8.5
psycopg2-binary==2.8.5
```

I have seen this issue #1018 but cannot seem to solve it by installing from source as that user did.

Am I missing any dependency?

Thanks :)

**Comment by dvarrazzo** [comment]
`PQencryptPasswordConn` is available in libpq 10. If psycopg is built with a previous version than the functionality is not compiled in and the library will just give an error if the feature is used.

In your case psycopg was built on a system with a pg_config >= 10 and then moved on a system which at runtime has libpq < 10

I don't believe this is possible with wheels, because they ship with the libpq used at build time and it is > 10.

I don't know what conda pack and unpack do, but they are not doing it right. Please open a bug with them, pointing them to this bug for explanations.

**Comment by AndreFCruz** [comment]
Thanks

As a quick fix I can report that downgrading psycopg2 and sqlalchemy to the following versions fixed the problem:
```
psycopg2-binary==2.8.4
SQLAlchemy==1.3.15
```

**Comment by liangxu21** [comment]
> psycopg2-binary==2.8.4
> SQLAlchemy==1.3.15

works  for me. thanks a lot!
