### ISSUE TITLE
connection.cursor.close() called twice without error

### ISSUE THREAD

**Issue by pgodfrin** [psycopg/psycopg2#1114]
Greetings,
pyscopg2 noob here, be gentle. In this snippet, the .close() method is called twice, with no error. I would have expected the second close to kick on a cursor already closed error. Oh yeah, same thing for the connection close...

try:
            dbconn = psycopg2.connect(host="foo",
                                      dbname='postgres',
                                      user='postgres'
                                      )
            curs01 = dbconn.cursor()
            curs01.execute("SELECT version();")
            record = curs01.fetchone()
            print(f"You are connected to - {record}")
            curs01.close()
            curs01.close()
            dbconn.close()
            dbconn.close()
        except (Exception, psycopg2.DatabaseError) as error :
            print ("ERROR: connecting to PostgreSQL:", error)
            raise

**Comment by dvarrazzo** [comment]
It's intentional. In the past the behaviour was what you describe and people complained that it shouldn't have been an error...

I guess their point is a better one. Sometimes your connection gets closed by the server or other accident outside your control, so a snippet like:

```python
conn = connect()
try:
    do_some_work(conn)
finally:
    conn.close()
```

would fail if e.g. connectivity is lost. That means pretty much you could _never_ call `close()` safely and you always had to guard it like:

```python
if not conn.closed:
    conn.close()
```

It was a long time ago, but this is the rationale behind deciding to make `close()` idempotent.
