### ISSUE TITLE
Is it possible to connect throw proxy?

### ISSUE THREAD

**Issue by heckad** [psycopg/psycopg2#1117]
My database is hidden from the internet and I have ssh access to server wich in local network and have access to db. How to connect to db using this server as a proxy?

**Comment by dvarrazzo** [comment]
with `ssh -L`. Look in the manual.

**Comment by okainov** [comment]
@dvarrazzo well, it would be more useful if you'd point to some particular page in the documentation. Because neither search by "proxy" nor search by "ssh" gives any results when using search at the main [doc page](https://www.psycopg.org/docs/). Nor does Google search with `site` modifier

**Comment by dvarrazzo** [comment]
`ssh -L` is documented in `man ssh`.

**Comment by okainov** [comment]
@dvarrazzo but it has nothing to do with making `psycopg2` work via proxy. Especially when folks have only Python script available to run (on some restricted hosting or so).

**Comment by dvarrazzo** [comment]
With computers, things work in layer: psycopg expects that you have network connectivity between the server and the client, and then it can make the two talk to each other. Connectivity problems come in all shape and forms and it is not psycopg role to diagnose and fix them. For psycopg, networking is a precondition to rely on, not a problem to solve.

I understand that there are Python solution to proxy around things. For psycopg3 test suite I have used [pproxy](https://pypi.org/project/pproxy/) to simulate network interruptions, and it has worked ok for this limited use case. Other people have reported problems using other proxies, especially in async: there is nothing psycopg can  do about it, and if I suggest `ssh -L` is because I know it works, others may not, and if they don't work it's a problem with them, not with psycopg.

The same way you cannot expect a firewall program to lay down a cable between two computers of yours: that's a problem one layer below. Turtles all the way down.

**Comment by tim-schilling** [comment]
Another way I've found to manage this is to route the connections through to your proxy via a tool like `proxychains-ng`. We're using a hosted postgres provider that doesn't allow for SSH tunneling which removed `ssh -L` as an option for us.
