### ISSUE TITLE
conn.poll does not raise an AdminShutdown exception

### ISSUE THREAD

**Issue by elemoine** [psycopg/psycopg2#1121]
When a connection was closed by the server `cursor.execute()` raises an `AdminShutdown` exception:

```
>>> conn = psycopg2.connect(dsn="")
>>> # here the connection gets closed on the postgres side
>>> curs = conn.cursor()
>>> curs.execute("select 1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
psycopg2.errors.AdminShutdown: terminating connection due to administrator command
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

>>>
```

but `conn.poll()` raises an `OperationalError`:

```
>>> conn = psycopg2.connect(dsn="")
>>> # here the connection gets closed on the postgres side
>>> conn.poll()
0
>>> conn.poll()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

Why doesn't `poll` raise an `AdminShutdown` error? And also, why the first call to `poll` reports no error?

**Comment by dvarrazzo** [comment]
`AdminShutdown` is raised upon receiving a well defined message from the server. It is an error result carrying an SQLSTATE code (`57P01` as per [`psycopg2.errors`](https://www.psycopg.org/docs/errors.html)). The server is polite enough to send a message to the client _before_ closing the connection.

If poll is executed on a broken connection some client-side function call will fail. This failure doesn't carry an SQLSTATE so it cannot be converted into a more precise error subclass.

I don't know the detail of why the first poll doesn't give an error. The politeness of the server makes me think that the poll falls when the TCP connection is still open but the database is shutting down and it's already closed for business.

If you are curious to look more into it you can compile psycopg in debug mode and look at what happens behind the scene of poll. I think quite simply the connection is still open and then gets closed. Note that you only receive the 57P01 because you have a query ongoing, otherwise I don't think the server will send a message to the client regarding the connection being shut down.

**Comment by elemoine** [comment]
Thank you @dvarrazzo for your response.
