### ISSUE TITLE
set_isolation_level reset search_path

### ISSUE THREAD

**Issue by pronsholt** [psycopg/psycopg2#1128]
changing/touching "set_isolation_level" resets search_path in PostgreSQL.

Model code:

```
search_path = "set search path to some path"
cur.execute('SET search_path TO %s', (search_path,))

cur.execute("show search_path")
print(cur.fetchall())

conn.set_isolation_level(ISOLATION_LEVEL_DEFAULT) # nothing should happen, but search_path is reset in PostgreSQL!

cur.execute("show search_path") 
print(cur.fetchall()) # search path is reset

```

(Psycopg2 version 2.8.5, PostgreSQL PostgreSQL 12.2, compiled by Visual C++ build 1914, 64-bit, Python  3.8.2, Windows 10 Pro)

**Comment by dvarrazzo** [comment]
[As docs declare](https://www.psycopg.org/docs/connection.html#connection.set_isolation_level) `set_isolation_level()` is an old deprecated method. It has a unsavoury behaviour: it rolls back the active transaction; that's why your session state is reset.

A more suitable method is `set_session()` which behaves in a saner way, which is to raise an exception if you try and do what you are doing:

```
>>> cur.execute("set search_path to whatever, public")
>>> cnn.set_session(isolation_level="default")
ProgrammingError: set_session cannot be used inside a transaction
```

the problem is that the `set` statement has already started a transaction: asking to change its behaviour half way is not possible.

You can run your `set search_path` after setting the session the way you need.

**Comment by pronsholt** [comment]
Thanks for your swith and thorough explanation!
