### ISSUE TITLE
cursor.itersize does seem to fetch all data to memory

### ISSUE THREAD

**Issue by JakobHenning** [psycopg/psycopg2#1156]
I have a postgres DB with around 700k rows and 1 column (`data`) containing a JSON-object. The entire DB takes around 500 MB when loaded.

Running the following 

```python
query =" SELECT data from db;"
con= psycopg2.connect(
    dbname=database,
    user=user,
    password=pwd,
    host=host,
    port=port
)
with con.cursor(name='custom_cursor') as cursor:
     cursor.itersize = 10# chunk size
     
     cursor.execute(query)
     df = np.vstack(cursor)
```

still spikes my memory to more than 6 GB. It does no difference if I change the `itersize` to 10, 100, 100000. The memory still explodes.

Python == 3.7.9
mysql-connector==2.2.9
numpy==1.19.2
pandas==1.1.2
Pillow==7.2.0
psycopg2==2.8.6
pyarrow==1.0.1
pyodbc==4.0.30
SQLAlchemy==1.3.19

**Comment by dvarrazzo** [comment]
I don't know how `np.varstack` consumes the input: it probably creates a list of it, fetching all the data in memory, using the chosen page size. This is not under psycopg control.

Please enable server-side logging and look at the requests psycopg makes to the server. If you specified a certain page size and psycopg does something different then we have a bug. Otherwise there's nothing we can do about your memory, if downstream psycopg something does `list(cursor)`.
