### ISSUE TITLE
How to install on OSX or Windows?

### ISSUE THREAD

**Issue by pzelnip** [psycopg/psycopg2#1167]
The documentation for installing (https://www.psycopg.org/install/) is Linux-specific, in particular around requiring the python3-dev and libpq-dev libraries.

Is there equivalent documentation about how to install psycopg2 under OSX or Windows?  When I pip install it I get compilation errors, but I'm not sure how to get the equivalent dependency libraries for my OS.

**Comment by pzelnip** [comment]
And FWIW, installing psycopg2-binary also fails for me currently with compilation errors as well (which I thought psycopg2-binary didn't do any compilation?).

**Comment by dvarrazzo** [comment]
If you update pip you should be able to install psycopg2-binary. If you are inexperienced I suggest you to do so.

I don't have OSX experience to help in what packages to use, but I'm sure others have had the same problem you had and google knows the answer.

Installing on Window just works, because binary packages are distributed for the psycopg2 package too. However Python 3.9 is still unsupported on windows for reasons described in #1160.
