### ISSUE TITLE
UniqueViolation does not map to IntegrityError

### ISSUE THREAD

**Issue by halltristanj** [psycopg/psycopg2#1176]
Per this statement in the [documentation](https://www.psycopg.org/docs/errors.html#module-psycopg2.errors):
> Every exception class is a subclass of one of the standard DB-API exception and expose the Error interface. Each class’ superclass is what used to be raised by psycopg in versions before the introduction of this module, so everything should be compatible with previously written code catching one the DB-API class: if your code used to catch IntegrityError to detect a duplicate entry, it will keep on working even if a more specialised subclass such as UniqueViolation is raised

More specifically, I am not seeing this part:
> if your code used to catch IntegrityError to detect a duplicate entry, it will keep on working even if a more specialised subclass such as UniqueViolation is raised

work.

Had a `contextmanager` that continued to no longer work once upgrading to `2.8.6`:
```python
@contextmanager
def ignore_duplicates() -> Generator:
    try:
        yield
    except QueryException as e:
        logger.debug(f'IgnoreDupes#QueryException: {e}')
        if type(e.previous) != IntegrityError:
            raise
    except Exception as leftovers:
        logger.debug(f'IgnoreDupes#Exception: {leftovers}')
```

Had to change `if type(e.previous) != IntegrityError` to `if type(e.previous) not in (IntegrityError, UniqueViolation)` to get my tests to pass.

Using `psycopg2-binary==2.8.6 `.

**Comment by dvarrazzo** [comment]
The inheritance chain of `UniqueViolation` is:
```
In [5]: psycopg2.errors.UniqueViolation.__mro__                                                                      
Out[5]: 
(psycopg2.errors.UniqueViolation,
 psycopg2.IntegrityError,
 psycopg2.DatabaseError,
 psycopg2.Error,
 Exception,
 BaseException,
 object)
```
showing that `UniqueViolation` inherits from `IntegrityError`.

Checking for the type of thing using `type(x) ==` is wrong, because it doesn't consider subclasses, violating the [Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle). The correct way to write your code should have been `if not isinstance(e.previous, IntegrityError)`. Note that "catching an exception" in our docs means catching the exception and all its subclasses: `except IntegrityError` would have done that, and if you want to replicate the same semantics you have to use `isinstance()`.

See https://switowski.com/blog/type-vs-isinstance for some more explanation (that's just the first hit on duckduckgo, but it's pretty common knowledge and I don't have a canonical reference in mind).

**Comment by halltristanj** [comment]
Oh man! Thanks for the post. That cleared it right up! Working with old code so didn't spend too much time on it. Definitely will use `isinstance` more thoroughly and look for any other hiccups in our code.
