### ISSUE TITLE
Feature: Rename/remap execute_batch to executemany

### ISSUE THREAD

**Issue by willemavjc** [psycopg/psycopg2#1195]
I think that `execute_batch` is what `executemany` is expected to be and as such should replace the executemany current and strange implementation which is basically a for loop with no additional value over a manual implementation.

Again, based on some experience with some other libraries for other databases engines such - but not only - `cx_Oracle`, the common implementation of the `executemany` is that very implementation which was done for `execute_batch`.

Having the current implementation of `executemany `has no sense so that it results into something quite confusing. Hopefully, the documentation is quite clear with some grays and/or reds blocks detailing the thing. Though it still feels like following a trail of breadcrumbs for first developments with `psycopg2`: You have to go through multiples pages to understand in the end that what you were obviously looking for is just named something else.

Is there any particular reason to preserve `executemany `and separate `execute_batch `into an optional `extras `module?
Thanks in advance for your kind replies.

Documentation references:
https://www.psycopg.org/docs/cursor.html#cursor.executemany
https://www.psycopg.org/docs/extras.html#fast-execution-helpers

**Comment by dvarrazzo** [comment]
For a description of how things went, executemany() is a method mandated by the DBAPI, the interface standard that psycopg2 implements. I assume the way the feature should be implemented in order to perform would be to prepare the statement and execute it repeatedly. The execute_batch function is an attempt to find a strategy to make the same operation faster.

Even here, there is fundamentally a problem of backward compatibility: execution may turn out somewhat different, we lose rowcount... it's a bit delicate.

However, the function has proven to work ok. The specific rowcount problem might be probably fixed, because after a sequence of statements the libpq returns a sequence of results, which we dutifully discard, but from which we could at least accumulate the count. However it might be quite some work, and still be tricky.

I would leave this open and it's something that we cold consider for release 2.9, however at the moment it would have lower priority for me. In psycopg3 perspective the implementation is different (because psycopg3 prepares the plan and then execute it repeatedly).

**Comment by dvarrazzo** [comment]
This would be a major piece of work and at the moment I don't have resources to make. psycopg3 provides a better implementation for executemany (based on stored procedures and maybe in the future might use pipelined operations).
