### ISSUE TITLE
Question: psycopg2.errors.CharacterNotInRepertoire 

### ISSUE THREAD

**Issue by xcesaralejandro** [psycopg/psycopg2#1231]
Hi, I am trying to upload files and I am getting the following error
`psycopg2.errors.CharacterNotInRepertoire: secuencia de bytes no válida para codificación «UTF8»: 0xc0 0xa7
`
My database is encoded in UTF8 and with pandas I make sure to load everything in utf-8 (or so I think).

My code looks something like this

```python
for current_folder in range(len(folders)):
    print('\n')
    print("Filling table: " + folders[current_folder])
    path_to_files = path_to_folders + folders[current_folder] + '/'
    table_name = folders[current_folder]
    files = listdir(path_to_files)
    for current_file in tqdm(range(len(files))):
        print("Loading file: " + files[current_file])
        file_path = path_to_files + files[current_file]
        dataframe = pd.read_csv(file_path, compression='gzip', 
                                         header = None, 
                                         sep='\t', 
                                         quoting=csv.QUOTE_NONE,
                                         error_bad_lines=False, 
                                         low_memory=False,
                                         encoding='utf-8')
        db_connection = db_engine.raw_connection()
        db_connection.autocommit = False
        db_connection.set_client_encoding("utf-8")
        db_cursor = db_connection.cursor()
        output = io.StringIO()
        dataframe.to_csv(output, sep='\t', header=False, index=False, encoding='utf-8')
        output.seek(0)
        contents = output.getvalue()
        db_cursor.copy_from(output, table_name)
        db_connection.commit()
        db_connection.close()
```

I've looked everywhere but can't find any feature for the package to fix the data encoding problem.

Is there a feature that takes care of it?

**Comment by dvarrazzo** [comment]
That looks invalid unicode indeed.

```In [2]: b"\xc0\xa7".decode("utf8")                                                                                   
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-2-6cf856539283> in <module>
----> 1 b"\xc0\xa7".decode("utf8")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte
```

I don't know about the encoding of your data, but you are using a function `copy_from()` that doesn't don anything but passing data from your file-like object to Postgres (the error, indeed, comes from the server, not from the client).

I suspect `dataframe.to_csv()` with an `encoding` param converts the dataframe  content to bytes, but because you are writing it into an unicode object (`io.StringIO()`) they get re-encoded. You may try to use `io.BytesIO()` instead.

All in all, the problems you have are in how you craft your data to pass to postgres. You should ask to someone with Pandas expertise.
