### ISSUE TITLE
Can SQL_ASCII be set when server doesn't return client encoding?

### ISSUE THREAD

**Issue by harukat** [psycopg/psycopg2#1236]
Psycopg2 throws a connection error when the DB server doesn't return client_encoding via ParameterStatus ('S') messages.
But psql command allows such a response and set client_encoding as SQL_ASCII.
Some  proxy software or compatible servers doesn't behave the same completely.
I would like to request to loosen the connection check like psql.

Thanks,

**Comment by dvarrazzo** [comment]
It is a reasonable request I guess. However psycopg2 doesn't deal well with a missing encoding and I'm afraid it would throw decoding errors, unless the same care used with SQL_ASCII databases is taken, such as using a bytes typecaster for strings. It might be good to allow the client to set the encoding after connection, but that should be tested too.

Wouldn't utf8 be a better guess in most databases, or a client-provided encoding? This way you would have strings in your applications, not bytes. Psql doesn't do any decoding and if you see non-ascii chars there it's because the console is converting them.

Is there a way to test it? What other database or proxy are you specifically referring about?

I suspect that psycopg3 would work out of the box in this case, but it is still something to be tested. Would you be so kind to try it out?

**Comment by harukat** [comment]
Thank you for your comment.

I think it is inevitable that a server that didn't return client_encoding causes some encoding errors.
An user who uses such a DB server/proxy should avoid or solve the problem by any method.
It shouldn't be psycopg's duty nor consideration.

I met a case nested Pgpool-II connection didn't work with psycopg2 because of the above reason.
I tried psycopg3 and confirmed the new behavior, which didn't throw an error and set utf8 for
a database that has a different server encoding.

May I understand that you are not going to fix psycopg2?

**Comment by dvarrazzo** [comment]
It is a big work for me because I don't have such databases or proxies handy so setting up a test environment for me would take quite some time. I have a pile of tasks with higher priority right now.

If you or anyone else provide a patch it will be well accepted, otherwise it will have to wait for when I have the capacity.

**Comment by harukat** [comment]
Thank you for your sincere answer.
There is already solution, so we will try to consider to switch to psycopg3 firstly.
