### ISSUE TITLE
Issue with setting up idle_timeout for simple connection pool

### ISSUE THREAD

**Issue by saiharshitachava** [psycopg/psycopg2#1241]
Im trying to set up idle_timeout parameter for simple connection and it says as below

psycopg2.ProgrammingError: invalid dsn: invalid connection option "idle_timeout"

Im referring to this doc

https://psycopg2-pool.readthedocs.io/en/latest/#psycopg2_pool.ConnectionPool.idle_timeout

**Comment by dvarrazzo** [comment]
The link you sent is not psycopg2's connection pool but it's an external project implementing a more advanced pool. psycopg2.pool doesn't support that parameter, so it passes it to the connection function, which doesn't recognise it and raises an exception.

I think that your problem is that you haven't installed, or you are not using, the right pool module.

**Comment by saiharshitachava** [comment]
@dvarrazzo  so there is no concept to close idle connections in psycopg2.pool?

**Comment by dvarrazzo** [comment]
No, not for now. it's being designed and implemented in psycopg3 (https://www.psycopg.org/articles/2021/01/17/pool-design/) and it is likely that the new pool design will be usable in psycopg2, but at the moment the pg2 pool is pretty limited.
