### ISSUE TITLE
Does psycogp2 2.6.1 supports postgres 9.6 and above

### ISSUE THREAD

**Issue by karanambhanu** [psycopg/psycopg2#1244]
Hi,

Our app is built on python 2.7/django framework. We have a tight dependency that we can not upgrade any libraires in our requirements file. We use below libraries in our requirements file. There is a mandate from aws that we need to upgrade postgres 9.5 instances to 9.6 and from there eventually to postgres 12. I would like to understand if the below libraries are compatible with postgres 9.6 atleast so that we can live for some more time to run our application.

psycopg2== 2.6.1 
pghstore==0.9.2
psycopg2-binary==2.7.5
psycogreen==1.0

Thanks.

Regards,
Bhanu Prakash

**Comment by dvarrazzo** [comment]
Yes, psycopg2 works no problem with versions of postgres even much older than 9.6.

**Comment by karanambhanu** [comment]
@dvarrazzo - thanks for confirming. We can not upgrade psycopg2 latest version  2.8.6 due to some internal issues in the project. So just wanted to re check once again the 2.6.1 supports  postgres 9.6 or not.  Also, can you please let me know which is the minimal psycogp2 version supported by postgres 12.. Can I use 2.6.1 library for postgres 12.

Thanks for your timely response.

Regards,
Bhanu Prakash

**Comment by dvarrazzo** [comment]
You can use 2.6.1 no problem for the foreseeable PostgreSQL versions. Every time a new Postgres version comes out we run the test suite against it to be sure we support everything. However the network protocol is unchanged since v7.4 and Postgres developer are careful to maintain backward compatibility.

There is no reason to think that old psycopg2 versions will not work with upcoming Postgres versions because psycopg2 itself makes very few and single queries, apart the ones the application does, and changing the network protocol is not on Postgres plans.

**Comment by karanambhanu** [comment]
Thanks @dvarrazzo  for your inputs.
