### ISSUE TITLE
Domain Array type is returned as string, not as list

### ISSUE THREAD

**Issue by dmitriibundin** [psycopg/psycopg2#1285]
`PostgreSQL 13.0 (Debian 13.0-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit`

`psycopg2 version 2.8.6`

Considering an empty postgresql db here are the steps to reproduce:

1. Execute sql `create domain vca as VARCHAR(512);`
2. Execute sql `create domain avca as vca[];`
3. 
```
with psycopg2.connect(...) as conn:
   with conn.cursor() as cursor:
       cursor.execute("select CAST(ARRAY['1', '2', '3'] as avca);")
       for record in cursor.fetchall():
           for v in record:
               print(type(v))
```

**Expected behavior**:
`<class 'list'>` is printed

**Actual behavior**:
`<class 'str'>` is printed

**Comment by dvarrazzo** [comment]
That's because psycopg doesn't know the OID for the array type you want to cast. It will not look it up for you, because the time to do that should be under your control.

You can use `new_array_type()` and `register_type()` to customise the adaptation: see [the docs](https://www.psycopg.org/docs/extensions.html#database-types-casting-functions) for the details.
