### ISSUE TITLE
Please stick to the semantic versioning

### ISSUE THREAD

**Issue by Gui-greg** [psycopg/psycopg2#1303]
Dear Psycopg developers!

I would like to give you hints on how semantic versioning works.

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.

> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY also include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.

You can read this here: https://semver.org/#spec-item-7 and https://semver.org/#spec-item-8

So please next time when you introduce any backwards incompatible change increase the major version instead of the minor, what you did with the 2.9.0.

**Comment by dvarrazzo** [comment]
@Gui-greg 

thank you for the advice. We try to stick to semantic version as much as we can. The change we had to push has a component of security (because the previous implementation was open to SQL injections) but the breakage was unintended: using schema qualified tables in the legacy methods copy_to and copy_from was not covered by the test suite and overlooked.

It was an error I personally made and I apologise to everyone who was affected by it.

Semver protects from intended changes, but breakages may happen for unintended reasons. A safer way to manage dependencies is to use a tool to lock them such as Poetry. I have learned to use the tool the hard way, for (unwanted) changes in certain patch-level dependencies. I am sorry for having been someone's hard way.

-- Daniele
