### ISSUE TITLE
2.9.1 psycopg2-binary fails to install without postgresql-devel (python 2.7.x)

### ISSUE THREAD

**Issue by aureus1** [psycopg/psycopg2#1309]
if pg_config binary is not found, installation fails with:
```
      File "/tmp/pip-build-RVQFcI/psycopg2-binary/setup.py", line 117
        f"Unable to find 'pg_config' file in '{self.pg_config_exe}'")
                                                                   ^
    SyntaxError: invalid syntax

```

fstrings are a python3 construct, so instead of a warning (the intended result) this is fatal as the syntax is invalid

**Comment by dvarrazzo** [comment]
Psycopg 2.9 is not compatible with python 2. or python 3 < 3.6.

**Comment by songololo** [comment]
Where can we find information about the latest psycopg still compatible with Python 2?

**Comment by dvarrazzo** [comment]
Most people would expect them in a "release notes" page in the documentation... and [there they are](https://www.psycopg.org/docs/news.html).

**Comment by songololo** [comment]
@dvarrazzo it would help streamline things (I say this constructively, not bashing efforts) if there were a note in the installation instructions.

Otherwise, it is a process of trial and error. In my case I assumed that the new psycopg was aimed at Python 3 and that pscyopg2 was presumably OK for python 2. So it then becomes an issue of trying to build from source and not realising at first why 2.9.3 doesn't want to build, then digging deeper until realising that 2.9.3 doesn't work with python3. At which point one ends up places like this thread or else looking for release notes as you suggest.

**Comment by dvarrazzo** [comment]
Thank you very much: we can surely add some info there too. Actually [in psycopg 3 docs](https://www.psycopg.org/psycopg3/docs/basic/install.html#supported-systems) we have it already. Opened #1418.
