### ISSUE TITLE
Segmentation fault during instantiation of `psycopg2.extensions.Column`

### ISSUE THREAD

**Issue by OneRaynyDay** [psycopg/psycopg2#1402]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS: Debian 10
- Psycopg version: 2.9.3. Built from source. Also failing in version psycopg2==2.8.6, psycopg2-binary==2.8.6
- Python version: 3.8
- PostgreSQL version: Not applicable
- pip version: 20.2.3

**Describe the bug**
Please let us know: Instantiating the `Column` class leads to segmentation fault

1: what you did: I instantiated the `Column` object because it's in the cursor's `description` field. It was originally used for mocking out testing without directly hitting postgres.
2: what you expected to happen: I expected the Column class to be a lightweight wrapper class that "just works".
3: what happened instead: Segmentation fault for sizes > 16, which I'm guessing is the typical size interpreted by a generic PyObject* rather than a unicode object.

If possible, provide a script reproducing the issue.

```
>>> from psycopg2.extensions import Column
>>> Column("abcdefghijklmnopq")
Column(name='abcdefghijklmnopq', type_code=None)
>>> Column("abcdefghijklmnopq")
Column(name='abcdefghijklmnopq', type_code=None)
>>> Column("abcdefghijklmnopq")
[1]    3950 segmentation fault (core dumped)  python
```

**Comment by dvarrazzo** [comment]
Uhm... smells like #1252 which was supposedly fixed in 2.8.7. Are you positive that this is reproduced in master?

```python
'2.9.3.dev0 (dt dec pq3 ext lo64)'
>>> for i in range(1000000):
...     x = Column("abcdefghijklmnopq")
... 
>>> for i in range(1000000):
...     x = Column("abcdefghijklmnopqrstuvwxyz")
... 
>>> for i in range(1000000):
...     x = Column("abcdefghijklmnopqrstuvwxyz")
... 
```

**Comment by dvarrazzo** [comment]
Your explanation about the issue and the fix proposed in #1403 doesn't convince me: [the `U` code](https://docs.python.org/3/c-api/arg.html#strings-and-buffers):

> U (str) [PyObject *]
>
>    Requires that the Python object is a Unicode object, without attempting any conversion. Raises TypeError if the object is not a Unicode object. The C variable may also be declared as PyObject*.

looks like it doesn't do anything on top of `O` apart from a type check.

> Segmentation fault for sizes > 16, which I'm guessing is the typical size interpreted by a generic PyObject* rather than a unicode object.

I don't know if I'm misreading you, that's not really how Python works. `_make_column` starts with a blanked-out `Column` object (which from python looks like having `None` on each attribute) and then associates the attributes as it goes.

I think the way things went was:

- you used Column manually, and you found the bug #1252.
- you checked out master but by mistake tested 2.8.6 again
- you fixed the bug, compiled the library
- you tested the right thing this way, and the bug wasn't there anymore.

I also just noticed that, unlike what stated [in the news file](https://www.psycopg.org/docs/news.html#what-s-new-in-psycopg-2-8-7) there has never been a release 2.8.7: the bug fix was released in 2.9 instead. Could you please check if the problem is in 2.9.2?

Thank you very much.

**Comment by OneRaynyDay** [comment]
Ah, apologies for this! You're right - I must've tested the wrong version. Building from source the newest version no longer shows the segfault. I'll close this issue and the corresponding PR.

I'm not very familiar with the C API, so just out of curiosity, why don't we use `U` instead of `O` on the column name? Is it so we can accept other string-like types in the future?

**Comment by dvarrazzo** [comment]
Duck typing I guess :D This object is only used in one code path, getting the name argument from a function that only returns strings, and is only used to return data to the user, psycopg doesn't do anything else with it. Making every attribute strict (why the name should be strict and the other attributes no?) would be a lot of checking for not immensely practical use.

Python and every Python program is full of functions which just trust the user to pass arguments of the right type, and the mainstream approach is "if this must fail, it will fail somewhere down the line". Questionable for some, so mypy exists, but a perfectly valid way of writing programs.

I don't believe you add an `if not isinstance(param, str): raise TypeError("the name must be a string")`, to every function you write, right? If someone feels that that's the right way to do things, I think the solution would be to start using `mypy --strict` rather than adding check to every single parameter of every single function.
