### ISSUE TITLE
How do I tell if I have installed binary or non-binary version?

### ISSUE THREAD

**Issue by scythargon** [psycopg/psycopg2#1413]
Hi and thank you for your incredible work! 

I'm moving our project's dependency engine from pip-tools to poetry which have different ways to specify if it should install binary or non-binary version. 

My question - is how do I tell psycopg versions apart after the installation? To make sure that I've installed non-binary one.

I've looked into the code, there is `psycopg2.BINARY` object with name and values fields, but they seem to show the same in both versions. and in the installed package directory I don't see any differences as well.

Thank you!

**Comment by dvarrazzo** [comment]
Hello, thank you :)

> I'm moving our project's dependency engine from pip-tools to poetry which have different ways to specify if it should install binary or non-binary version.

Ah curious, I have done the opposite in my projects...

`psycopg2.BINARY` is a wrapper for binary data to send to the db, it's not related to the binary package.

Honestly I haven't thought about a way to tell the packages apart at runtime. In psycopg 3 there is `psycopg.pq.__impl__` but that's because the C speedup module is optional.

One way that comes to mind is to use importlib_metadata to inspect the installed package. You want to have an error looking for the version of `psycopg2-binary` and no error looking for `psycopg2`

```
(venv) piro@baloo:~/tmp$ pip install importlib_metadata
...
Successfully installed importlib-metadata-4.10.0 zipp-3.7.0
```

```python
>>> from importlib_metadata import version
>>> version("psycopg2-binary")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/piro/tmp/venv/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 978, in version
    return distribution(distribution_name).version
  File "/home/piro/tmp/venv/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 951, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/piro/tmp/venv/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 542, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for psycopg2-binary

>>> version("psycopg2")
'2.9.3'
```

Would this work?

**Comment by scythargon** [comment]
Thank you for the answer!

No, imagine two ways to install it:

`pip install psycopg2`

VS

`pip install psycopg2 --no-binary psycopg2`


Is there a way to tell the resulting environments or filesystems apart?

**Comment by dvarrazzo** [comment]
Ah I see. In that case I don't think it would be possible to tell them apart, however `--no-binary` shouldn't be needed anymore. It was needed in version 2.7, because we distributed both source and binary files under the `psycopg2` distribution name (see https://pypi.org/project/psycopg2/2.7/#files - you can see the manylinux wheel packages).

Starting from psycopg 2.8, in order to "opt-in" into using binary, we started distributing the binary package under the distribution name `psycopg2-binary`, and `psycopg2` only includes the source (see https://pypi.org/project/psycopg2/2.8/#files - the binaries are only for windows).

So, as long as you install `psycopg2 >= 2.8` you can be sure that you have installed the non-binary version.

---

if you want to be _even more sure_, you can take a look if the `psycopg_binary.libs` directory exists in the pythonpath, where `psycopg2` package is installed. In case of binary installation:

```python
>>> import psycopg2
>>> from pathlib import Path
>>> (Path(psycopg2.__file__).parent.parent / "psycopg2_binary.libs").exists()
True
```
in case of source installation, that dir won't exist. If you look for the `psycopg2.libs` directory too you could detect older psycopg2 binary installations.
