### ISSUE TITLE
psycopg2.OperationalError: could not translate host name "X.postgres.database.azure.com" to address: Name or service not known

### ISSUE THREAD

**Issue by HGamalElDiin** [psycopg/psycopg2#1416]
**Please complete the following information:**
- OS: Linux server
- Psycopg version: 2.7.7
- Python version: 3.7
- PostgreSQL version: 11
- pip version 21.3.1

**Describe the bug**
in the requirments.txt if i defined the version 2.9.2 or higher it raises an error while building the docker image, and when it's not specified it uses only 2.7.7 version.. suddenly it raises this exception perhaps the host name is working normally locally in windows machine with Psycopg version: 2.9.2

I tried to upgrade pip to install higher version with no hope.

Any relevant updates?

**Comment by dvarrazzo** [comment]
Hello,

the error you see, at connection time, is not related to the version of psycopg you are using. If you see that exception it actually means that psycopg is installed correctly, otherwise you would have an error at import time.

It seems to me that your DNS name resolution is not working correctly inside Docker. For a test, try to ping the same host, or even better try to connect with psql using the same connection string you have in python: you should see it failing with exactly the same error.

I hope this helps
