### ISSUE TITLE
Please build manylinux wheels

### ISSUE THREAD

**Issue by con-f-use** [psycopg/psycopg2#1417]
On a few systems install psycopg from it's sourcedistributions fails because of library issues. Would it be feasible to provide wheels as you do for windows?

**Comment by dvarrazzo** [comment]
Manylinux wheels have been made available in the last release, 2.9.3.  They are distributes in the [`psycopg2-binary`](https://pypi.org/project/psycopg2-binary/#files) package.

Binary packages are not released under the `psycopg2` name because using binary packages should be opt-in, not opt-out, and in the past they had compatibility problems (look for the issues tagged "binary" if you are interested). Please check the `install` page in the docs for all the information about installation.
