### ISSUE TITLE
Basestring errors upon import on fresh pip installation inside a virtualenv

### ISSUE THREAD

**Issue by mikrl** [psycopg/psycopg2#1419]
**Environment:**
- OS: Debian GNU/Linux 11 (bullseye) / Docker image python:3.7-bullseye
- Psycopg version: 2.7.3.2
- Python version: 3.7.12 (virtualenv)
- PostgreSQL version: N/A
- pip version: 21.3.1

**Description:**
Importing psycopg2 fails with a NameError: name 'basestring' is not defined.
Inspecting the source code installed in the venv reveals that it is a python2.7 source file.

**Expected Behaviour:**
Import succeeds.
Pip installing psycopg2 retrieves a python3 source file.

**Actual Behaviour:**
Importing psycopg2 fails with a NameError: name 'basestring' is not defined.
Pip installing psycopg2 retrieves a python2.7 source file. 

**Steps to Reproduce:**
```
docker run -it python:3.7-bullseye /bin/bash
pip install virtualenv
virtualenv test
source test/bin/activate
pip install psycopg2==2.7.3.2 
python -c  'import psycopg2'
```

**Comment by dvarrazzo** [comment]
Before 2.8, paycopg was using 2to3 to be used both on Python 2 and 3, as it was customary at time. Maybe something has changed in pip?

However that's out of control. If something has changed in the python build tool so that such an old version cannot be installed anymore I doubt we can do anything about it. Please install paycopg 2.8 or following.
