### ISSUE TITLE
SSL SYSCALL error: EOF detected

### ISSUE THREAD

**Issue by timforr** [psycopg/psycopg2#1445]
I am using a ThreadedConnectionPool in a Flask app, and using context manager to get and return connections to the pool. The pattern I am using is this:

```
PS_POOL = ThreadedConnectionPool(10, 100, host=PGURL, user=PGUSER, password=PGPASSWORD, port=5432)

@contextmanager
def get_cursor():
    conn = PS_POOL.getconn()
    conn.autocommit = True
    try:
        cursor = conn.cursor(cursor_factory=RealDictCursor)
        yield cursor
    finally:
        cursor.close()
        PS_POOL.putconn(conn)

with get_cursor() as cursor:
    cursor.execute("some query")
```

As you can see, my context function closes the cursor and then puts the connection back into the pool when it is finished. My issue is that I am occasionally seeing the error ```SSL SYSCALL error: EOF detected``` when performing a query. This error happens a few times in a row after inactivity, and then the call will start working again, so I assume some of the connections in the pool are corrupted somehow. I'm filing this as an issue because I assume the connection pool should be returning working connection objects.

**Comment by dvarrazzo** [comment]
Yes, it is an issue, but it cannot be fixed easily, and will not be fixed in psycopg 2.

Psycopg 3 pool works better. About psycopg 2, there are [ways to detect disconnections](https://www.psycopg.org/psycopg3/docs/advanced/async.html#detecting-disconnections) which can be used with psycopg 2 pool too. Psycopg 2 pool doesn't have a `check()` method like psycopg 3 does, but all in all it's a simple object and it wouldn't be a problem to empty it.

More details about what can and can't be done is also available in [psycopg 3 pool docs](https://www.psycopg.org/psycopg3/docs/advanced/pool.html#connection-quality).

For psycopg-pool 3.2 I am considering to introduce an automatic disconnection check: https://github.com/psycopg/psycopg/issues/247 for details.

Whatever happens, it will not happen in psycopg 2: its pool is a really simplistic object and it is not a good base to bolt other features on top of it. It is not an "active" object, like psycopg 3 one, so there is not really a way to check for connection quality in the background and I don't want to add a check on getconn for reasons explained in the docs linked above.

**Comment by arabinda-g** [comment]
It fixed for me after increasing server resources (including CPU and RAM).

**Comment by Govind10g** [comment]
Hi @arabinda-g  - 
Good to know you fixed this issue and I m also facing it btw like occasionally seeing the error SSL SYSCALL error: EOF detected when performing a query.

So where did you increase the CPU and RAM ? 
Have you observed any insufficient CPU and memory which give you the evidence to increase it ?

**Comment by arabinda-g** [comment]
Hi @Govind10g 

I was occasionally seeing the error too. Then I observed insufficient CPU and RAM usage while there was high traffic using the `htop` command. So, I upgraded the VPS to get higher CPU and RAM, which resolved the issue.

You can install htop on Ubuntu using `apt install htop`

**Comment by Govind10g** [comment]
@arabinda-g  - You mean you increased the CPU/Memory of your Application server Not DB  instance ?

**Comment by arabinda-g** [comment]
The Flask application and PostgreSQL server is hosted on the same server.

**Comment by Govind10g** [comment]
Hi @dvarrazzo -

I tried to reduce the tcp_keepalive_idle to lower value i.e. 5 sec but still getting `SSL SYSCALL error: EOF detected` as per this blog -> https://www.cybertec-postgresql.com/en/tcp-keepalive-for-a-better-postgresql-experience/#reasons-for-broken-connections

Any idea, what should I do to debug and fix this issue ?

**Comment by pkit** [comment]
@dvarrazzo 
> I don't want to add a check on getconn for reasons explained in the docs linked above

I cannot find anything regarding that in the linked docs.
Overall it's not clear what's the lifecycle of a "bad" connection?
Is it detected on `putconn()`? I can see that it uses `close` on `TRANSACTION_STATUS_UNKNOWN` ones, but it's not clear who sets that, and when?
For now, just by looking at the code, I suppose the safest is just to
```python
try:
  conn.close()
except psycopg2.Error:
  pass
finally:
  pool.putconn(conn)

```
On any "final" error.
It looks like `libpq` does not make it any easier for users either.

**Comment by dvarrazzo** [comment]
@pkit with the latest version of the psycopg 3 pool, it is possible to register a check function on getconn. The documentation changed in the almost 3 years from that message.

That, however is about psycopg 3 pool, not psycopg2 pool, for which no new development is scheduled.
