### ISSUE TITLE
set_session cannot be used inside a transaction with sqlalchemy and pool_pre_ping

### ISSUE THREAD

**Issue by arpekkar** [psycopg/psycopg2#1452]
Because connection drop issues I needed to start using pool_pre_ping with sqlalchemy. 

```
engines = {
      "writer": create_engine(
          f"postgresql+psycopg2://{username}:{password}@{writer_endpoint}:{port}/{database}",
          logging_name="writer",
          pool_pre_ping=True,
      ),
}
```

Now I'm facing a new issue: 

```
File "/opt/python/sqlalchemy/dialects/postgresql/psycopg2.py", line 850, in do_ping
dbapi_connection.autocommit = True
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) set_session cannot be used inside a transaction
(Background on this error at: http://sqlalche.me/e/14/f405)
```

I read from [here](https://github.com/dbcli/pgcli/issues/646) that downgrading to 2.6.2 would solve these issue. Should I do that?

- OS: Linux
- Psycopg version: 2.9.1
- Python version: 3.8.10
- PostgreSQL version: 13.3

**Comment by dvarrazzo** [comment]
I would say that this is an issue in sqlalchemy, not in psycopg. Looks like the pre-ping leaves a transaction open. Autocommit should be set before that, not after a transaction is open. Older version probably would have closed the transaction, but it was an excess of favour of a program that is doing something wrong, and made that behaviour stricter.

Psycopg is only reporting something that the client shouldn't do, because it's not possible. Don't shoot the messenger.

> I read from https://github.com/dbcli/pgcli/issues/646 that downgrading to 2.6.2 would solve these issue. Should I do that?

That's an 8 years old version: it doesn't seem wise. Please also note that it is a bug reported in a client that then proceeded to be fixed. You can probably obtain the same.

**Comment by arpekkar** [comment]
Alright, fair enough, I will raise this in sqlalchemy repo!
