### ISSUE TITLE
Failed to bundle `psycopg2-binary` into RPM package

### ISSUE THREAD

**Issue by bebound** [psycopg/psycopg2#1460]
**Please complete the following information:**
- OS:CentOS7
- Psycopg version:2.9.3
- Python version:3.6.8
- PostgreSQL version:
- pip version21.3.1

**Describe the bug**
1: what you did
I try to build a python RPM package which install `psycopg2-binary` as requirements.
2: what you expected to happen
The RPM package works.
3: what happened instead
`Failed dependencies` error is raised when install the built package.
```
error: Failed dependencies:
	libcrypto-2f2fcd35.so.1.1(OPENSSL_1_1_0)(64bit) is needed by hello-world-1-1.x86_64
	libcrypto-2f2fcd35.so.1.1(OPENSSL_1_1_0d)(64bit) is needed by hello-world-1-1.x86_64
	libcrypto-2f2fcd35.so.1.1(OPENSSL_1_1_0f)(64bit) is needed by hello-world-1-1.x86_64
	libcrypto-2f2fcd35.so.1.1(OPENSSL_1_1_0i)(64bit) is needed by hello-world-1-1.x86_64
	libcrypto-2f2fcd35.so.1.1(OPENSSL_1_1_1)(64bit) is needed by hello-world-1-1.x86_64
	libgssapi_krb5-497db0c6.so.2.2(gssapi_krb5_2_MIT)(64bit) is needed by hello-world-1-1.x86_64
	libk5crypto-b1f99d5c.so.3.1(k5crypto_3_MIT)(64bit) is needed by hello-world-1-1.x86_64
	libkeyutils-dfe70bd6.so.1.5(KEYUTILS_0.3)(64bit) is needed by hello-world-1-1.x86_64
	libkeyutils-dfe70bd6.so.1.5(KEYUTILS_1.0)(64bit) is needed by hello-world-1-1.x86_64
	libkeyutils-dfe70bd6.so.1.5(KEYUTILS_1.5)(64bit) is needed by hello-world-1-1.x86_64
	libkrb5-fc820a1d.so.3.3(krb5_3_MIT)(64bit) is needed by hello-world-1-1.x86_64
	libkrb5support-a4e68a84.so.0.1(krb5support_0_MIT)(64bit) is needed by hello-world-1-1.x86_64
	libssl-6b7b94d5.so.1.1(OPENSSL_1_1_0)(64bit) is needed by hello-world-1-1.x86_64
	libssl-6b7b94d5.so.1.1(OPENSSL_1_1_1)(64bit) is needed by hello-world-1-1.x86_64
```

If I remove auto generated dependencies, I can install the package. But if I set `PYTHONPATH` to package's `site-packages` path and run python3, calling `import psycopg2` will raise `error while loading shared libraries: libpq-30c1c89d.so.5.14: ELF load command address/offset not properly aligned`.

If I modify the spec file and use `psycopg2` instead, everything works.

If possible, provide a script reproducing the issue.

1.  `docker run -it centos:centos7 bash`
2. run this script in docker:
```bash
yum update -y
yum install -y wget rpm-build python3

cat > demo.spec << 'EOF'
%global __python %{__python3}
# Turn off python byte compilation
%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')

Name:       hello-world
Version:    1
Release:    1
Summary:    Most simple RPM package
License:    FIXME

%description
This is my first RPM package, which does nothing.

%prep
# we have no source, so nothing here

%install
python3 -m venv %{buildroot}/kk
source %{buildroot}/kk/bin/activate
pip install --upgrade pip
pip install psycopg2-binary==2.9.3
deactivate

rm %{buildroot}/kk/bin/python* %{buildroot}/kk/bin/pip*

for d in %{buildroot}/kk/bin/*; do perl -p -i -e "s#%{buildroot}##g" $d ; done;


%files
%exclude /kk/bin/
%attr(-,root,root) /kk

EOF

rpmbuild -v -bb  demo.spec
cp /root/rpmbuild/RPMS/x86_64/hello-world-1-1.x86_64.rpm kk.rpm
rpm -i kk.rpm
```

**Comment by dvarrazzo** [comment]
Bundling -binary in RPM makes no sense: you would introduce a copy of system packages (possibly from a mismatched Centos version) when instead you can depend on the system ones. Apart from pointing that out, I don't have any expertise on RPM building to assist more.

If you are doing so because you have some package depending on psycopg2-bunary, just sed s/psycog2-binary/psycopg2/ them to fix their dependencies. Package maintainers are asked to not depend on psycopg2-binary: it causes problems because it can't be installed alongside psycopg2.

**Comment by bebound** [comment]
Thanks for your reply, this problem can be solved by manually changing the dependency.

Out of curiosity, could you please elaborate on this: *Package maintainers are asked to not depend on psycopg2-binary*? Does it related to the so files in `psycopg2_binary.libs`?

**Comment by dvarrazzo** [comment]
There are two distribution packages (aka what is uploaded on PyPI): `psycopg2` and `psycopg2-binary`,  both of which install the same package (aka what can be imported by Python: `psycopg2`). Python packages metadata are unable to express this and some files are installed in the same location by the two packages: installing both in the same env will overwrite each other's file, removing one of them will break the others, and all the funny things.

As a consequence we ask, collaboratively, to express only one in a project dependency. Between the two, we choose `psycopg2` because of [several issues with the wheel packages](https://github.com/psycopg/psycopg2/issues?q=label%3Awheel).

The situation is improved in psycopg 3, where the base package (`psycopg`) is Python only, and speed-up add-on distribution packages install independent Python packages, which don't trample on each other.

- psycopg 2 docs: [psycopg vs psycopg-binary](https://www.psycopg.org/docs/install.html#psycopg-vs-psycopg-binary)
- psycopg 3 docs: [handling dependencies](https://www.psycopg.org/psycopg3/docs/basic/install.html#handling-dependencies)
