### ISSUE TITLE
Support for getting the exact record/column which is failing while doing a bulk insertion using execute_values.

### ISSUE THREAD

**Issue by nirosha9** [psycopg/psycopg2#1472]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS: windows 10
- Psycopg version: 2.9.3
- Python version: 3.9
- PostgreSQL version: 
- pip version: 22.1.2

**Describe the bug**
Please let us know:

1: what you did

-      I am trying to insert multiple rows into the postgress db using execute_vlaues with a batch of 1000 records.
        `execute_values(cursor, query, rows, page_size=1000)`

-     Here we a have a column 'abc' defined with NUMERIC(10,5) but in one of the records, the value of 'abc' is with precision 16 and scale 5.

       
2: what you expected to happen

-  A detailed error message with the exact row/column, which is breaking the insert/update operation due to any violation.

3: what happened instead

-  We are getting a generic error message like below, with which we couldn't figure out the one error causing record out of thousands.
     **'numeric field overflow\nDETAIL: A field with precision 16, scale 5 must round to an absolute value less than 10^11.\n'**

If possible, provide a script reproducing the issue.

**Comment by dvarrazzo** [comment]
This is not possible, in a general way.

In the psycopg 3 test suite I wrote code similar to the one you describe, in order to find which random value fails, but it relies on the possibility of rolling back the transaction and retrying.

https://github.com/psycopg/psycopg/blob/4740e20083b169eef9033cc7c5345c6718f7e761/tests/fix_faker.py#L137-L158

If you want to do something similar, you can do it from the application, if you know the life cycle of your table and records, but the driver cannot make guesses valid for everyone.
