### ISSUE TITLE
copy_to with temporary table fails

### ISSUE THREAD

**Issue by MaestroGlanz** [psycopg/psycopg2#1530]
I have a temporary table in this connection. 
1. I drop it, if exists
2. I commit to assure dropping
3. I create it with (next) data set
4. I count the elements in the EXPORT_TEMP
5. I try to copy_to some file (If the table doesn't exist, I assume, that there were put zero elements into the EXPORT_TEMP)
6. I count the elements in the EXPORT_TEMP

```
    f = open(connection['backupPath'] + filename + ".csv'", 'w+')
    pg_cursor.execute("DROP TABLE IF EXISTS EXPORT_TEMP;")
    print(pg_cursor.statusmessage)
    pg_cursor.execute("COMMIT;")
    print(pg_cursor.statusmessage)
    current_sequence = "CREATE TEMPORARY TABLE EXPORT_TEMP AS (SELECT * FROM sometable where id > 5 and id < 100);"
    pg_cursor.execute(current_sequence)
    print(pg_cursor.statusmessage)
    pg_cursor.execute("SELECT count(*) FROM EXPORT_TEMP")
    print(pg_cursor.fetchall())
    try:
        pg_cursor.copy_to(f, "EXPORT_TEMP", ";", "\\N")
    except psycopg2.errors.UndefinedTable:
        print("Returned table is empty")
    pg_cursor.execute("SELECT count(*) FROM EXPORT_TEMP")
    print(pg_cursor.fetchall())
    f.close()
```

The result is:
```
DROP TABLE
COMMIT
SELECT 201
[(201,)]
Returned table is empty
[(201,)]
```

As you see, the temporary table is created and contains the correct number of elements. However copy_to doesn't find it.

I can not use COPY as in copy_expert, as I'm not an admin of the database. So, I MUST use copy_to.

**Comment by dvarrazzo** [comment]
Your problem is probably that you are specifying `EXPORT_TEMP` in uppercase. your `create table` statement doesn't do what you expect, and creates a table in lowercase, as explained in [Postgres documentation](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS). `copy_to()` takes what you asks literally and will refer to a table called `EXPORT_TEMP` in uppercase.

Using `pg_cursor.copy_to(f, "export_temp", ";", "\\N")` should do what you expect.

> I can not use COPY as in copy_expert, as I'm not an admin of the database. So, I MUST use copy_to.

This makes no sense. `copy_to` just composes a "COPY" statement in a string and executes it.

https://github.com/psycopg/psycopg2/blob/e8d92b74fd4b219cb4725cb906c526f3f2dce31d/psycopg/cursor_type.c#L1514-L1515

There is no need of being a database admin. Where did you even read that?

If you used `copy_expert()` directly you wouldn't have this problem, because the statement you execute will have the same case mismatch you made creating the table.
