### ISSUE TITLE
Using intervalstyle iso_8601 not supported

### ISSUE THREAD

**Issue by ninas** [psycopg/psycopg2#1541]
Hi there,
I've got my database using iso_8601 as the style for interval data: https://www.postgresql.org/docs/15/datatype-datetime.html#DATATYPE-INTERVAL-OUTPUT
However, when querying from this database, I get the following error:
```
psycopg2.NotSupportedError: iso_8601 intervalstyle currently not supported
```

Basic example:
```
CREATE DATABASE test;
ALTER DATABASE test SET intervalstyle = 'iso_8601';
CREATE TABLE test_table (id SERIAL PRIMARY KEY, duration INTERVAL);
INSERT INTO test_table(duration) VALUES ("PT10M");
```
and then:
```
import psycopg2
conn = psycopg2.connect("dbname=test user=postgres")
cur = conn.cursor()
cur.execute("SELECT * FROM test_table;")
cur.fetchone()
```
Is this something that there are plans to add? I know that timedelta doesn't support creating objects from iso8601 strings by default, so I understand if there's a desire to avoid using an additional library to do that.

**Comment by dvarrazzo** [comment]
~It is supported in psycopg 3.~ No, not true: I've double checked and it doesn't support other `IntervalStyle` either, only other `DateStyle`. However psycopg 3 supports binary format, which is unaffected by interval style.

You can avoid the problem in text mode by setting the postgres interval style in the connection string, using the `options` parameter (which takes command line switches, hence the weird `-c`):

```
$ psql "host=localhost options='-c intervalstyle=sql_standard'"
psql (15.1 (Ubuntu 15.1-1.pgdg22.04+1))

=# show intervalstyle;
┌───────────────┐
│ IntervalStyle │
├───────────────┤
│ sql_standard  │
└───────────────┘
(1 row)
```

so, from your example, you can try one of the following:

```python
psycopg2.connect("dbname=test user=postgres options='-c intervalstyle=postgres'")
psycopg2.connect("dbname=test user=postgres", options="-c intervalstyle=postgres")
```

I doubt the features will be implemented, because the request for it is minimal (this is likely the first in 16 years) and there are easy workarounds.
