### ISSUE TITLE
Autocommit does not work with context management

### ISSUE THREAD

**Issue by INRIX-Mark-Gershaft** [psycopg/psycopg2#1742]
According to the documentation context management should be used for transaction isolation. However, it conflicts with the autocommit property of the connection object.

**Please complete the following information:**
- OS: Windows
- Psycopg version: 2.9.3
- Python version: 3.12
- PostgreSQL version: N/A
- pip version N/A

**Describe the bug**
Please let us know:

1: what you did
Attempted to use context management with SQL that has its own transaction management.
2: what you expected to happen
context management be aware of transaction isolation
3: what happened instead
different behavior with and without context management.
If possible, provide a script reproducing the issue.
```
# Test transaction block
def foo(pcc):
  with pcc.cursor() as cur:
    cur.execute('do $$\nbegin\ncommit;\nend $$;')

pcc = pc.connect()  # pc object has login information and calls psycopg2.connect() with proper parameters
pcc.autocommit = True
foo(pcc)  # Works

with pcc:
  foo(pcc)   <<< crashes
```

**Comment by INRIX-Mark-Gershaft** [comment]
At least this should be properly documented that context management conflicts with autocommit.

**Comment by dvarrazzo** [comment]
The context manager works perfectly well with autocommit and manages an
explicit transaction. The behaviour is documented.

In psycopg2 the context manager manages an explicit transaction. If you
want to manage the transaction on your own you shouldn't use the context
manager.

If you are using the context manager with the expectation that it will
close the connection at the end, no, this is not what psycopg2 does. It is
not intuitive but it is documented as well.

Maybe you could find useful to move to psycopg 3, because

1) unlike psycopg2, a context manager closes the connection at the end
(transactions are explicitly started by a `transaction()` method.

2) psycopg2 connections have a flag that tracks the in/out of transaction
state, so changing this state using SQL statement can put it in
inconsistent state; psycopg 3 instead uses a libpq function to get the
in/out trans state which is not fooled by SQL transaction control commands.

**Comment by INRIX-Mark-Gershaft** [comment]
Then maybe you should update documentation about the conflict with autocommit?
