### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by psmoros** [psycopg/psycopg2#1747]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@samplebias) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by JamesParrott** [comment]
Thanks Pavlos and SampleBias.  It's not best practise, but by its very nature, Psycopg2 will run arbitrary SQL via `cur.execute` on the DB it's connected to (i.e. this is a feature, not a bug).  

Is the vulnerability you've found something else?

**Comment by dvarrazzo** [comment]
you can write me privately.

**Comment by SampleBias** [comment]
ok thank you for the clarification, and sorry to bother:) I was just thinking somewhere along the lines of this, Using PQexec() without parameterization or validation is like leaving your database's front door wide open, and I could very well be wrong. If query includes any user input, you're inviting attackers to inject SQL code, but I understand that If the vulnerability cannot be directly exploited due to existing usage constraints within psycopg2 (i.e., if query isn't influenced by external user input in standard library use) then it doesnt really matter. So I am still wrapping my brain around, Verification of how query is populated and if user input can realistically flow into it unfiltered in "normal" psycopg2 use and the low-level communication with the PostgreSQL database through the libpq library and the pqpath.c

**Comment by dvarrazzo** [comment]
@SampleBias please read the basic usage of the package and feel free to read the code.
