### ISSUE TITLE
High macOS deployment targets for psycopg2-binary

### ISSUE THREAD

**Issue by bwoodsend** [psycopg/psycopg2#1753]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Before opening this ticket, please confirm that:**
- [x] I am running the latest version of pip, i.e. typing ``pip --version`` you get [this version](https://pypi.org/project/pip/).
- [x] I have read the [installation documentation](https://www.psycopg.org/docs/install.html) and the [frequently asked questions](https://www.psycopg.org/docs/faq.html)
- [ ] If install failed, I typed `pg_config` on the command line and I obtained an output instead of an error.

**Please complete the following information:**
- OS: macOS 13 arm64 
- Psycopg version: 2.9.10
- Python version: 3.12.7
- PostgreSQL version:
- pip version: 24.3.1

The `MACOSX_DEPLOYMENT_TARGET` sets the minimum version of macOS that the `psycopg2-binary` wheels will install on so the introduction of [setting MACOSX_DEPLOYMENT_TARGET to the CI runner version](https://github.com/psycopg/psycopg2/commit/a59079a4f2c4af12224a385eff4397954b647293#diff-5bcf795eb775d7afa43ccd6534c336b59bc441c814c20f4b30603fa7d50fb03cR171) blocks installs on anything older than the CI runner. As of `2.9.10`, `pip install psycopg2-binary` on a macOS <14.0 arm64 or <12.0 x86_64 machine will ignore the wheels, pull the sdist, probably fail to build from source and give the misleading advice to try `pip install psycopg2-binary` instead.

Judging by the lack of *drop support for macOS 13* entries in the changelog and macOS 13 still having another year before its EOL date, I'm guessing that wasn't intentional?

Incidentally, why publish sdists for the `psycopg2-binary` package?

**Comment by dvarrazzo** [comment]
Hello,

The variable was added because latest cibuildwheel versions require it. If omitted, build fails. I haven't found a simple workaround. See also discussion at https://github.com/pypa/cibuildwheel/discussions/1926

We don't declare support for specific OS, we only declare support for specific Python versions. Binary packages are produced on a best-effort basis.

The presence of the source in the binary package was for a fallback for people adding `psycopg2-binary` in the `requirements.txt` and making impossible to install dependencies on platforms not supporting binary. Psycopg 3 uses [a different and better strategy](https://www.psycopg.org/psycopg3/docs/basic/install.html#handling-dependencies).

As my competence with macOS is limited and I had made my attempts at the time of releasing the latest version, I will close this ticket here. If you think you can provide a solution to the problem, a MR is welcome.
