### ISSUE TITLE
Psycopg2-binary Compatibility

### ISSUE THREAD

**Issue by christian98b** [psycopg/psycopg2#1765]
Hello,

I encountered an issue while attempting to install the package on my Snapdragon X Elite Arm64 Windows machine. It appears that the pyscopg2-binary is not available for this architecture.

To provide further context, here are the details of my environment:
* Operating System: Windows Arm64
* Psycopg version: 2.9.10
* Python version: 3.13.0
* PostgreSQL version: (not specified)
* pip version: 24.3.1

If you need any additional information or assistance in reproducing this issue, please let me know.

**Comment by dvarrazzo** [comment]
Unfortunately, that's correct: Windows arm64 is not supported because there are no available builders to build packages for this architecture.

Supporting this architecture will require purchasing hardware or renting a VM in Azure (which seem [available in preview](https://learn.microsoft.com/en-us/windows/arm/create-arm-vm)) and some work to reimplement the build system for all the depending libraries (openssl, libpq) because there's nothing available for arm64.

If you are interesting in funding this development, please let us know.
