### ISSUE TITLE
DictRow should behave like an OrderedDict?

### ISSUE THREAD

**Issue by psycoteam** [psycopg/psycopg2#177]
Originally submitted by: Laurent Fasnacht

I think RowDict should behave like an OrderedDict. In particular, I would expect the following to be True:

``` python
[row_dict[k] for k in row_dict.keys()] == list(row_dict)
```

**Comment by auvipy** [comment]
Dict's are Ordered from 3.6

**Comment by kumatty** [comment]
I encountered the same issue when I tried to export csv from a postgres database. I used the first dict row's keys as the csv header and I realized the csv header and the data do not match. At least it worked with python's native sqlite3 adapter when I used sqlite3, i.e., keys of a row and actual data of a row are in the same order.

I would like to suggest to change a little bit DictRow#keys implementation as per the following:
```
def keys(self):
  - return self._index.keys()
  + return sorted(self._index, key=self._index.get)
```

Or at least it would be nice to have a method like `ordered_keys`. What do you think?

(For now I made a super class of DictRow that overrides keys() as workaround.)

**Comment by dvarrazzo** [comment]
You can use `[d[0] for d in cur.description]` as keys: that will work and is available even when your dataset is empty.

**Comment by kumatty** [comment]
Thanks for your quick reply, I actually didn't know that but the thing is I do not have a cursor object when I actually process the data. I know this is just our implementation problem but if DictRow has the information of keys I think it would be nice to know the order of the keys too.
I also think our situation is not quite limited because in many code "how we get the data" and "how we process the data" are separated.

**Comment by dvarrazzo** [comment]
Sure. For the moment you'll have to use your own subclass of `DictRow`. If you have an improvement to propose patches are welcome.
