### ISSUE TITLE
Mogrify performance on arrays

### ISSUE THREAD

**Issue by psycoteam** [psycopg/psycopg2#179]
Originally submitted by: ChrisB

If I run cursor.mogrify on a 64000 double array it is taking 350ms. If I just do a 'ARRAY[' + ','.join(map(str, array)) + ']' and put it into a string format myself it only takes 55ms. Although the documentation tells you not to do this, it is bringing the insert time of my app down massively.

**Comment by jonathanstrong** [comment]
Found this as I am struggling with poor performance on inserting arrays. 

In my case, trying to insert float array of shape (256, 256, 3, 3). The query itself takes 454 ms. Executed via psycopg2 is 2.68 s. Mogrify for an array of that size takes 1.44 s. 

Selecting one row from a table of 4d arrays takes 420ms. 

I clearly seem to be outside of normal usage patterns for this, but storing n-dimensional arrays transparently in postgresql, with all the data structure/integrity that offers, would be huge. Any thoughts on how to improve this situation?

**Comment by mamikonyana** [comment]
I have a similar problem when storing a bunch of arrays of 1000 length in postgres, it seems that most of the time spent is when type checking because I get noticeable performance boost when I write raw sql queries (using string formatting in python).

using psycopg2 I get 10.8 seconds to insert 2200 rows
using raw queries I get it down to 4.8 seconds.

Any updates on the solution? I'd love not to write raw sql :)

**Comment by dvarrazzo** [comment]
Fixed in psycopg3. Will not work further on this in psycopg2.
