### ISSUE TITLE
Error while converting time 24:00:00

### ISSUE THREAD

**Issue by fogzot** [psycopg/psycopg2#278]
PostgreSQL can store `time` (with or without TZ) values from 0:00:00 to 24:00:00 while Python `datetime.time` only accepts values up to 23:59:59 (stupid the package that can't represent leap seconds is!)

    >>> import psycopg2
    >>> conn = psycopg2.connect("dbname=test")
    >>> curs = conn.cursor()
    >>> curs.execute("SELECT '24:00:00'::time")
    >>> curs.fetchall()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ValueError: hour must be in 0..23

Note that this is only about `time` values: PostgreSQL seems to always convert a `timestamp` ending in 24:00:00 into the midnight of the day after, i.e., 2012-6-30T24:00:00 -> 2012-7-1T00:00:00.

Reference to StackOverflow question: http://stackoverflow.com/questions/27919727/postgresql-time-conversion-formatting-from-240000-to-000000-in-select-st/27920175

**Comment by dvarrazzo** [comment]
Ha, problems ahead! Well, we already had leap seconds in our lifetime, didn't we?

I'm not sure silently converting the data for that second is something we want to do so lightly: a monotonic sequence of PG timestamps would see time going backwards in python:

    23:59:00.0  23:59:00.0
    23:59:00.5  23:59:00.5
    24:00:00.0  00:00:00.0
    24:00:00.5  00:00:00.5
    00:00:00.0  00:00:00.0  <- Time went backwards
    00:00:00.5  00:00:00.0

so I'm not sure what would be the lesser evil for a client program: an unexpectedly broken assumption of monotonicity or a traceback.

We can inform the guys on SO that they can have a customized adapter to deal with the leap seconds if the prefer the non-monotonicity to the traceback: it would a recipe similar to the [infinite dates handling](http://initd.org/psycopg/docs/usage.html#infinite-dates-handling).

**Comment by dvarrazzo** [comment]
Sorry, reading better the SO conversation, yes, it's probably easier than that.

I'm fine fixing it in our next point release and convert the time 24:00 to 00:00. Yes, we lose monotonicity there too, but I think it's not a big issue with times only.

**Comment by fogzot** [comment]
Yep, given that the problem happens only for `time` we can simply convert implicitly 24:00 to 00:00: you are going back in time but nobody notices it because there isn't a date as reference (and PostgreSQL does this for `timestamp` anyway).

**Comment by nvllsvm** [comment]
I can't think of a good solution to this problem so I'm only adding my experience for the sake of documenting the silent and inconsistent conversion.

---

Converting 24:00 to 00:00 results in incorrect logical comparisons on the Python side. For me, I experienced this while working with time windows. For example, I'll use a case which was windowed to any time of day (stored as 00:00 through 24:00).

Comparing these in SQL worked as expected.
```
postgres=# SELECT '00:00:00'::time < '24:00:00'::time;
┌──────────┐
│ ?column? │
├──────────┤
│ t        │
└──────────┘
```

However, the Python comparison results in the opposite.
```
>>> cursor.execute("SELECT '00:00:00'::time, '24:00:00'::time")
>>> a, b = cursor.fetchone()
>>> print(a, b)
00:00:00 00:00:00
>>> print(a < b)
False
```

**Comment by fogzot** [comment]
As you said, there *is not* a good solution, except patching the `datetime` module to accept `'24:00:00'` as "the midnight of the day after". Btw, this is very common, lots of PostgreSQL adapters for other languages (.NET for example) have the exact same problem.

**Comment by dvarrazzo** [comment]
It's also unwise to expect that data types and operators will behave *exactly* the same way across Python and Postgres. String comparison doesn't work the same because of collation, which means that *by default* it doesn't work the same unless your database is `lc_collate='C'`.

Total consistency between data models between Python and Postgres is not a goal the adapter can possibly set. We try to map across types the best we can, but the operators behaviour is outside our control.

**Comment by nvllsvm** [comment]
Thanks for your responses. I'm planning to propose adding something to the docs to mention the behavior with times. Would fit well at 
http://initd.org/psycopg/docs/usage.html?highlight=infinity#date-time-objects-adaptation

**Comment by dvarrazzo** [comment]
Yes please: a note in the docs would be nice to have. Thank you.
