### ISSUE TITLE
cursor.copy_from does not set the rowcount

### ISSUE THREAD

**Issue by kmoppel** [psycopg/psycopg2#332]
Currently after a successful copy_from operation cursor.rowcount seems to be always -1, although rowcount information should be available according to the Postgres docs.

-----------
http://www.postgresql.org/docs/9.4/static/sql-copy.html

On successful completion, a COPY command returns a command tag of the form
`COPY count`
The count is the number of rows copied.

**Comment by dvarrazzo** [comment]
As far as I can see this was fixed in 2.5.3. See ticket #180.

Closing as [there is a test proving it works](https://github.com/psycopg/psycopg2/commit/81b5f1fb266781c1f6df6565224c9c09e6998c06#diff-d3c5590c2a7272a086169231172c0390R275). If it doesn't please provide version numbers for psycopg and postgres.

**Comment by kmoppel** [comment]
doh. sorry, should have checked my version being up to date first. thanks!
