### ISSUE TITLE
bioinformatics extension postBIS support

### ISSUE THREAD

**Issue by auvipy** [psycopg/psycopg2#372]
should it be located here? or another project should handle that?

**Comment by dvarrazzo** [comment]
It should probably be another project, using psycopg to map postBIS data types etc (if I understood what you mean).

**Comment by auvipy** [comment]
yes I want to use pscycopg to map postbis data types :)

**Comment by dvarrazzo** [comment]
You are welcome. This would make psycopg2 a postBIS dependency, or you may have a Python package (e.g. pyPostBis) using psycopg2 to interact with postBIS data type, but psycopg2 will not incorporate postBIS adapters directly in the core, because postBIS is a fairly specialized package whereas psycopg2 is a base driver.

If you want information about how to use psycopg2 to map new Postgres data types to Python objects please [check the documentation](http://initd.org/psycopg/docs/advanced.html#adapting-new-types).

If you have questions about data adaptation please send a message to [the mailing list](https://lists.postgresql.org/mj/mj_wwwusr?user=&passw=&func=lists-long-full&extra=psycopg), don't use the bug tracker.

**Comment by auvipy** [comment]
thanks your for the kind information :) that will really help me a lot to bring that into python :dango:

**Comment by auvipy** [comment]
well 1 last question, do i need to code any c code? or calling c function in python?

**Comment by dvarrazzo** [comment]
No, pure Python should suffice :)
