### ISSUE TITLE
Why set_session

### ISSUE THREAD

**Issue by 540Grunkspin** [psycopg/psycopg2#374]
I have a question regarding set_session.

What is the benefit of that?

If i for instance call: 
```python
set_session(isolation_level=ISOLATION_LEVEL_READ_COMMITED, autocommit=True)
```

What will happen to the isolation level. Wont the two behaviours contradict each?

I must be missing something i guess.

**Comment by dvarrazzo** [comment]
Unlike what the previous implementation suggested, *autocommit* is not an isolation level. Isolation levels dictate the server behaviour with concurrent transactions: how much they can see of each others, how much they should be serialized or can proceed in parallel etc. Postgres docs have pretty detailed documentation about [transactions isolation](http://www.postgresql.org/docs/current/static/transaction-iso.html).

"Autocommit" is a client-side setting that disables the default behaviour, dictated by the DBAPI, of starting a new transaction at every statement. When autocommit is disabled, psycopg issues a `BEGIN` before any statement executed outside a transaction, and expects the client to explicitly commit or rollback the transaction using the appropriate connection method.

The two traits are independent because, even without psycopg's explicit `BEGIN`, every statement executed into Postgres is effectively a transaction of its own, and can be potentially executed against concurrent transactions, hence be subject to the artefacts discussed in Postgres docs.

`set_session()` decouples the two traits: `isolation_level` (as well as `readonly` etc.) changes the server settings for the future transactions that will be executed inside the current session, whether they are explicitly started with a `BEGIN` or implicit within a single, "naked", statement. `autocommit` dictates whether psycopg should or shouldn't send a `BEGIN` of its own.

Mixing the two in the `isolation_level` attribute, in previous psycopg versions, was an implementation naivety.

**Comment by 540Grunkspin** [comment]
Thank you for the very informative and quick answer!
