### ISSUE TITLE
Freer License Preferred

### ISSUE THREAD

**Issue by lbmn** [psycopg/psycopg2#377]
psycopg2's restrictive license is a major reason to avoid this module for a growing number of people, who, whether for philosophical or practical reasons, audit their software components to avoid restrictive licenses.

For example, https://wiki.postgresql.org/wiki/Python_PostgreSQL_Driver_TODO states: "Projects using GPL or non-standard licenses are less attractive, due to a strong preference for the simpler license issues that come from a BSD or MIT style license in this community."

A large choice of genuinely free (no anti-business ideology, no hypocrisy, no legal threats) licenses can be found at http://copyfree.org/standard/licenses .

**Comment by dvarrazzo** [comment]
> psycopg2's restrictive license is a major reason to avoid this module for a growing number of people, 

[citation needed]

> who, whether for philosophical or practical reasons, audit their software components to avoid restrictive licenses.

We, for philosophical when not practical reason, like the LGPL.

> For example, https://wiki.postgresql.org/wiki/Python_PostgreSQL_Driver_TODO states: "Projects using GPL or non-standard licenses are less attractive, due to a strong preference for the simpler license issues that come from a BSD or MIT style license in this community."

You may read that page this way: "if there was to be a new driver for Postgres we would prefer it BSD". By the way Psycopg doesn't use neither the GPL nor a non-standard license: it uses the LGPL, which doesn't restrict you in any meaningful way. Unless you want to derive a product from psycopg and sell it without giving the original developers a penny, in which case I would be forced to hate you, but you can't, because LGPL, so my karma is fine and I can go to bed with a frustration less.

> A large choice of genuinely free (no anti-business ideology, no hypocrisy, no legal threats) licenses can be found at http://copyfree.org/standard/licenses .

Thank you for considering us threatening and hypocrite. I thought our work had been somewhat useful for Python and Postgres communities.
