### ISSUE TITLE
Please use explicit rather than relative paths to PostgreSQL libraries

### ISSUE THREAD

**Issue by cjw296** [psycopg/psycopg2#385]
Please see this Stack Overflow question:

http://stackoverflow.com/questions/32978365/how-do-i-run-psycopg2-on-el-capitan-without-hitting-a-libssl-error

ArtHarg's answer worked for me, and suggests it may be possible to fix this on the psycopg2 side.
Please let me know what I can do to help!

**Comment by dvarrazzo** [comment]
Duplicate of issue #378 

Which I don't know if it will be fixed or not, but you can just compile the lib statically.

**Comment by cjw296** [comment]
@dvarrazzo - I'm hoping you can re-open this issue if I phrase it in a different way. So, steps to reproduce:

- Install Postgres on Mac OS using the standard EnterpriseDB installer, 9.4 in my case
- Create a virtualenv using Python 2.10 and the latest virtualenv
- pip install psycopg2

Compilation, linking and installation will succeed with no errors, but attempting to import the resulting library will result in the error shown in the above Stack Overflow question:

```
  File ".../lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: dlopen(.../lib/python2.7/site-packages/psycopg2/_psycopg.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: .../lib/python2.7/site-packages/psycopg2/_psycopg.so
  Reason: image not found
```

As such a standard install of psycopg2 on a standard install of Mac OS X is currently non-functional. While experienced users can fight their way through, it's not great for anyone else.

What could we do to improve things?

**Comment by cjw296** [comment]
@dvarrazzo - a year later, has any progress been made on this? I see you closed the bug you referred to as invalid, but the above is still a common use case for psyocpg2 users on a Mac...

**Comment by dvarrazzo** [comment]
@cjw296 If any, it is a problem shared by any extension library on OSX. Do *every* Mac OSX user have the same issue or it is a matter of certain setups?

There is no progress being made on this issue: I don't have Mac OSX to test with, nor any Mac specific expertise, and nobody who does has stepped in to help with that.

**Comment by cjw296** [comment]
Every Mac user of psycopg2 will have this problem, if they do a `pip install psycopg` and don't use one of the documented hacks.

Interestingly, conda has a psycopg2 build that doesn't exhibit these problems, probably for the reasons described here: http://conda.pydata.org/docs/building/shared-libraries.html#shared-libraries-in-linux-and-os-x

I see from https://pypi.python.org/pypi/cryptography/1.7.1 that Mac wheels are now built, I'm pretty sure that's to deal this this issue. Maybe @reaperhulk or @alex could help with how they solved the problem there?

As far as Mac building goes, Travis supports Mac builds: 
https://docs.travis-ci.com/user/multi-os/

**Comment by cjw296** [comment]
For the next time I need it:

```
install_name_tool -change libpq.5.dylib /Library/PostgreSQL/$PGVERSION/lib/libpq.5.dylib $PSYCOPG2/_psycopg.so
install_name_tool -change libcrypto.1.0.0.dylib /Library/PostgreSQL/$PGVERSION/lib/libcrypto.1.0.0.dylib $PSYCOPG2/_psycopg.so
install_name_tool -change libssl.1.0.0.dylib /Library/PostgreSQL/$PGVERSION/lib/libssl.1.0.0.dylib $PSYCOPG2/_psycopg.so
```

**Comment by dvarrazzo** [comment]
@cjw296 Hi Chris,

It seems the `delocate` tool is useful to create a package with a local copy of the depending libraries and to hack the binary to find them.

Would you be able to help me creating OSX wheel build for psycopg (issue #479)? I have [a branch](https://github.com/psycopg/psycopg2/tree/manylinux) where I create the builds for linux (issue #425). I would like to extend it to OSX and Windows too, but it is likely that a separate project could be a better option.

[This project](https://github.com/MacPython/numpy-wheels) seems to have everything requested to create the builds on Travis.

**Comment by cjw296** [comment]
I'm certainly interested, as with all these things, it's finding time.

Not sure about `delocate`. Thinking more about it, you probably want to link to the libraries on the user's system, otherwise you're going to have to build wheels not only per python version and per platform, but also per postgres version that you want to support.

The key this is to end up with an absolute path when linking, rather than a relative one. These Macs all have postgres installed, and pg_config is providing the correct information, it's just that the resulting .so has a relative rather than an absolute path to libssl.1.0.0.dylib and friends, so when the OS tries to load it, it can't find it.

**Comment by dvarrazzo** [comment]
Linking to the system libraries is exactly the problem that the wheels try to solve and the reason you opened this bug. Python on OSX is not a simple thing, from what I've learned reading MacPython notes.

I don't want to customise personally the build system on a platform I know little about. ``python setup.py build_ext`` should just work, and it does on most of the system, if the build prerequisites are met. If the built artifact has relative paths, not absolute, it's a problem with your build tool, it doesn't happen to other. I don't know what `install_name_tool` is, and sure I can't rely I will find it everywhere. Building the wheels solves your problem and the need to install the prerequisites (build tool matching python, the postgres client lib).

We don't have to support different Postgres versions: libpq is backwards compatible, we would just package the latest available.

> I'm certainly interested, as with all these things, it's finding time.

That's hard for everyone. I'll take it as a no and will keep on working at my pace. This bug will be fixed by the release of the wheels.

**Comment by reaperhulk** [comment]
If you want to statically link psycopg2 reliably on macOS there's several things you need to be able to do:

* Not pass `-lssl -lcrypto -lpq` to the linker.
* Pass the absolute path to the static libs (this can be done via `LDFLAGS`)
* Since you're now statically linking libpq you'll need to add `-framework Kerberos -framework LDAP` so that those are dynamically linked against the system since `libpq` (if obtained from homebrew at least) will be compiled with GSSAPI and LDAP support.

I did a quick hack of the setup.py to let me do this on the mac (just stripping the linker args and then doing `CFLAGS="-I/usr/local/opt/openssl/include" LDFLAGS="/usr/local/opt/openssl/lib/libcrypto.a /usr/local/opt/openssl/lib/libssl.a /usr/local/opt/postgresql/lib/libpq.a -framework Kerberos -framework LDAP" pip install -vvv .`) and this appears to work without issue.

There is some added complexity in deciding if the wheels should be built against the python.org Python releases as well as whether you want universal (aka x86 + x86_64 fat binaries) libs, but we can tackle that later.

I could potentially submit a PR that does all this via a travis job, but I'd love some guidance on whether adding flags to the configparser for `build_ext` is the right path here. There's already a `static_libpq`, but that still attempts to build a path on the user's behalf, whereas here we probably just want to be able to pass absolute paths as part of the build process to generate an artifact that most users will consume. Regardless, let me know what makes sense in the context of the project's current layout!

**Comment by cjw296** [comment]
@reaperhulk - interesting, I do wonder if static linking is going to create more problems than it solves.

Reading what you've written, I wonder if something `pg_config` is setting in the environment is causing Python's extension building process to go badly?

```
$ pg_config
...
CONFIGURE = '--prefix=/mnt/hgfs/pginstaller.pune/server/staging/osx' '--with-ldap' '--with-openssl' '--with-perl' '--with-python' '--with-tcl' '--with-bonjour' '--with-pam' '--enable-thread-safety' '--with-libxml' '--with-uuid=e2fs' '--with-includes=/opt/local/Current/include/libxml2:/opt/local/Current/include:/opt/local/Current/include/security' '--docdir=/mnt/hgfs/pginstaller.pune/server/staging/osx/doc/postgresql' '--with-libxslt' '--with-libedit-preferred' '--with-gssapi' 'CFLAGS=-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.7 -arch i386 -arch x86_64 -O2' 'LDFLAGS=-L/opt/local/Current/lib'
...
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.7 -arch i386 -arch x86_64 -O2
...
LDFLAGS = -L../../../src/common -L/opt/local/Current/lib -L/opt/local/20150618/lib -Wl,-dead_strip_dylibs
```

The snippet above looks like things that might be relevant.

Thoughts?

**Comment by reaperhulk** [comment]
@cjw296 static linking doesn't really carry any drawbacks beyond the ones that are already present with bundling delocated dylibs. Depending on your `pg_config` output the extension building could definitely be problematic. In my environment I have postgresql from homebrew, which is linked against homebrew openssl, so if I just do `pip install psycopg2` it actually installs and runs successfully.

**Comment by cjw296** [comment]
...but psycopg2 doesn't currently bundle delocated dylibs, and I'm not advocating for that any more than shipping statically linked wheels.

I use the EnterpriseDB provided Mac OS X installer, which looks like the official way to install postgres on Mac OS, as best I could tell. The `pg_config` output snippets above are from that.

So, back to my question: I wonder if something that `pg_config` is setting in the environment is causing Python's extension building process to go badly? Could psycopg2 do something to encourage Python's extension building process to ignore the bad bits?

**Comment by dvarrazzo** [comment]
Thank you very much for the ongoing discussion. @reaperhulk, no, I don't think adding flags to the configparser for `build_ext` is the right path: because as you say Python OSX is built with different toolkits and architecture a binary package should keep account of all of them: the [MacPython wiki](https://github.com/MacPython/wiki/wiki/Spinning-wheels) has more info. This result in chubby packages, catering for different architectures: just see the [numpy wheels filename](https://pypi.python.org/pypi/numpy)...

AFAICS the Travis OSX machines have all that is needed to build the aforementioned chubby packages. More specifically, I would only publish packages that are built on Travis: If it comes from there, it will go on PyPI.

I have just created the [psycopg2-wheels](https://github.com/psycopg/psycopg2-wheels) project whom I would like to give the same structure of the [numpy one](https://github.com/MacPython/numpy-wheels). If things are the way I expect them to be, it would be best to move there the [manylinux build](https://github.com/psycopg/psycopg2/tree/manylinux) I was writing instead in a psycopg2 branch. This way we can separate the travis builds: pushing into psycopg2 repos would run the [test suite](https://travis-ci.org/psycopg/psycopg2) on the supported platforms. Pushing into psycopg2-wheels would happen at release time and would upload packages e.g. on initd.org, from where they can go on PyPI (or directly on PyPI, to be decided).

On a note related to this conversation: I would avoid psycopg static build, I'm not sure it still works ok. Again, if numpy guys use `delocate` I would use it as well. Pure unduly cargo-cult :)

Thank you for your interest in the feature, and contribution is very, very, welcome (possibly reporting that in bug #479).

**Comment by dvarrazzo** [comment]
@cjw296 @reaperhulk There is now this project to build binary wheels on Travis CI: https://github.com/psycopg/psycopg2-wheels If you can contribute building wheels for OSX it would be great.

**Comment by dvarrazzo** [comment]
I have uploaded some test OSX wheels package on testpypi. Could you please check if they work?

    pip install -i https://testpypi.python.org/pypi psycopg2==2.7b1

Thank you very much.

**Comment by cjw296** [comment]
doesn't look like the wheel is being found:

```
Mac Pro:~ chris$ which virtualenv
/Users/chris/anaconda/bin/virtualenv
Mac Pro:~ chris$ virtualenv virtualenvs/test_psycopg2
New python executable in virtualenvs/test_psycopg2/bin/python
Installing setuptools, pip, wheel...done.
Mac Pro:~ chris$ source virtualenvs/test_psycopg2/bin/activate
(test_psycopg2)Mac Pro:~ chris$ pip install -i https://testpypi.python.org/pypi psycopg2==2.7b1
You are using pip version 7.0.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting psycopg2==2.7b1
  Downloading https://testpypi.python.org/packages/fe/d3/446affafe8f31866c4e95f8c89277ac71cd85aa5f1c220a803764c7f06e5/psycopg2-2.7b1.tar.gz (419kB)
    100% |████████████████████████████████| 421kB 565kB/s 
Building wheels for collected packages: psycopg2
  Running setup.py bdist_wheel for psycopg2
  Stored in directory: /Users/chris/Library/Caches/pip/wheels/7d/07/03/3d10164931620cf426e427528aaa58c9412ecfc0ff1f444c8e
Successfully built psycopg2
Installing collected packages: psycopg2
Successfully installed psycopg2-2.7b1
(test_psycopg2)Mac Pro:~ chris$ python
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chris/virtualenvs/test_psycopg2/lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: dlopen(/Users/chris/virtualenvs/test_psycopg2/lib/python2.7/site-packages/psycopg2/_psycopg.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /Users/chris/virtualenvs/test_psycopg2/lib/python2.7/site-packages/psycopg2/_psycopg.so
  Reason: image not found
```

**Comment by cjw296** [comment]
Ah, right, those wheels are only found with newer versions of pip. My pip was 7.0.1, updating to 9.0.1:

```
(test_psycopg2)Mac Pro:~ chris$ pip install -i https://testpypi.python.org/pypi psycopg2==2.7b1
Collecting psycopg2==2.7b1
  Downloading https://testpypi.python.org/packages/a2/2b/aa777c64fdaf4654a0bef4dc837173c2e9de6d8fc82c87563d6ce3ea941a/psycopg2-2.7b1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (1.4MB)
    100% |████████████████████████████████| 1.5MB 434kB/s 
Installing collected packages: psycopg2
Successfully installed psycopg2-2.7b1
(test_psycopg2)Mac Pro:~ chris$ python
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
>>> 
```

🎉

**Comment by dggsax** [comment]
@cjw296 Well it's 2020 and I was running into issues with psycopg2 installation again, using your solution, I was able to install it. It's still unclear what sorts of things could cause this particularly library to have such an issue, but yeah hopefully this can help more folks.

**Comment by dvarrazzo** [comment]
@dggsax your message doesn't help if you don't say:

- what problem you had
- how you solved it.

I doubt you have the same problem someone had 4 years ago, right?

**Comment by dggsax** [comment]
@dvarrazzo Thanks for the tip, I should've considered that when making my first comment. I was indeed having a very similar problem that sparked this initial thread. Using Mac Catalina 10.15.1.

**Problem**
Created a virtual environment and attempted to install psycopg2 using `pip3 install psycopg2`. The package installs fine with no issues or errors, but then as soon as I use sqlalchemy anywhere in my Flask project, I get the following error message.
```
ImportError: dlopen(/Users/gonzo/Documents/github/kappasigFlask/env/lib/python3.7/site-packages/psycopg2/_psycopg.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/gonzo/Documents/github/kappasigFlask/env/lib/python3.7/site-packages/psycopg2/_psycopg.cpython-37m-darwin.so
  Reason: image not found
```
Research on this thread as well as some others gave lots of different reasons and solutions that involved messing with symlinks and paths, but I found that the following solution worked best for me and solved my issues:

**Solution**
```
pip3 uninstall pyscopg2
pip3 install -i https://testpypi.python.org/pypi psycopg2
```
After doing this, my sqlalchemy worked without a hitch and resolved my issues and the methods in my Flask project that weren't working before were then working.

**Comment by dvarrazzo** [comment]
That sound to me like you installed psycopg 2.7.7, and you may get whatever broken testing package.

You are better off if you configure your dependencies (e.g. requirements.txt) with `psycopg<2.8`.

I don't know who suggested you to install from testpypi, but that's deranged.

**Comment by dggsax** [comment]
I followed your suggestion and installed `psycopg2-2.7.7` by running `pip3 install pyscopg2==2.7.7` that fixed my initial problem. I've crossed out my initial solution since it's not the recommended one as you said.

**New Solution**
Since I use homebrew to install and manage OpenSSL on my computer, this solution works for me. So, if you are a Mac user and you don't have libssl.1.0.0 or greater in your `/usr/lib` directory, then this is the solution for you.
`pip3 install pyscopg2==2.7.7`

Thank you for the help and for helping me make sure my comments were more specific and helpful (and to also know that installing from testpypi is a bad idea)! @dvarrazzo Below is some more info about the issue between v2.7.7 and v2.8.4 in my case just in case you or someone else may be interested. Should I just make a new issue with specific error message and provide the concise solution there and close it for others to find?

<details>
<summary>More info related to the differences between v2.7.7 and v2.8.4</summary>
<br>

**So what is the difference between `psycopg2-2.7.7` and `psycopg2-2.8.4`?**

I think I figured out where things were becoming an issue _on my specific machine_.  After re-reading my initial error message and re-installing 2.8.4 (using `pip3 install pyscopg2`), I get the same error message from my previous comment again. Specifically, it looks like it's trying to reference OpenSSL 1.0.0 based on this part of the message:
 >`Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib`

That path does not exist on my machine. Instead, my machine has `/usr/local/opt/openssl/lib/libssl.1.1.0.dylib` whereas `libssl1.0.0.dylib` lives in `/usr/local/opt/openssl@1.0/lib/libssl.1.0.0.dylib`. 

Curious about the differences between 2.7.7 and 2.8.4, I decided to figure out what versions of OpenSSL the compiled libraries required.

 * With `psycopg2-2.8.4` installed I ran, `otool -L {path to my virtualenv}/env/lib/python3.7/site-packages/psycopg2/_psycopg.cpython-37m-darwin.so` which had the following output:
```
/usr/local/opt/postgresql/lib/libpq.5.dylib (compatibility version 5.0.0, current version 5.11.0)
/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```
 * With `psycopg2-2.7.7` installed, the same otool command had the following output:
```
@loader_path/.dylibs/libpq.5.10.dylib (compatibility version 5.0.0, current version 5.10.0)
/usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```
So, version 2.7.7 seems to reference openssl-0.9.8 directly from `/usr/lib` which works fine on my machine because `/usr/lib/libssl.0.9.8.dylib` exists. Then version 2.8.4 expects openssl-1.0.0 at `/usr/local/opt/openssl/lib/libssl1.0.0.dylib`.  

But, then based on your response in #1030 it looks like it's not pyscopg2 requiring openssl but rather libpq as you mention. You also say that the library works with openssl-1.1.1, so I wonder if version 2.8.* is just incompatible with macs that use homebrew to install OpenSSL because of how homebrew installs packages now in `/usr/local/opt`. So, if I _really, really_ wanted to use version 2.8.4, I would need to manually install openssl 1.0.0 or greater without homebrew.
</details>

**Comment by HEPBO3AH** [comment]
@dggsax Thank you for the explanation. Unfortunately I wasn't able to fix it using the `pip3 install pyscopg2==2.7.7` as the version cannot be found.
I managed to temporary fix it by installing `psycopg2-binary` but that doesn't seem to be the preferred approach. 

I'll skip the rant, but as a python newby I'm baffled at why is this an issue and why the community cannot provide a clear once-and-for-all fix for this

**Comment by dvarrazzo** [comment]
@HEPBO3AH the files are here: https://pypi.org/project/psycopg2/2.7.7/#files why "the version cannot be found"? What pip version are you using?

**Comment by cjw296** [comment]
@HEPBO3AH / @dggsax: How did you install postgres on the macs where you're having these problems?

**Comment by HEPBO3AH** [comment]
> @HEPBO3AH the files are here: https://pypi.org/project/psycopg2/2.7.7/#files why "the version cannot be found"? What pip version are you using?
```
pip --version
pip 20.1 from /xxxx/virenv/lib/python3.7/site-packages/pip (python 3.7)
```
If fails because it's looking at a different location to the one you sent:
 `404 Client Error: Not Found for url: https://pypi.org/simple/pyscopg2/ - skipping`
Seems like my `virenv` was generated with the `url = "https://pypi.python.org/simple"`. Thanks for letting me know, I didn't even know that there are multiple URLs and though thats all managed through pip update.

> @HEPBO3AH / @dggsax: How did you install postgres on the macs where you're having these problems?

I don't remember really. The thing is that I installed it some time ago and the project was working. 
Now that I came back to it a month or two later - it's broken. 
I'm just really confused as to how often things in python in general on mac break and how careful I need to be when doing anything. Not sure what broke this, my guess is that it's something to do with `brew`.

**Comment by cjw296** [comment]
@HEPBO3AH - Yeah, I tend to avoid `brew` for that very reason. However, in this case, it turns out my problems were the result on using the EnterpriseDB installer. Since I switched to https://postgresapp.com/, I have not had this problems.

See https://github.com/psycopg/psycopg2/issues/1095 for the latest incarnation of this.
