### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Abondened** [psycopg/psycopg2#405]
On Centos release 5.11 
psql (PostgreSQL) 8.1.23 [psql 8.1.23 (server 9.3.10)]
Python 2.7.11
and psycopg2 ==2.6.1
on
`import psycopg2`
**Segmentation fault** prints 
On downgrading to psycopg2==2.4.5 problem is resolved but on again upgrading to 2.6.1 error shows.

**Comment by dvarrazzo** [comment]
First note: you are using an unmaintained version of libpq (8.1). Please try upgrading the client library.

If you provide a core dump or some other indication we can try and fix the bug. Otherwise please stick to a psycopg version released in a consistent age with the libpq you are trying to use.

Closing the bug unless further information about how to reproduce it is provided.
