### ISSUE TITLE
NamedTupleCursor doesn't handle duplicate field names well

### ISSUE THREAD

**Issue by tonycpsu** [psycopg/psycopg2#418]
Often when writing SQL queries with JOINs and such, one will end up with duplicate column names as the keys from both sides of the JOIN are returned.  For example, in this query:

```sql
    SELECT f.*, b.* FROM foo f JOIN bar b ON f.bar_id = b.bar_id
```
In this case, "bar_id" will be duplicated.  This can be fixed by selecting individual fields instead of using `*` or aliasing the primary/foreign keys in question so that they have unique names, but this is often inconvenient when tables have many columns, or when the "table" you're selecting from may be a subquery that you may not know the names of in advance, so the usual desired behavior is to simply have the duplicate column names overwritten, since they're the same anyway.

This is what seems to happen when one uses `RealDictCursor`, for example, but with `NamedTupleCursor`, this error is returned:

```python
  File "/usr/lib/python2.7/site-packages/psycopg2/extras.py", line 310, in fetchmany
    nt = self.Record = self._make_nt()
  File "/usr/lib/python2.7/site-packages/psycopg2/extras.py", line 340, in _make_nt
    return namedtuple("Record", [d[0] for d in self.description or ()])
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 352, in namedtuple
    raise ValueError('Encountered duplicate field name: %r' % name)
ValueError: Encountered duplicate field name: 'player_id'
```
The two ways I can think of to handle this would be to rename duplicate columns, e.g. [ "foo_id", "foo_id" ] becomes ["foo_id", "foo_id_2"], or to have the namedtuple simply overwrite duplicate columns as other cursors do.  I'm ambivalent about which is chosen, but the current behavior of throwing an exception for a pretty unexceptional case seems incorrect.

I'd be happy to put together a PR for this if it's deemed useful.

**Comment by fogzot** [comment]
Both your proposed solutions result in undefined behavior (you get columns with names you don't expect or you get one random value among many). The current behavior is correct: if you ask for a dictionary you're supposed to provide data that can be unambiguously indexed by key - anything else is an error.

**Comment by dvarrazzo** [comment]
It's also worth mentioning that the original cause of the problem is the use of `SELECT *`, which is ok for one-off interactive queries but it's to be best avoided id real programs, exactly because it makes the behaviour of the program undefined.

While I agree with @fogzot that we prefer avoiding indefinite behaviours in the library, it's really easy to create your cursor subclass and use it if you want.

https://gist.github.com/dvarrazzo/da1e98df4d3691a57aeb

This **won't** make its way into the library.

**Comment by tywoodpav** [comment]
This would definitely be useful.

Consider

    SELECT tweets.created_at, likes.created_at FROM tweets INNER JOIN likes ON likes.tweet_id = tweets.id LIMIT 1;

Using `RealDictCursor` results in 

    [{ 'created_at': '2017-06-18 20:17:04.417122' }]

This is an unambiguous query returning an ambiguous result from `psycopg2`.

Perhaps a better way would be to return 
    
    [{ 'tweets': { 'created_at': '2017-06-18 20:17:04.417122' }, 'likes': { 'created_at': '2017-06-18 20:18:23.147970' }}]

This would only be useful for `JOIN` so perhaps a `RealDictTableCursor`?

For joins with many fields this would be incredibly useful because the current solution is to use indices (from what I can tell). Although I'm a fan of Sesame Street, but I really don't like to count.
