### ISSUE TITLE
would supporting overlap/intersection of Ranges be an interesting idea?

### ISSUE THREAD

**Issue by xblitz** [psycopg/psycopg2#427]
length would be something like doing something like:
```
>>> r1 = DateRange(datetime.date(2000, 1, 1), datetime.date(2010, 1, 1))
>>> r2 = DateRange(datetime.date(2005, 1, 1), datetime.date(2015, 1, 1))
>>> r1.overlap(r2)
(datetime.date(2005, 1, 1), datetime.date(2010, 1, 1))
>>> r1 & r2
(datetime.date(2005, 1, 1), datetime.date(2010, 1, 1))
```

I was in need of this, of course it doesn't take much to do it in my own code, but I think the idea of supporting it would be nice,  should be pretty straight forward. 

If the response is positive, I would like to have my chance to do the integration and tests with a pull request

**Comment by dvarrazzo** [comment]
Hello,

thank you for the suggestion. When implementing the range objects I started giving them support functions and operators to make these objects richer, but I preferred not to overstep in that direction. Some of them may have results slightly different from the database (not the builtin ones, but as soon as you build a range over strings and include collating in the mix, it will). Some operations rely on range normalization, which would need a whole layer of "quasi-business" logic duplicate and I don't think the driver is the right place for it.

So yes, I think there are uses for range set operations (proof is that they exist in the database) but I don't think the driver is the best place for them. If you think you can do a good work with them, feel free to create a package on PyPI defining functions like `overlap(r1, r2)` or a new Range object implementing the operators: you can provide functions like `register_range()` in order to have psycopg producing your objects instead of its ones. It would be no problem referencing your package from the documentation, endorsing it if someone wanted objects thicker than the ones we provide.

**Comment by buyology** [comment]
@xblitz — did you ever come around to work on this, e.g. `overlap`? Would be very handy but I understand that this can be considered out of scope for `psycopg`

**Comment by xblitz** [comment]
I just made a gist of what I ended up making for my project:

https://gist.github.com/xblitz/8fcb14a1f55d3082354a604178648357

**Comment by buyology** [comment]
thanks @xblitz 👍
