### ISSUE TITLE
can't execute COPY TO: use the copy_to() method instead

### ISSUE THREAD

**Issue by freshquiz** [psycopg/psycopg2#444]
I'm trying to utilise PostgreSQL's (native performant) ability to convert any query result into CSV format and thus not have to do the conversion in (slower) Python.

So I'm trying to run queries like so:
```
copy from (
   ...inner query...
) to stdout with csv;
```
... where the inner query may require parameters.

`cursor.execute()` provides the ability for query parameterisation, but it gives the error:
`can't execute COPY TO: use the copy_to() method instead`
... when you try to run queries similar to what I have mentioned.

If I follow the advice and try to use the `copy_*` functions, they do not provide the ability for query parameterisation, as they seem to be geared towards basic table I/O queries.

Would it be a lot of work to either:

- Remove that _guard_ in `cursor.execute()`
- Change `copy_expert()` to accept query parameterisation

?

**Comment by dvarrazzo** [comment]
There is no "guard": COPY can't simply be used like other queries, because there is a stream to handle after the query.

Parametrizing COPY needs a different adaptation protocol from the one currently used by psycopg: implementing such protocol is among the things to implement in some psycopg3, but there is no ETA for such project.

So yes, we would implement your second suggestion, but yes, it's a lot of work.
