### ISSUE TITLE
Support LIMIT NULL and LIMIT ALL

### ISSUE THREAD

**Issue by iStefo** [psycopg/psycopg2#494]
According to the [PostgreSQL docs for LIMIT and OFFSET](https://www.postgresql.org/docs/9.5/static/queries-limit.html), there are a few valid non-numeric values for the `LIMIT` clause:

> LIMIT ALL is the same as omitting the LIMIT clause.
> [...]
> LIMIT NULL is the same as omitting the LIMIT clause.

When using these values in psycopg2 2.6.2, it gives the following error:

```
psycopg2.DataError: invalid input syntax for integer: "NULL"
LINE 1: ...AND stage < 1 ORDER BY rank ASC LIMIT 'NULL'
```
(the same is true for `ALL`).

As a workaround, one can dynamically build the query string to completely omit the limit clause if no limit is desired, but that completely defeats the purpose of writing easy to read and maintainable database queries, doesn't it?

Therefore, psycopg2 should adhere to the docs and either

a) allow `ALL` and `NULL` as legal values for the `LIMIT` clause
b) strip out the `LIMIT` clause when such a value is given
c) allow `math.inf` or a similar constant as `LIMIT` value and internally translate it to one of the cases above, although I don't see any advantage in this option.

**Comment by dvarrazzo** [comment]
Psycopg doesn't parse the SQL statement so it will not manipulate the query for you.

What you don't say if your example is that the way you are passing `NULL` is using a python string `'NULL'`: this will be escaped as a string literal, not as an SQL literal, because this is psycopg job.

You can obtain what you want in two ways: `None` is converted in a literal `NULL` so it works as expected:

```python
>>> cur.execute("select * from generate_series(1,4) limit %s", [None])
>>> cur.fetchall()
[(1,), (2,), (3,), (4,)]
```

you can also use `AsIs()` to create SQL literals instead, so you can create your literals for `ALL` or `NULL` if you wish:

```python
>>> from psycopg2 import extensions as ext
>>> ALL = ext.AsIs('ALL')
>>> cur.execute("select * from generate_series(1,4) limit %s", [ALL])
>>> cur.fetchall()
[(1,), (2,), (3,), (4,)]
```

**Comment by iStefo** [comment]
Thanks, your explanation makes perfect sense. Both options you described are suitable for my situation.
