### ISSUE TITLE
SQL_ASCII Databases should not use ascii encoding

### ISSUE THREAD

**Issue by colelloa** [psycopg/psycopg2#519]
I work for Black Duck Software, a company that specializes in scraping as many open source projects and metadata off the internet as possible. To do this, we use a massive Postgres database that is encoded in SQL_ASCII because we don't want to introduce any data corruption by forcing an encoding when scraping raw data from all corners of the internet. There is a persistent encoding issue when we use psycopg2, because it assumes SQL_ASCII databases should be encoded in 'ascii' be default.

Per comment on https://github.com/psycopg/psycopg2/blob/17dc5a8/psycopg/psycopgmodule.c#L548, this is a known issue that may/may not have been forgotten about. As the comment states, it would be great if there was a way to return a raw string or bytestring by default when dealing with SQL_ASCII databases.

Thank you for taking the time to read this.
Andrew Colello
Automation Lead, KnowledgeBase Team
Black Duck Software

**Comment by dvarrazzo** [comment]
Oh, that's long been a pet-peeve of mine, but I guess fixing it "brutally" would break a lot of databases, and because nobody complained before I thought to leave it as it is. Also returning different types according to different connection encodings seems dangerous.

Because you know what database you are connecting to I think you should configure your connection to return binary upon text values. I have fumbled a bit with adapters but haven't a solution on top of my mind. However if you cast the string you want to return to bytea psycopg should return a memory object with the binary content of your string. Even better would be to return `bytes`: I guess we can improve on that.

So, IMO, it should be possible to devise a solution for your case only using psycopg2 configuration of the adapters. Can you start testing how it is to return your data cast to `::bytea`?

Are you using python 2 or python 3 for your system? If Py2, are you returning strings as unicode? I imagine you may well want to have certain strings returned as "normal" strings (whatever normal means according to your python version) and certain others as bytes: in this case casting the raw ones to bytea seems sensible...

**Comment by RX4NT9UP** [comment]
I recently came upon this problem myself when porting code from py2 to py3, and I've yet to figure out a work around. As colelloa described above, in py2 strings default to bytes which makes sense because the database is mixed encodings. In py2 to return as unicode you need to explicitly call psycopg2.extensions.register_type(psycopg2.extensions.UNICODE).

Is there a work around for this in py3, perhaps using psycopg2.extensions.new_type()?

**Comment by dvarrazzo** [comment]
@RX4NT9UP I'm not sure it can be done in the current version (because at a first glance the data is decoded before passing it to python, but I may be wrong). However I agree it's not nice to have no fallback: I will release something to allow doing the equivalent of `register_type(UNICODE)` in Py3 to return bytes.

With the above changeset it is possible to configure psycopg to return bytes from text types:

```python
psycopg2.extensions.register_type(psycopg2.extensions.BYTES)
cur.execute("select 'asdf'::text")
cur.fetchone()[0]
b'asdf'
```

I will try to finish the feature and release it soon.

**Comment by colelloa** [comment]
Following up 3 years later: looks like this issue was fixed with the BYTES cast: https://github.com/psycopg/psycopg2/issues/835

Thnaks @dvarrazzo !

**Comment by dvarrazzo** [comment]
Hey @colelloa 

I'm pleased the issue was fixed. I think as far as psycopg2 is concerned there won't be much better than the `BYTES` caster.

However for psycopg3 I would like that adaptation rule to be chosen by default when connecting to a SQL_ASCII database. So I'd like to keep this issue open and move it to the psycopg3 repository, when such project will start properly.

Thank you very much!

**Comment by dvarrazzo** [comment]
Implemented in psycopg 3.
