### ISSUE TITLE
2.7 wheel unix socket directory

### ISSUE THREAD

**Issue by RazerM** [psycopg/psycopg2#521]
The libpq in the wheel uses `/var/run/postgresql`, which is different from PostgreSQL's default of `/tmp`.

Perhaps this was deliberate but shouldn't the psycopg2 wheel default match the PostgreSQL default?

**Comment by dvarrazzo** [comment]
It is something that has bitten me... the other way around. Trying to package a libpq built by myself instead of a system one it went looking for sockets in `/tmp` instead of `/var/run/postgres` as all the system I've managed in the last 10 years put their socket.

The libpq installed is the one that comes bundled with CentOS. Pretty much all the RedHad and Debian based distros have sockets in `/var/run` which makes the latter a better default to me.

So it wasn't exactly deliberate: it just stems from using the libpq coming with the image used to build the wheels (CentOS 5). It could be reviewed if there was a reason.

What distro are you using? Are you build Postgres yourself or do you use a packaged version?

**Comment by RazerM** [comment]
Since `/var/run/postgresql` appears to be convention I think it makes sense that the pre-built psycopg2 follows that convention. Users compiling from source can just add `no-binary = psycopg2` to `pip.conf` if required.

I'm building PostgreSQL from source, so I could also just change it pre-build.

**Comment by dvarrazzo** [comment]
I'd say if you are building postgres from source it's fair if you build psycopg too :)

**Comment by dvarrazzo** [comment]
@RazerM FYI, I've added some notes in the docs about [skipping wheel packages](http://initd.org/psycopg/docs/install.html#binary-install-from-pypi).

**Comment by qsbao** [comment]
I used a symbolic link to solve this.

``` bash
sudo ln -s /tmp/.s.PGSQL.6432 /var/run/postgresql/.s.PGSQL.6432
```

**Comment by dvarrazzo** [comment]
@qsbao you may even use the `PGHOST` env var or the `host` connection parameter to set the directory for the sockets:

```
$ PGHOST=/tmp psql
$ psql -h /tmp
$ psql "host=/tmp"
```

For the docs see [libpq env vars](https://www.postgresql.org/docs/current/static/libpq-envars.html) and [connection parameters](https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS).

**Comment by qsbao** [comment]
@dvarrazzo Thank you,   I use the `host` connection parameter now.
