### ISSUE TITLE
Range types comparison errors for DateRange

### ISSUE THREAD

**Issue by edruid** [psycopg/psycopg2#534]
When comparing ranges of discrete types (int, date) care should be take to handle boundaries correctly.
The following comparison should result in `True` but doesn't:
```
DateRange(date(2017,` 1, 1), date(2017, 1, 2), '[]') = DateRange(date(2017, 1, 1), datetime(2017, 1, 3, '[)')
```
Postgres will identify them as equal, but psycopg2 will not. Postgres will actually convert the first to the second when reading it back from the database.

I have not tested, but the issue should affect integer ranges as well.

Also, comparing an integer range with a numeric range is iffy at best, postgres disallows it.

**Comment by dvarrazzo** [comment]
This is expected. As [docs say](http://initd.org/psycopg/docs/extras.html#psycopg2.extras.Range):

> This Python type is only used to pass and retrieve range values to and from PostgreSQL and doesn’t attempt to replicate the PostgreSQL range features: it doesn’t perform normalization and doesn’t implement all the operators supported by the database.

**Comment by edruid** [comment]
@dvarrazzo Would it be appreciated if I wrote a patch for this? DateRange would be non breaking, but I would need to create a new class (IntegerRange?) for the int types.

My main use case is for testing equality in a test suite where PostgreSQL is not returning the same format that was put in.

**Comment by dvarrazzo** [comment]
Hi @edruid,

psycopg is customisable so you can write your own class to receive DateRange and implementing every rule you need to pass your tests. You may either subclass the current adapter or implement one from scratch: whatever is more useful for you.

My preference for the builtin adapter is that it didn't implement normalization rules on its objects, because normalization is already implemented by the server and doing something inconsistently is worse than not doing it at all IMO.

If you come out with some improvements you find useful feel free to submit them and we will take them in consideration but I cannot promise outright we will merge them.
