### ISSUE TITLE
inconsistent "closed" error message after upgrading from 2.6.2 to 2.7.1

### ISSUE THREAD

**Issue by cjerdonek** [psycopg/psycopg2#539]
After upgrading psycopg2 from 2.6.2 to 2.7.1, I noticed that the error message that occurs when trying to query using a closed connection varies non-deterministically.

In a personal project of mine, I have a test case where I create a temporary connection, call `SELECT pg_terminate_backend()` on its pid, and then try executing a query with that connection.

Prior to upgrading, I always got an OperationalError message that looked like the following:

    OperationalError: terminating connection due to administrator command
    SSL connection has been closed unexpectedly

However, after upgrading, the error message sometimes looks like the above, and sometimes it looks like the below:

    OperationalError: terminating connection due to administrator command
    server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

Is this a known issue? It seems similar to issue #443, since that issue is also about flaky behavior involving closed connections.

I'm using Docker with ubuntu:14.04 and postgres 9.5.6. Thanks.

**Comment by cjerdonek** [comment]
Additional info: if I put a small sleep (`time.sleep(0.1)`) before executing the query, it seems that the message is always the second of the two messages (otherwise, it is usually but not always the first):

    terminating connection due to administrator command
    server closed the connection unexpectedly
    	This probably means the server terminated abnormally
    	before or while processing the request.

**Comment by dvarrazzo** [comment]
Greg Ward has identified some [race condition](https://github.com/psycopg/psycopg2/commit/b203a7c775c5f81f59c6b4205c3c33455ceeec3d) in the kernel message, and he made sure psycopg reacts in a consistent way in different cases: this was #443 fixed.

The behaviour you report is not inconsistent as we raise the same exception upon different cases. The different message is not an issue.

If psycopg raises an exception different than `OperationalError`, and if this happens in master, then please re-open the issue. Otherwise it's not a bug for me.

**Comment by cjerdonek** [comment]
Okay, thanks, @dvarrazzo.
