### ISSUE TITLE
Psycopg2 can't work with huge redshift datatables

### ISSUE THREAD

**Issue by Rustem** [psycopg/psycopg2#553]
Please refer to the discussion here https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues/116.

**Comment by dvarrazzo** [comment]
If you use a client-side cursor psycopg will fetch itersize items. In [this example](https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues/116#issuecomment-299880889) you are fetching 10 records in the sql and 100 in psycopg, which may or may not different. For extra control use a named cursor and `executemany(size)` instead of `for record in cur`.

If the query is allocating excessive memory on the server is not psycopg bug. Psycopg is only opening a cursor on the server; what the server does is outside its control.

The rest of the discussion is polluted by sqlalchemy syntax: I don't know what sqlalchemy tells psycopg to do.

If you have a bug with psycopg not doing what it should with a named cursor open a self-contained bug. I don't see a bug here: I see a combination of not knowing what psycopg operation sqlalchemy does and what happens on the server.

**Comment by Rustem** [comment]
@dvarrazzo With postgres it works, if i use client side cursor with redshift, psycopg start allocating everything in memory instead of providing stream connection. I wouldn't ask if the default behaviour would work. I provided Java JDBC driver for comparison. It works like a charm, but my app is based on Python stack.

**Comment by dvarrazzo** [comment]
Use `cursor.query` to know what is that psycopg is telling to the server. If psycopg asks the server 10 rows and it uses 160GB of ram maybe it is a problem. If you say that "either my app or the database crashes" I understand your query is wrong: psycopg cannot crash the server. However I don't want to infer anything about your environment. If you provide information about a bug we can fix (e.g. Python receives 10 rows and explodes), we can fix the bug. As it is this is not a bug we can reproduce.

**Comment by Rustem** [comment]
After my investigation I see that the only way to go is jdbc.

**Comment by papaben** [comment]
1. [Redshift documentation](https://docs.aws.amazon.com/redshift/latest/dg/fetch.html) states that the largest fetch size supported for single-node clusters is `1000`.
1. The [psycopg](https://www.psycopg.org/docs/cursor.html#cursor.itersize) documentation states that the default iteration size for cursors is `2000`. 

The two solutions that worked for me:
1. Upgrade the cluster (which costs money)
2. Use `cursor.fetchmany(1000)` within a while loop

**Comment by dvarrazzo** [comment]
Why, setting itersize=500 no?

**Comment by papaben** [comment]
> Why, setting itersize=500 no?

Good question. I was able to get it working with `cursor.__iter__`, but the behavior of `cursor.fetchall()` still failed. 

```python
cursor.itersize = 500
cursor.execute('SELECT col FROM table_with_more_than_1000_things')
cursor.fetchall()
```

`Fetch ALL is not supported on single-node clusters. Please specify the fetch size (maximum 1000 for single-node clusters) or upgrade to a multi node installation.`

**Comment by dvarrazzo** [comment]
Ah ok. Sure: `fetchmany(n)`, `fetchall()` do just what they say on the tin. `__iter__` behaviour can be tweaked. I thought you referred to it.
