### ISSUE TITLE
Psycopg2 db connection hangs on lost network connection

### ISSUE THREAD

**Issue by GabrielSalla** [psycopg/psycopg2#561]
It's a problem since 2014

https://stackoverflow.com/questions/26741175/psycopg2-db-connection-hangs-on-lost-network-connection

If the connection is lost in the middle of a query, it will never detect it, raise an exception or anything else. It will just stop.

**Comment by dvarrazzo** [comment]
You can use [setsockopt(2)](https://linux.die.net/man/2/setsockopt) to set a timeout on the underlying connection (which you can get from [conn.fileno()](http://initd.org/psycopg/docs/connection.html#connection.fileno)).

**Comment by GabrielSalla** [comment]
As you can see on the StackOverflow question, it doesn't work.

**Comment by dvarrazzo** [comment]
I'm not sure `socket.fromfd()` does what you expect to do: it says that it duplicates the file descriptor. It sounds like the original fd doesn't change? Dunno, I would call `setsockopt(2)` via ctypes. For [someone](http://choly.ca/post/libpq-pqexec-timeout/) `setsockopt` works.

However you will not be able to tell apart the difference from a connection lost and a long running query: the server doesn't send keepalives (google _libpq network timeout_ for fun).

Another problem is with the libpq, because the libpq is what handles the `select()` that blocks the connection: maybe is better if you ask on pgsql-general and hear from them. If you want control on the wait you can go in green mode, write your own select-based callback and play with the socket to check if it's alive (how? no idea).

So, this is a TCP problem, on top of which there is the libpq, on top of which there is psycopg. psycopg doesn't have a precanned solution for your problem: there are workarounds consisting in manipulating the communication (`setsockopt`) and the wait (`select`). If you find some cool workaround please let us know.

**Comment by brianmaissy** [comment]
It feels dangerous to mess with someone else's fds without their knowledge. Could setting a timeout on the socket possibly be a feature that psycopg could expose with a higher-level API?

**Comment by dvarrazzo** [comment]
@brianmaissy The same is true for psycopg: it would be someone messing with the libpq-opened FDs without the libpq knowledge. Adding an API to it would be only a thinly-veiled disguise: better if the end user - assuming they know what they are doing - do them, using the complete POSIX api.

**Comment by brianmaissy** [comment]
Understood, thank you
