### ISSUE TITLE
copy_from - Insert null bytes into a bytea column

### ISSUE THREAD

**Issue by jean553** [psycopg/psycopg2#567]
Hello,

I would like to use copy_from() to insert bytes into a table with a `bytea` column type. Some of the bytes I want to insert are null bytes, for example:

```python
cursor.copy_from(
    StringIO("\x00\x55\x66")
    "my_table",
)
```

I get the following error: `psycopg2.DataError: invalid byte sequence for encoding "UTF8": 0x00`. Is there any way to insert null bytes in a `bytea` column with `copy_from` ? I get the same result when I switch from StringIO to BytesIO. I use psycopg 2.7.1 and PostgreSQL 9.5.7.

Thanks!

**Comment by dvarrazzo** [comment]
You have to pass the values in the COPY stream in one of the supported [bytea format](https://www.postgresql.org/docs/current/static/datatype-binary.html).

The format is sort of exposed by the `Binary` object:

```python
In [8]: data = b'\x00HI'

In [10]: from psycopg2 import Binary

In [12]: print Binary(data).getquoted()
'\\000HI'::bytea
```

but the `getquoted()` method adds an extra layer of encoding, because it is designed to embed the literal into a string, so it doesn't work out of the box for you.

You can implement your own encoding function from bytes to escaped bytea, but I think a more clever way is to use the functions [PQescapeStringConn](https://www.postgresql.org/docs/current/static/libpq-exec.html#LIBPQ-PQESCAPESTRINGCONN) or [PQescapeString](https://www.postgresql.org/docs/current/static/libpq-exec.html#LIBPQ-PQESCAPESTRING) directly from the libpq, accessing them via ctypes. You can check the implementation of psycopg2ct to see a practical example: in that project the libpq is used in python to implement the `Binary` object. You can see here [how to import the function into python](https://github.com/mvantellingen/psycopg2-ctypes/blob/2.4.4/psycopg2ct/_impl/libpq.py#L228-L234) and [how to use them from python](https://github.com/mvantellingen/psycopg2-ctypes/blob/2.4.4/psycopg2ct/_impl/adapters.py#L49-L60).
