### ISSUE TITLE
ProgrammingError: Argument formats can't be mixed, when using dictionary for parameters in complex sql

### ISSUE THREAD

**Issue by upendram91** [psycopg/psycopg2#590]
Does not parse well enough when the query is having multiple sub queries. 
I am using latest version of psycopg2 on python 3+ version.

**Comment by fogzot** [comment]
Please, provide an example because we never had any problems with subqueries (psycopg doesn't parse them, PostgreSQL does).

**Comment by upendram91** [comment]
`with a as (
select x,y from %(schema)s.%(table-abc)s
)
with b as (
select x,y from %(schema)s.%(table-bcd)s
)
select count(*) from a join b on a.x = b.x and a.y = b.y;`

Above is stored in query.sql and I am calling try to execute it with below python code

`cur.execute(file.readResource(query.sql), {
"schema": AsIs("schema-xyz"),
"table-abc": AsIs("table-abc"),
"table-bcd": AsIs("table-bcd")
})`

Errors out with Programming Error: Argument formats can't be mixed.

**Comment by fogzot** [comment]
Are you sure this is the query you're trying to execute? It is wrong and PostgreSQL will never accept it.

Anyway, I tried with a query very much like yours (using different table names, because PostgreSQL doesn't like `-` in table names...) and it worked like a charm. In `psql`:

```
CREATE TABLE abc (x integer, y integer);
CREATE TABLE bcd (x integer, y integer);
```
Then in Python:
```
import psycopg2
from psycopg2.extensions import AsIs
o = psycopg2.connect("dbname=test")
c = o.cursor()
c.execute("""
    WITH A AS (SELECT x,y FROM %(schema)s.%(table1)s),
         B AS (SELECT x,y FROM %(schema)s.%(table2)s) 
  SELECT count(*) FROM A JOIN B ON A.x = B.x and A.y = B.y""",
    {"table1":AsIs("abc"), "table2":AsIs("bcd"), "schema":AsIs("public")}
)
print c.fetchall()
```

Hope this helps.

**Comment by dvarrazzo** [comment]
You shouldn't be using `execute()` parameters to pass table names: please use `sql.Identifier` in the [psycopg2.sql](http://initd.org/psycopg/docs/sql.html) module. This will also protect you from weird things like table names with a dash.

I am pretty sure the query is creating an error is not the one you posted here: the error you reported only happens when you use named and positional placeholders together (`%s` and `%(name)s`). The complexity of the query is not psycopg concern because it doesn't parse it except for parameters substitution.

Taking from @fogzot fixed example, I suggest you to use:

```python
from psycopg2 import sql

c.execute(
    sql.SQL("""
        WITH A AS (SELECT x,y FROM {schema}.{table1}),
             B AS (SELECT x,y FROM {schema}.{table2}) 
        SELECT count(*) FROM A JOIN B ON A.x = B.x and A.y = B.y
        """
    ).format(
        table1=sql.Identifier("abc"),
        table2=sql.Identifier("bcd"),
        schema=sql.Identifier("public")
    )
)
```

and to leave `%s` placeholders for query parameters only.

**Comment by mutaimwiti** [comment]
It would help to see an example of a query like:

`data = {'x': 'value of x', 'y': 'value of y'}`

`query = update sometable set 'x' = 'value of x'  'y' = 'value of y'`

I have checked literary every sensible place on the internet.

**Comment by dvarrazzo** [comment]
@mutaimwiti In order to replace the field names in the query you can use the `psycopg2.sql` modules. You can use the same modules to replace them with values too:

```python
>>> from psycopg2 import sql

>>> data = {'x': 'value of x', 'y': 'value of y'}

>>> stmt = (sql.SQL("update sometable set {}").format(
    sql.SQL(", ").join(
        sql.SQL("{} = {}").format(
            sql.Identifier(k), sql.Literal(v)) for k, v in data.items())))

>>> print cur.mogrify(stmt)
update sometable set "y" = 'value of y', "x" = 'value of x'
```

Or use the `sql` module just to compose a statement with placeholders and pass the values separately:

```python
>>> stmt = (sql.SQL("update sometable set {}").format(
    sql.SQL(", ").join(
        sql.SQL("{} = {}").format(
            sql.Identifier(k), sql.Placeholder(k)) for k in data)))

>>> print stmt.as_string(cur)
update sometable set "y" = %(y)s, "x" = %(x)s

>>> print cur.mogrify(stmt, data)
update sometable set "y" = 'value of y', "x" = 'value of x'
```

Morally, the latter is better. Practically it's the same.

**Comment by mutaimwiti** [comment]
Very clear and elegant
