### ISSUE TITLE
ROW(t.*) type

### ISSUE THREAD

**Issue by ocZio** [psycopg/psycopg2#615]
Is there a support for queries like this? Looks like it is converted to UNICODE/String.

```sql
SELECT ROW(t.*) 
FROM table t
```

**Comment by dvarrazzo** [comment]
Not really, because the server doesn't pass information about the sub-fields. There is support for parsing of composite fields, splitting the sub-fields the right way, but then there is no casting to the right types.

You may reuse `psycopg2.extras.CompositeCaster.tokenize()` to [write your own typecaster](http://initd.org/psycopg/docs/advanced.html#type-casting-of-sql-types-into-python-objects), which would e.g. return a `ROW()` as a list of strings. The database doesn't give you info about if that string `42` is an integer or a varchar though: this is is what `register_composite()` does by inspecting the system catalog, but there is no catalog info for `ROW()` generated on the fly.
