### ISSUE TITLE
Clean up `examples` and `sandbox` dirs

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg2#645]
The project directories `examples` and `sandbox` contains mixed stuff such as

* simple examples
* nontrivial examples
* tests to reproduce bugs
* random experiments

All this predates the time when we had proper documentation and a test suite. I suspect a lot of that material can be dropped because it has received less review than the rest of the code, it may use outdated patterns, the same stuff may be already merged to the docs/tests etc, and if there is any nugget of interest I think it should be added to the docs so it's published on the interwebs...

@fogzot do you want to delete everything unused there? Or point out what should be promoted to the maintained areas of the project? I understand there may be some sentimental material in there :) so I'm happy to keep whatever you want to keep "for historical reasons"!

**Comment by dvarrazzo** [comment]
In the `scripts` directory, `buildtypes.py` and `maketypes.sh` are probably unused?

**Comment by fogzot** [comment]
I think the correct way forward is to either have a sane, documented set of examples or to move valid examples to the documentation and then remove the examples directory. Having runnable example code is better, IMHO, because you can just modify and run it while checking out how some feature works.

`buildtypes.py` and `maketypes.sh` were used to generate some headers but it seems we don't need them anymore.
