### ISSUE TITLE
`ipaddress` types don't include explicit type cast when adapted, unlike `timedelta`

### ISSUE THREAD

**Issue by univerio** [psycopg/psycopg2#653]
`ipaddress` objects are adapted into string literals, which causes problems in cases like this:

```
cursor.execute("SELECT '10.0.0.1'::inet <<= ANY (%s)",
               ([ip_interface('10.0.0.1/24'), ip_interface('10.1.0.1/24')],))
```

The error is

```
operator does not exist: inet <<= text
```

In contrast, `timedelta` objects work fine because they are adapted with an explicit cast:

```
cursor.execute("SELECT '1 day'::interval = ANY (%s)",
               ([timedelta(days=1), timedelta(days=2)],))
```

Do you think adding an explicit cast is the right way to go? I can't see any drawbacks with this, but I thought I'd ask before working on a PR.

**Comment by dvarrazzo** [comment]
I have mixed feelings about decorating adapted values with a type cast: it is probably something we shouldn't have introduced and probably something will stop working in the future.

You can add an explicit cast to your placeholder:

    SELECT '10.0.0.1'::inet <<= ANY (%s::inet[])

**Comment by univerio** [comment]
That's a bummer. Out of curiosity, what is the argument against automatically adding a cast like this?

**Comment by dvarrazzo** [comment]
That it will stop working when psycopg will start using server-side argument merging, requiring queries to be rewritten.

**Comment by univerio** [comment]
"server-side argument merging" means passing parameters separately instead of mogrifying them into the query? I'm not sure I completely understand. Can you give an example of a query that would require changes? Sorry if I'm being annoying -- just want to understand.

**Comment by dvarrazzo** [comment]
A typical one is `select some_func(%s)` where different definitions of the functions with different data types in the signature exist.

Merging the arguments server-side requires passing the arguments as postgres values, for instance a date as the string `2018-01-10`. The current protocol instead converts Python objects into string literals, e.g. `'2018-01-10'`. Converting the date into `'2018-01-10'::date` is actually an abuse: it is an entire sql expression. We introduced it millennia ago, once that the server cast behaviour changed and several queries started failing. but with many more moons of experience on the shoulders, our answer should have been "it sucks mate, fix your query as postgres wants it now" instead of trying to be smart.

The postgres function to execute a query with arguments will just not work if you try to sneak other info apart from the sql representation of the object.

**Comment by dvarrazzo** [comment]
> A typical one is select some_func(%s) where different definitions of the functions with different data types in the signature exist.

what I mean is: if you have `some_func(date)` and `some_func(timestamptz)`, calling the function without specifying the type results in an error:

```
piro=# select some_func('2010-01-01');
ERROR:  function some_func(unknown) is not unique
LINE 1: select some_func('2010-01-01');
               ^
HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
```

psycopg somewhat shields from that error by specifying a cast for the user, but this can only be done abusing the argument merging and merging a cast expression instead of a string literal in the placeholder. However we can only sneak the cast merging the argument client-side: the server will not support it. So, porting a program to this new hypothetical psycopg version will require adding the casts in the queries where necessary.

**Comment by univerio** [comment]
Thanks for the explanation! So the problem comes down to the fact that the PostgreSQL server doesn't allow the client to specify the types of arguments, so we (the user) need to explicitly include a cast in the query? I'm not too familiar with `libpq`, but from a cursory glance it seems that one could pass in OIDs for each parameter to `PQexecParams` and `PQsendQueryParams` -- or is that not sufficient?

**Comment by dvarrazzo** [comment]
I have noticed it is possible, but I'd refrain to use the types in `PQexecParams`. One problem I see, apart from the extra complexity of the adapter implementation, is that the query `select some_func(%s)` would fail with the above error if passing a None, which could be a valid input for the function instead (better a system where the query fails *every time* instead of with a specific input: the query can be fixed earlier than later).

Another problem is that for non builtin data types the oid of the types are unknown and require an extra query to fetch.

Psycopg can try to be smart, and work most of the times, failing in obscure corner cases. I think a more predictable system, failing consistently with an ambiguous query, and working consistently once the query is disambiguated, is a win in the long run.

Ah, by the way: do you want another example of query failing? Your own :) What would happen if the ipaddress adapter worked as you expect... and you passed an empty list to your query? :D

**Comment by univerio** [comment]
Thanks for the detailed explanation! I think understand where you're coming from now. I just want to stress how convenient it is for me not to have to write type casts everywhere (except for `ipaddress`) -- I would hate to lose that feature. I hope all of these edge cases can be worked around such that the system is no less predictable than not specifying types, e.g.: for `None`, pass 0 as the OID to let the server infer the type; similarly, for `inet[]` (and all array types), pass 0 as the OID so that the effect is the same as if you didn't give the OID to the server for *all* types. If this were a democracy, consider this a vote cast in favor of more "smarts". :)

Anyway, thanks for all the hard work and I am eager to see how the server-side arguments feature pans out.
