### ISSUE TITLE
psycopg2-binary: Why?

### ISSUE THREAD

**Issue by jleclanche** [psycopg/psycopg2#674]
Forgive the blunt question but I cannot find discussion on why the split of psycopg2 and psycopg2-binary is happening. The current (2.7) way of doing wheel+source distribution works exactly how it's supposed to. Splitting into a separate -binary distribution actually *breaks* any library that depends on psycopg2=>2.x, which includes for example sqlalchemy's postgres bindings, because setuptools will complain the dependency is not matched.

**Comment by dvarrazzo** [comment]
The discussion is [here](https://www.postgresql.org/message-id/CA%2Bmi_8bd6kJHLTGkuyHSnqcgDrJ1uHgQWvXCKQFD3tPQBUa2Bw%40mail.gmail.com)

The explanation is [here](http://initd.org/psycopg/articles/2018/02/08/psycopg-274-released/)

If you have another solution let us know in the mailing list. The solution should involve not segfaulting.

**Comment by jleclanche** [comment]
Thanks for the context! This is super helpful.
I actually hit the issue specified there (uwsgi+psycopg2 libssl issues on debian). It's tough because I get that this stuff should work out of the box, but at the same time I think the current solution will only work out of the box as far as people won't be using psycopg2-binary.

If you are affected by that particular issue, compiling from source is one of the more appropriate fixes and pip has a command line flag for it (which psycopg2 itself documented in various places including this issue tracker).

I understand the desire to fix the issue (as I said, I'm affected by it), but I don't think this really fixes anything:
- Users who stay on psycopg2 now have a runtimewarning they may or may not understand
- pip install psycopg2 time and requirements changed with no clear explanation why without knowing the background or having seen aforementioned warning
- Users who switch to psycopg2-binary now have issues with various package requires such as the one I mentioned in this issue (sqlalchemy is a big user of psycopg2, this is probably going to surface a lot more once 2.8 is released)
- And for the users who switch to psycopg2-binary, the original issue with libssl still exists. It's just been moved.

I think the "solution" really is the --no-binary pip flag. Unless I completely misunderstand something, that has the same effect as moving the wheels to a different package, except that for this package the wheels will not have added issues.

**Comment by Cykooz** [comment]
I fully agree with @jleclanche. Creating of psycopg2-binary is not a solution for end users. On the contrary, it is a new problem for users whom uses many third-party libraries depended from psycopg2. Now one half of this libraries depends from psycopg2 (e.g. sqlalchemy), and other half - from psycopg2-binary (e.g. pgcli). Which version of psycopg2 package will be installed and used in that situation?

**Comment by Cykooz** [comment]
psycopg2-binary has not resolved problem with libssl.

Imagine, what if near future all python libraries will be depends from psycopg2-binary instead of psycopg2. What will this situation be different from when there was only one version of psycopg2?

**Comment by dvarrazzo** [comment]
@Cykooz use psycopg2 and forget the wheel for your use. Let the other decide for theirs. If they are writing multithread programs using ssh they better use psycopg2. Otherwise they are fine with -wheels. The libssl one is not a solvable problem. If it is a problem for you forget the wheels.

**Comment by Cykooz** [comment]
But not all depends from me. I use different third-party packages which already has `psycopg2` or `psycopg2-binary` in self dependencies. And I can't control an order of installation of this packages. Sometimes `psycopg2` will be installed first, other time - `psycopg2-binary` will. 

By default `pip` don't use package name from METADATA to check that it already installed. It compare only package names taken from names of wheel files. This means that I can install both packages at the same time.

If I install `psycopg2-binary` first, and then install `psycopg2`:
```
$ pip install psycopg2-binary
$ pip install psycopg2
```
then if I uninstall `psycopg2-binary`:
```
$ pip uninstall psycopg2-binary
```
this will completely remove the code of `psycopg2` from my python.
```
$ python
>>> import psycopg2
...
ImportError: No module named psycopg2
```
But `pip` will still consider that the `psycopg2` is installed.
```
$ pip install psycopg2
Requirement already satisfied: psycopg2 in ./dist-packages
```
All of this is not very well.

**Comment by Cykooz** [comment]
Third-party packages should not determine which version of the psycopg2 distributive should be used. Because they do not know in what environment they will be used.  Version of distributive of psycopg2 should be determined solely by external tools. For example, with help of the `--no-binary` option for `pip`.

**Comment by dvarrazzo** [comment]
@Cykooz What third party package depend on psycopg2-binary?

**Comment by Cykooz** [comment]
@dvarrazzo `pgcli` depends from psycopg2-binary.

**Comment by dvarrazzo** [comment]
@Cykooz `pgcli` is an interactive tool: it doesn't strike me as something that has to live 100% in the virtualenv of e.g. a Django webapp using psycopg. But those kind of tools are exactly the reason for which I don't want to get rid of the wheels altogether. It's probably worth a chat with them to understand what's the best strategy.

**Comment by Cykooz** [comment]
Oh, maybe you are in something right.
 
I'm just afraid that not only standalone applications will include `psycopg2-binary` as a dependency, but also libraries.

**Comment by dvarrazzo** [comment]
@Cykooz I appreciate your concern. And it highlights the fact that if some library started depending on that package it may cause interdependencies problem: it's something to highlight very clearly in the docs. We are a bit into uncharted waters here: we are trying to figure out if the idea behind the psycopg2-binary is any good or if it's just the case of giving up with it.

**Comment by goodtune** [comment]
This is a problematic solution for the reasons already mentioned - `psycopg2-binary` does not satisfy a `psycopg2` dependency, and there are more than a few of these.

Pip already had a way to avoid using the wheel distribution - that should be the mechanism to go for a source installation, not a new package which clobbers the namespace of another.

**Comment by poswald** [comment]
Can the `psycopg2[nobinary]` [format](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) be used to trigger a build with `--no-binary` or perhaps the opposite with `psycopg2[binary]` pulling in the bins instead of building? No idea if that's possible but it would satisfy the same dependency for the 2 versions.

**Comment by rouge8** [comment]
> However the --no-binary is hardly a solution either, because with long requirements lists many other packages are fine to be installed from wheels except psycopg2

You can specify which packages you don't want to install from wheels, e.g. `--no-binary=psycopg2`.

For example:

```console
$ PIP_NO_CACHE_DIR=off pip install --no-binary=click click flask
Collecting click
  Downloading https://files.pythonhosted.org/packages/95/d9/c3336b6b5711c3ab9d1d3a80f1a3e2afeb9d8c02a7166462f6cc96570897/click-6.7.tar.gz (279kB)
    100% |████████████████████████████████| 286kB 6.6MB/s
Collecting flask
  Downloading https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 13.5MB/s
Collecting itsdangerous>=0.24 (from flask)
  Downloading https://files.pythonhosted.org/packages/dc/b4/a60bcdba945c00f6d608d8975131ab3f25b22f2bcfe1dab221165194b2d4/itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 12.2MB/s
Collecting Jinja2>=2.10 (from flask)
  Downloading https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 43.8MB/s
Collecting Werkzeug>=0.14 (from flask)
  Downloading https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl (322kB)
    100% |████████████████████████████████| 327kB 11.3MB/s
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10->flask)
  Downloading https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz
Installing collected packages: click, itsdangerous, MarkupSafe, Jinja2, Werkzeug, flask
  Running setup.py install for click ... done
  Running setup.py install for itsdangerous ... done
  Running setup.py install for MarkupSafe ... done
Successfully installed Jinja2-2.10 MarkupSafe-1.0 Werkzeug-0.14.1 click-6.7 flask-1.0.2 itsdangerous-0.24
```

**Comment by Vadorequest** [comment]
I don't understand anything about all that stuff neither really want to dive into it, I don't know what wheels are, I just know I had a working project using psycopg2, which now displays warning about being renamed, so I thought I had to migrate to psycopg2-binary, but if I remove psycopg2 then it fails connecting to my postgre DB. Kinda lost as people mentionned earlier...

Should I keep both? Should I not care and keep using psycopg2 and ignore that warning?

**Comment by sarusso** [comment]
@dvarrazzo you mentioned that you are "trying to figure out if the idea behind the psycopg2-binary is any good or if it's just the case of giving up with it", but you never commented on the alternative "--no-binary" approach. What are your thoughts?

**Comment by randygrolemund** [comment]
I bought a new macbook pro last night, and am trying to teach myself python. This psycopg2 stuff is really triggering me. No matter what tutorial I follow, I end up getting an error that no module is found. 

Any suggestions?

![image](https://user-images.githubusercontent.com/8581255/44302282-0766ec00-a2eb-11e8-9f3f-06655fc1706f.png)

**Comment by mmerickel** [comment]
> I bought a new macbook pro last night, and am trying to teach myself python. This psycopg2 stuff is really triggering me. No matter what tutorial I follow, I end up getting an error that no module is found.

Python 3.7 is not the python that is installed in the system, but you are running `sudo pip` to install things as the root user into the system python. Always use the `pip` that is bundled with the `python` you are using. The easiest way to make sure this always works is `python -m pip install` instead of `pip install`. Also just don't ever `sudo pip install` ever. Your issue is unrelated to this psycopg2 vs psycopg2-binary ticket.

**Comment by randygrolemund** [comment]
pip install results in permission denied. 3.7 is in fact on the laptop, I put it there. I'm not using any previous version of python, the system points to 3.7b via an alias in my profile.

I'm seeing it's likely that I needed to install Postgresql prior to psycopg2, is this accurate?

**Comment by randygrolemund** [comment]
![image](https://user-images.githubusercontent.com/8581255/44302486-4f880d80-a2ef-11e8-957e-47ad73efca7f.png)

**Comment by randygrolemund** [comment]
I see what you mean now..... I used pip versus pip3.

**Comment by goodtune** [comment]
It's not the use of pip or pip3, it's which environment you attempted to install into.

Use a virtual environment to isolate your dependencies. As suggested by @mmerickel if you encounter yourself about to run `sudo pip` then backtrack, it's almost certainly not what you want to do.

There are plenty of good tutorials on using `virtualenv` so start there.

**Comment by randygrolemund** [comment]
I have it working already... and my api is now operational :)

**Comment by sarusso** [comment]
@randygrolemund, the next time please:

1) Check for basics on the Internet before posting. Saying that a "pip install results in permission denied without sudo" and moving to a "sudo pip install" to solve the issue is a terribly noob approach. Googling for "pip install permission denied" would have solved your problem at its roots (telling you exactly what @mmerickel and @goodtune said).

2) Most importantly, if you cannot make it by yourself as sometimes happens,  check *where* you are posting. This ticket was supposed to be for a pretty advanced topic, as it is clearly stated on the first post "discussion on why the split of psycopg2 and psycopg2-binary is happening", and you created a lot of noise.

**Comment by Vadorequest** [comment]
@randygrolemund Replying with this tone certainly won't help. @sarusso is right about what he's saying, you created a lot of noise for something unrelated to the issue. The right thing would have been to create another thread, which avoid people like kleclanche, myself, and many other to be notified for every post you've made there. I'd even suggest posting on stackoverflow rather than here, since you're encountering usage issue, certainly not a bug.

Don't forget that open source requires a lot of personal time, I suppose Sarusso got annoyed of all the noise you created, hence the fact he was a bit harsh on his comment, despite the fact he gave you all the inputs you need to do better next time.

I hope this doesn't escalade, as it doesn't need to, and mustn't happen here in any case. As jleclanche said, if you wanna discuss this more deeply then please do it privately.

For the newcomers, the last useful comment in this thread was https://github.com/psycopg/psycopg2/issues/674#issuecomment-413500506 and let's get back to the actual subject now. :)

**Comment by dvarrazzo** [comment]
I apologise for the noise: I was away for a few days and didn't see this moronic thread. I will delete the crap left @randygrolemund which I have blocked so I trust he will use stackoverflow to show up his arrogance and ignorance from now on.

**Comment by mlissner** [comment]
Just throwing this out there as user experience feedback. I just spent 30 minutes trying to figure out what I should do about the warning that popped upon my console when we upgraded to psycopg 2.7.

I didn't know whether I had a binary thing or a source thing installed, or why the split, or what. All I knew is that I have a warning that I need to somehow fix. Seems that if I'm happy building things myself, I can do:

> psycopg2>=2.7,<2.8 --no-binary psycopg2

So I did that. Alas, I still get the error on the console. So, I went to check if Django supports version 2.8, and it just says anything > 2.5 is fine. Great! So I update my requirements.txt file to have `psychopg~=2.8`, and...version 2.8 isn't yet out. 

So my options are:

1. Live with the warning (I choose this)

2. Install the `psycopg-binary` package, except that's for toy projects, I guess. ("The -binary package is meant for beginners to start playing with Python and PostgreSQL without the need to meet the build requirements.")

I'm outside my comfort zone here, but this all seems pretty funky.

**Comment by dvarrazzo** [comment]
@mlissner sorry for the bad experience. `psycopg2>=2.7,<2.8 --no-binary psycopg2` should work. You may have the binary package still there. Just delete it, with `pip uninstall`, and if it doesn't come away, find the package (`import psycopg2; print psycopg2`) and delete the directory.

**Comment by mlissner** [comment]
OK, uninstalling and then reinstalling with the `--no-binary` flag did it. Thanks for the tip. So if I'm understanding correctly,  anybody that has a serious project that wants to upgrade psycopg and not have the warning emitted will need to take this step. Should this go in the docs? 

Also worth mentioning, now we're in the realm where upgrading psycopg properly seems to mean writing an upgrade script to uninstall the old one and reinstall the new one (since requirements.txt doesn't do uninstallations). There's probably a way around it, but this also seems to mean taking DB clients offline temporarily too during the transition.

**Comment by merwok** [comment]
In my team, having `--no-binary` in the requirements complicated local setup for some developers (i.e. people using Mac OS and its ten ways of installing stuff).

(We really want to build from source against the system libraries for deployments, rather than having pre-built duplicated libs in a wheel.)

Devs have to ignore the requirements files even if they first install psycopg2-binary, because the latter does not `Provides-Dist: psycopg2`.  I’m not 100% sure that pip respects that bit of metadata but this could be worth checking?

**Comment by dvarrazzo** [comment]
Happy to fix provides-dist if it's any useful. Is there documentation for this feature?

**Comment by merwok** [comment]
The spec is https://www.python.org/dev/peps/pep-0345/#provides-dist-multiple-use

But I found out that the official guide notes that installers ignore it: https://packaging.python.org/specifications/core-metadata/#rarely-used-fields
(from PR https://github.com/pypa/python-packaging-user-guide/pull/513)

**Comment by lddubeau** [comment]
Using `psycopg2>=2.7,<2.8 --no-binary psycopg2` does produce a desirable install initially but when generating a dependency list with `pip freeze` (as of `pip` 19.0.3) the `--no-binary psycopg2` argument does not carry over into the frozen dependency list. There may be an argument to be made that pip should remember the flag and carry it over when doing `pip freeze`, like it does with some other arguments, but right now people who use `pip freeze` may find the issue they were trying to dodge come back to haunt them.

**Comment by Vadorequest** [comment]
@lddubeau Indeed. My recommendation about that is to manually add it to the `requirements.txt` instead of using the command.

I dislike very much `pip freeze` anyway, as it adds tons of dependencies that are just dependencies of dependencies and not the actual stuff you need. It doesn't cause a bug by doing so, but it makes the understanding of the actual dependencies much tougher. It's just useless noise.

Using the following in your `requirements.txt` will do the trick.
`psycopg2==2.7.5 --no-binary psycopg2`

**Comment by dpage** [comment]
For my purposes, using psycopg2 is definitely the safest option (we build our own Python, libpq, OpenSSL, zlib etc to avoid conflicts in the pgAdmin distributions). However, users of the pgAdmin wheel have complained (and frankly it annoys me too) about the psycopg2-binary warning cluttering log files when they automate deployments. Can we get rid of that?

**Comment by ssewilliam** [comment]
@Vadorequest  and @lddubeau, I tried following your suggestions but it's returning a series of errors including the following. It's not yet working for me.

> Using the following in your requirements.txt will do the trick.
psycopg2==2.7.5 --no-binary psycopg2

 ` In file included from psycopg/microprotocols_proto.c:27:
    In file included from ./psycopg/psycopg.h:37:
    ./psycopg/config.h:71:13: warning: unused function 'Dprintf' [-Wunused-function]
    static void Dprintf(const char *fmt, ...) {}`

`    ld: library not found for -lssl
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'clang' failed with exit status 1
`

**Comment by Vadorequest** [comment]
@ssewilliam I don't think it's related to the requirements.txt, if you run `pip install psycopg2==2.7.5 --no-binary` you'll probably get the same output. I'm not familiar enough with psycopg to be any further help.

**Comment by frenzymadness** [comment]
A lot of projects are affected by this change and it wasn't clear to me what happened. Thanks to this issue I know what to do.
Our case is that we have a lot of testing projects in containers hosted on OpenShift platform where we don't want to install all dependencies required to build psycopg2 from source so we have to switch all of them to psycopg2-binary.

**Comment by boolow5** [comment]
On Ubuntu 20.04 this [answer](https://stackoverflow.com/a/59596814/5706345) worked for me.
Answer summery:

```bash
sudo apt-get install gcc libpq-dev -y
sudo apt-get install python-dev  python-pip -y
sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
pip3 install wheel
```
None of the above suggestions fixed my issue.
