### ISSUE TITLE
psycopg2.extras.Json for a SQL_ASCII encoding

### ISSUE THREAD

**Issue by UShan89** [psycopg/psycopg2#675]
Hi, 

I insert json formatted string (Here a python dict adapted as Json) into a column of type JSON. 

The issue I see is with retrieval of data. 
`
from psycopg2.extras import Json
json_data = {"test": "\ud83d\ude02"}

cursor.execute("insert into json_column", (Json(json_data), )

cursor.commit()
`

To retrieve, I do select `json_column_name->'test'` but I fail to fetch the record because `\ud83d\ude02` is a unicode code point value above 007F

`Unicode escape values cannot be used for code point values above 007F when the server encoding is not UTF8. Error: unsupported Unicode escape sequence`

At this point, It is impossible to change postgres encoding from sql_ascii to UTF-8, In fact, that cannot be an option. SQL ASCII just means that the database will not do anything encoding
related for you. 

I am looking for recommendations that will help me treat these unicode data and avoid unsupported Unicode escape sequences during retrieval of json fields. What is psycopg2 can I leverage to help me fix this during insert.

**Comment by dvarrazzo** [comment]
What reportedis a server error so psycopg has little to do with it. If you typed the same query in psql you would get the same error.

You can maybe [set the connection encoding](http://initd.org/psycopg/docs/connection.html#connection.encoding) to utf8 and hope for the best.

You can try to cast your json to bytea (with `(json_column_name->'test')::text::bytea`) and decode it client-side.

As far as psycopg is concerned, yes, the use of ascii decoding for sql_ascii databases is an error I would like to fix (bug #519) but I don't think it would affect your problem: your problem is with the server.
