### ISSUE TITLE
Illegal instruction on compiled binary

### ISSUE THREAD

**Issue by sacdallago** [psycopg/psycopg2#685]
This is a very odd one and it took me ages to pinpoint the error down to psycopg2.

Basically, from what I can tell, python fails when importing `psycopg2` in the stack of imports of my app. I installed `psycopg2` via `pip install psycopg2-binary`, and the `Illegal instruction: 4` pops up right after launching the app via `python app.py`. There is literally no stack trace, just this one error coming up. I'm using SQLAlchemy to connect to a database and the way I have been able to pinpoint it to the psycopg2 package is that by changing connection string to a sqlite db, the app works just fine.

I have no idea how reproducible this is, nor what type of info might be relevant, but:

```bash
$ clang --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
```

```bash
$ uname -a
Darwin MSB-MARK-D06126 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

```python
psycopg2-binary==2.7.4
```

[UPDATE]
I:
1. Ran: `pip uninstall psycopg2-binary && pip uninstall psycopg2`
2. Installed pg locally (in order to have pg_conf)
3. Ran: `pip install --no-binary :all: psycopg2-binary` although this would be equivalent to `pip install --no-binary :all: psycopg2`

Now it works. So it clearly is an instruction in the compiled binary that my system doesn't know how to interpret.

**Comment by dvarrazzo** [comment]
Googling around, it smells like the binaries on the machines building the OSX wheels have some instructions not supported by your system.

I don't know much about OSX architectures. FYI this is [the job that built the distributed wheel packages](https://travis-ci.org/psycopg/psycopg2-wheels/jobs/337843587) (it can be verified by the shasum on upload). If you want to take a look at it and it tells something obviously wrong please let us know.

As far as I'm concerned I don't have enough knowledge to solve this problem. If a bug should be open it should be on the [psycopg wheels](https://github.com/psycopg/psycopg2-wheels) and it might be successfully discussed maybe with [MacPython](https://github.com/MacPython/wiki/wiki/Spinning-wheels) who could give you more advanced info than me.

I'm closing this bug because we are in the process of deprecating wheels for psycopg2: the current policy is "if psycopg2-binary works for you we are all happy, otherwise please install psycopg2 from source".
