### ISSUE TITLE
conn.poll() does not push all notifications on Asynchronous notifications

### ISSUE THREAD

**Issue by ludionisio** [psycopg/psycopg2#686]
The example shown for Asynchronous Notifications lead us to infer that the poll() function will push all notifications waiting from database:
```
import select
import psycopg2
import psycopg2.extensions

conn = psycopg2.connect(DSN)
conn.set_isolation_level(psycopg2.extensions.ISOLATION_LEVEL_AUTOCOMMIT)

curs = conn.cursor()
curs.execute("LISTEN test;")

print "Waiting for notifications on channel 'test'"
while 1:
    if select.select([conn],[],[],5) == ([],[],[]):
        print "Timeout"
    else:
        conn.poll()
        while conn.notifies:
            notify = conn.notifies.pop(0)
            print "Got NOTIFY:", notify.pid, notify.channel, notify.payload
```
But it actually only pushes the first one. If for example a given commit to the database makes multiple row updates and the notify is set to "for each row execute", the 
"while conn.notifies:" loop only executes once. It ends up working because the outer while loop where the "select" is performed keeps pushing the remaining ones.

**Comment by dvarrazzo** [comment]
That's not what it seems to me:

Shell 1:

```
$ ipython
In [1]: import psycopg2
In [2]: cnn = psycopg2.connect('')
In [3]: cur = cnn.cursor()
In [4]: cnn.autocommit = 1
In [5]: cur.execute('listen foo')
```

Shell 2:

```
$ psql
=# notify foo, 'foo';
NOTIFY
=# notify foo, 'bar';
NOTIFY
=# notify foo, 'baz';
NOTIFY
```

shell 1:

```
In [6]: cnn.poll()
Out[6]: 0

In [7]: cnn.notifies
Out[7]: 
[Notify(2312, 'foo', 'foo'),
 Notify(2312, 'foo', 'bar'),
 Notify(2312, 'foo', 'baz')]
```

I don't think the way notifications are received is really deterministic. I guess if the network is fast enough every notification is received separately and `select` returns at each of it so you find only one in the list, which looks like the right thing to me. If your server generates the notifies in a transaction it will send all of them together on commit and maybe you will see them together... I don't know, and again I don't think it's really specified.

What my example shows is that if the OS has received more than one notification psycopg will make them all available.

**Comment by ludionisio** [comment]
I have tried exactly what you did, both in a Linux and a MacOS console. The database is on the Ubuntu machine and the python part was run in both of them. In the Linux console the behaviour is the expected one, as you mentioned, but in the MacOS console I'm getting the behaviour I'm complaining about. Since the database is on the Linux machine I assume it is not a behaviour inherent of the database in a given operating system. It tells me that the problem relies on the MacOS implementation of psycopg2. Or is it something else?

**Comment by dvarrazzo** [comment]
That's how OSX works apparently. Psycopg has no different implementation on OSX than on Linux. Psycopg only makes available what the kernel provides it.

**Comment by hkennyv** [comment]
Just wanted to report I am getting a similar issue to @ludionisio. I've run the listener script on two machines: Mac OS (Mojave 10.14.6) and Ubuntu (18.04.3).

The mac os script will receive notifications for a while but after some time, it will not receive any new notifications and needs to be restarted in order to receive again.

On ubuntu, the script continues to receive notifications well after the mac os one stops receiving (roughly 10m?)..

If anyone has a workaround for mac os, I'm all ears :)

**Comment by ekoyle** [comment]
I am seeing similar behavior when multiple messages are queued by the database between polls.   I only see `conn.poll()` picking up one or two notifications at a time.  Adding an additional `conn.poll()` inside the `while conn.notifies:` loop after `conn.notifies.pop()` seems to yield the expected behavior.

Could this be dependent on the postgresql version?  I am running Debian with their packaged psycopg2 version 2.7.7 and postgresql client version 11.7 against a remote postgresql 10 db.

**Comment by ekoyle** [comment]
One more data point: I ran the same test against a local postgresql 11 database and it is behaving as expected.

**Comment by dvarrazzo** [comment]
@ekoyle can you verifty using wireshark that the server sends more notifications to the client than the one displays? If so it is a psycopg bug, otherwise it is the behaviour of the server and we cannot do anything about it. Thank you.
