### ISSUE TITLE
Json: make dumps method similar to std json.dumps

### ISSUE THREAD

**Issue by jkp85** [psycopg/psycopg2#694]
I was working with some libraries that are using psycopg2 and there is a minor inconvenience that can be fixed easily.
Currently [dumps](https://github.com/psycopg/psycopg2/blob/master/lib/_json.py#L65) method of Json object is passing only an object to `dumps` callable. Since its default is `json.dumps` it could pass also kwargs that are available in python standard library [dumps](https://docs.python.org/3/library/json.html#json.dumps)

**Comment by dvarrazzo** [comment]
What is the use case of this change? `Json.dump()` will be called by `Json.getquoted()` just passing the `obj` argument, it is not designed to take arbitrary kwargs because it's not designed to be called in an arbitrary way. If you want to pass in an extra argument you already have ways, e.g. passing a custom `dumps` function to the `Json` init or subclassing it: these way will work during normal adaptation.

**Comment by jkp85** [comment]
@dvarrazzo I reviewed my use case and you're right I can override this, althouh I will need override some more classes along. Thanks for response. Closing.
