### ISSUE TITLE
wheel package will be renamed

### ISSUE THREAD

**Issue by matsaman** [psycopg/psycopg2#701]
"_UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>._"

This seems like a lot of hand holding for people who somehow heavily rely on pip despite not understanding how it works, and kind of a punishment for everyone else.

Put another way: <sigh> why am I getting this stderr while using something normally, correctly, & without issue?

Sorry, this is just quite a pet peeve of mine.

**Comment by dvarrazzo** [comment]
Because I want you to explicitly opt in or opt out of using wheels.

**Comment by pslacerda** [comment]
> This seems like a lot of hand holding for people who somehow heavily rely on pip despite not understanding how it works, and kind of a punishment for everyone else.

I agree very much with this. Why you want to opt in this same package?

Why not use `psycopg3`?

**Comment by matsaman** [comment]
>Because I want you to explicitly opt in or opt out of using wheels.

I think you will find that only people who don't know what wheels are in the first place will be informed by this message, again making it just noise for those who actually would care about using a wheel or not (which I also doubt would be that many).

**Comment by dvarrazzo** [comment]
You are bothered by a line on stderr that is informing you that what you are doing will stop working in a next version (likely a useful info). Other people are bothered that their production server segfaults randomly in multithread environments. Guess who I care the most?

**Comment by pslacerda** [comment]
I'm worried by the broken deployment this change will causa especifically
for people who don't know about this subject. Most of us need to install a
lot of packages to get it done and some even don't know how to install it.

Think about student programs who don't program python for a while. Or
precarious but critical deployments of small business.

Anyway, it's your package so it's your decision.

Em qui, 12 de abr de 2018 13:10, Daniele Varrazzo <notifications@github.com>
escreveu:

**Comment by matsaman** [comment]
> You are bothered by a line on stderr that is informing you that what you are doing will stop working in a next version (likely a useful info). Other people are bothered that their production server segfaults randomly in multithread environments. Guess who I care the most?

Honestly, to me you've just described the least prepared who do no testing & whose servers are already doomed. I'm not sure you can help these people, but you can add & have added noise for everyone else.

**Comment by pslacerda** [comment]
Yes, just keep the package as is don't break those. Placing a warning and distributing sources at psycopg2-sources. Releasing a new psycopg3 package. You are not helping, you are dooming they.

**Comment by dwaltrip** [comment]
Can someone confirm my understanding and provide some guidance? As far as I can tell:

Starting on release 2.8, pcycopg2 as it is today will be moving into a new package `psycopg2-binary`, because some sort of dependency conflict with an `ssl` library. The packaged named `psycopg2` will change to becoming the usual python source code style package.

Is this correct? More importantly, who is affected by the `ssl` lib dependency issue that is triggering the package name change? How can I determine which one I should be using?

**Comment by matsaman** [comment]
@dwaltrip You are exemplifying the kind of needless confusion that is created by this bug not being resolved. Thank you, I hope the maintainer notices. In fact your confusion goes even beyond this bug. My original assertion was that the warning message would be an annoyance alone to anyone except those who wouldn't understand it, but you're representing another eventuality: people confused as to what the warning is even stating.

As to your actual question: Nothing much has or will change. You will pip install exactly same way, only you will suffer this pointless warning message which will at most inform only the most ignorant of people who are already beyond help. That's why this bug was created, because the warning message that has confused you changes nothing of note.

**Comment by alexandre-paroissien** [comment]
What is the status of this issue?

**Comment by dvarrazzo** [comment]
As described. For the foreseeable 2.7.x development you get the warning. For 2.8 psycopg has no wheel. If anyone has a solution and wants to help they may speak up. Moaning doesn't constitute help.

**Comment by matsaman** [comment]
It’s true there is not any known turnkey solution for people being ignorant... but there _is_ a solution to punishing those who are not: just don't—don't make them suffer such a pointless message.

**Comment by dvarrazzo** [comment]
@matsaman I have no problem with people being ignorant on a topic. I have problem with people who have _pet peeves_ and fail to accept that there are use cases bigger than those.

The state of the fact has been described, a solution found, an improved solution would be accepted if anyone found one.

This issue here is invalid: the real issue is the broken wheel, not that a guy gets a warning on stdout: that is what I want and it's there to stay so that you either choose one way or another. There is not a third way of coming here and saying that you have a pet peeve and please ignore the people whose servers segfault.

This issue is only becoming a magnet for trolls, so it gets locked here.
