### ISSUE TITLE
connection - sslmode=disable - non ssl connection is not working

### ISSUE THREAD

**Issue by sarathy365** [psycopg/psycopg2#741]
Prerequisite: PostgreSQL server is ssl enabled and accept both ssl/non-ssl connection

Psycopg2 is always connecting with ssl, even if sslmode=disable is given in dsn/connect parameters.

**Comment by dvarrazzo** [comment]
You are likely doing something wrong.

**Comment by sarathy365** [comment]
What's wrong in this?

I just need to connect in non-ssl mode on a SSL enabled PostgreSql server.(& It's working)

**Comment by dvarrazzo** [comment]
You are not showing any example of your code not working: how are you connecting? Do you get an error message?

Psycopg doesn't deal with the sslmode, it just forwards the parameter to the client library, which is the same used by psql. So do this: run

    psql "host=X user=Y ... sslmode=disable"

and check if it connects the way you want. If it does, use the exact connection string in python

    cnn = psycopg2.connect("host=X user=Y ... sslmode=disable")

they will do exactly the same thing. If they don't let us know. Otherwise it's not a psycopg bug

**Comment by huitredelombre** [comment]
I have the same probleme:

`c=psycopg2.connect(database='callejero', user='tamere', password='tamere', sslmode='disable')
cursorPsy= c.cursor(cursor_factory=psycopg2.extras.DictCursor)
cursorPsy.execute("SELECT * FROM masa WHERE masa='68546'; SELECT * FROM masa WHERE masa='09219'" )
cursorPsy.fetchall()`
Then Wireshark see a buntch of crypted stuff and is unable to detect the protocole (pgsql), while **the same stuff work with asyncpg**.

**Comment by huitredelombre** [comment]
> the same stuff work with asyncpg
Well I guess that's because asyncpg do not use libpq. I am gonna let the comment to show the whole Internet that I am still unhappy about it

**Comment by dvarrazzo** [comment]
@huitredelombre you are not even using the network in your example: you are connected to a unix socket. The whole Internet is only seeing how ridiculous you are by ranting into a bug tracker nobody reads.

Before ranting again, do as suggested above to the OP: connect via psql using a single parameter as connection string instead of `-h`, `-U` etc, connect via psycopg using the same string as single parameter, and if they work differently come here and explain.

**Comment by huitredelombre** [comment]
> you are connected to a unix socket

That was the problem. Add to specify host='localhost' to make it work.

However I dont get your point:

> The whole Internet is only seeing how ridiculous you are by ranting into a bug tracker nobody reads.

I think it's worth posting that kind of stuff. Even if you did not help me, people can see that this "bug" is still affecting people in 2019. Actually you solved my problem and it was not a bug. But common chill out man.

**Comment by fengzunbao** [comment]
I have the same problem, Wireshark see a buntch of SSL request
