### ISSUE TITLE
sql.Identifier with alias/label?

### ISSUE THREAD

**Issue by cjauvin** [psycopg/psycopg2#791]
I'd like to be able to use `sql.Identifier` with an alias, something like:

```
>>> sql.SQL('select {} from orders').format(sql.Identifier('quantity', alias='qty')).as_string(conn)
'select "quantity" AS "qty" from orders'
```

At first I thought that it would be simply a case of creating a specialized custom class for it (i.e. `sql.LabeledIdentifier`) but then I noticed that recent [changes](https://github.com/psycopg/psycopg2/commit/4aa02b7855994e60224cb435f893f6ee8760d3d8) for the upcoming 2.8 version have the effect that `sql.Identifier` can now deal with multiple input strings, in order to implement qualified names. I'm wondering if it wouldn't be an idea to reuse the same mechanism to implement aliases (it would only require slight modifications I believe)?

**Comment by dvarrazzo** [comment]
I don't think you need a new class for that. A function returning a `Composed` instance would do.

```python
from psycopg2 import sql

def alias_identifier(ident, alias=None):
    if isinstance(ident, str):
        ident = (ident,)
    if not alias:
        return sql.Identifier(*ident)
    else:
        return sql.Composed([
            sql.Identifier(*ident),
            sql.SQL(' AS '),
            sql.Identifier(alias)])

print sql.SQL("select {}").format(alias_identifier('foo')).as_string(psycopg2.connect(''))
# select "foo"

print sql.SQL("select {}").format(alias_identifier('foo', alias='baz')).as_string(psycopg2.connect(''))
# select "foo" AS "baz"

print sql.SQL("select {}").format(alias_identifier(['foo', 'bar'], alias='baz')).as_string(psycopg2.connect(''))
# select "foo"."bar" AS "baz"
```

This is not a thing generic enough to warrant inclusion in the `psycopg2.sql` module though.

**Comment by rwarren** [comment]
I was just looking for the same thing and ended up here. The function returning `Composed` workaround is great to have (thanks, @dvarrazzo!), but I like the proposal @cjauvin had with the `alias` kwarg in `sql.Identifier`.  It does seem like it is sorely missing from the stock `Identifier`.

**Comment by asqui** [comment]
+1 Column aliasing seems like reasonable functionality to expect in the library.

@dvarrazzo : What makes you say it's not generic enough to warrant inclusion? (Or were you referring specifically to the `alias_identifier()` example implementation above?)

**Comment by dvarrazzo** [comment]
For one, `as` can be on the right not only of identifier, but of values, and placeholders too:

```
select 3 as small_value_of_pi
select %s as oh_exciting
```

Why identifier should be blessed? :slightly_smiling_face: If any I would want a function `asify(composable, name=None)` in my project.

A second reason is that I would write `as` and people would start opening bugs wanting `AS` instead :stuck_out_tongue: 

A bit more seriously, this package pretty much only provides very basic primitives which need to be treated in different ways:

- things that should be escaped as identifiers,
- things that should be escaped as values,
- things that as good as they are,
- a generic way to compose the above.

the level of these construct is lexical, whereas `thing AS name` is syntactic, and in my opinion starts already going more on the side of the policy rather than on the side of the mechanism. I am pretty sure that there are plenty of "sql macros" which could be added as trivial small functions and would definitely come handy: `select(list_of_aliased_expressions)`, `order_by(limit, offset)`... but I don't want to start adding a zoo of them.

The role I envisioned for this module is to make people able to write such bits in a secure way, for people who want to generate their own dynamic sql but don't need a full ORM yet, or they want to write their own ORM.
