### ISSUE TITLE
implicit conversion from numeric in jsonb to float

### ISSUE THREAD

**Issue by edgarcosta** [psycopg/psycopg2#792]
According to https://www.postgresql.org/docs/10/static/datatype-json.html
numbers in JSONB are stored as numeric, however, when I fetch such an array of numerics with psycopg2 they all get converted implicitly to floats.

If this is done on porpuse, is there a way to disable it and get it as a Decimal?

Here is an example:

```
> cur.execute(SQL("SELECT foo FROM table WHERE origin = %s"),['bar'])
> foo = cur.fetchone()
> print type(foo[0][0]), foo[0][0]
<type 'float'> 6.36261389471
```

```
> cur.execute(SQL("SELECT foo->>0 FROM table WHERE origin = %s"),['bar'])
> foo = cur.fetchone()
> print type(foo[0]), foo[0]
<type 'unicode'> 6.36261389471308870138602900887905
```

Thanks

**Comment by dvarrazzo** [comment]
It's written in the docs.

http://initd.org/psycopg/docs/extras.html#json-adaptation

**Comment by edgarcosta** [comment]
Thanks for the quick reply.

In the documentation that you posted, shouldn't all the float mentions be replaced with numeric?
By the Postgres documentation, it stores json numbers as numerics.
https://www.postgresql.org/docs/10/static/datatype-json.html#JSON-TYPE-MAPPING-TABLE

Furthermore, is there an intrinsic reason for treating numerics differently?

**Comment by dvarrazzo** [comment]
The documentation shows that psycopg, by default, does what the Python `json` module does by default. I don't treat numbers differently: I treat them as Python does. I would if I chose to convert them to `Decimal`.

I find this behaviour the least surprising (the same json data coming from a web service is converted the same way the data coming from the database), and give the user plenty of possibility to customise their conversion (the same way you customise data coming from a web service can be used to customise data from the database).

Note that grown ups, who don't want badly specified languages such as javascript to mess up with their data, prefer to send around fixed precision numbers as strings rather than numbers.
