### ISSUE TITLE
Psycog2 not returning anything for Select statement

### ISSUE THREAD

**Issue by udaychadha** [psycopg/psycopg2#799]
I'm trying to select some data but I only get an list for fetchall() and a None for fetchone(). I use this command:
conn.cursor.execute(SELECT id from tracks WHERE 'title' = %(title)s", {'title': title})
conn.cursor.fetchone(). I used mogrify to make sure it was the write query and it worked fine in pSequel.

**Comment by dvarrazzo** [comment]
you have the field name 'title' in single quotes, so that's a string literal. This query will always returns no row, except when you pass 'title' as a value, in which case it will return the entire title.

Surely the query you tested with mogrify is not a working one.

This is not psycopg bug: closing. Please make this sort of question on Stack Overflow.
