### ISSUE TITLE
Literal `%` in queries should always be escaped.

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg2#827]
Currently in psycopg a lone `%` is accepted when the query has no parameters, but must be doubled into `%%` if the query takes parameters. This is confusing because changing a query from non-parametrised to parametrised gives weird errors. Plus, there is issues like #825, which we don't know how to solve.

Requiring to always escape the `%` is not backward compatible so it won't happen in psycopg2. However it can if we decide to break eggs, so remembering this issue for the mythical psycopg3.

**Comment by LaughDonor** [comment]
So I came across this because I'm trying to utilize the pg_trgm extension which adds the [`%` operator](https://www.postgresql.org/docs/current/pgtrgm.html#PGTRGM-OP-TABLE). I can't seem to get past the "sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) operator does not exist: text % text" error, since SQLAlchemy does properly construct my query (and executes just fine in PostgreSQL), but psycopg won't execute it.

I tried escaping, double escaping, and triple escaping the percent operator, but it doesn't help. Is this even possible right now?

**Comment by May4m** [comment]
Hi, is it possible to add sqlalchemy style `:named` parameters as an option? Maybe an additional argument like `format` as demonstrated below

```python
cur.execute("insert into bah ("temperature%") values (:values)", {"temperator%": 0.1), format='named')
```

**Comment by dvarrazzo** [comment]
No, that's not going to happen.
