### ISSUE TITLE
extras.register_composite() fails on async connection

### ISSUE THREAD

**Issue by Piatachock** [psycopg/psycopg2#878]
Attempt to use `register_composite()` on asynchronous connection leads to this error:
```python
psycopg2/lib/extras.py:1149: in register_composite
    caster = factory._from_db(name, conn_or_curs)
psycopg2/lib/extras.py:1112: in _from_db
    recs = curs.fetchall()
E   ProgrammingError: no results to fetch
```

That is probably caused by not explicitly waiting for query to be completed in this place:
https://github.com/psycopg/psycopg2/blob/master/lib/extras.py#L1109-L1119

Could some simple patch like one below help?
```python
    curs.execute(...)

    if conn.async:
        wait_select(conn)

    recs = curs.fetchall()
```

**Comment by dvarrazzo** [comment]
No. `register_composite()` is unapologetically blocking by design. The right way to use it non-blocking is to query yourself the oid and attribute of the type you want to map and use [`CompositeCaster`](http://initd.org/psycopg/docs/extras.html#psycopg2.extras.CompositeCaster) manually.

Alternatively you can copy the code from `extras.py` into your project and customise it as you prefer.
