### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [psycopg/psycopg2#901]
Would you like to add more error handling for return values from functions like the following?
- [pthread_mutex_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [connection_setup](https://github.com/psycopg/psycopg2/blob/8b7506f80d62366ab6bb9e055ff4ea492d16db2c/psycopg/connection_type.c#L1376)
- [pthread_mutex_lock](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html "Lock a mutex.") ⇒ [pq_commit](https://github.com/psycopg/psycopg2/blob/b76ff2fc338921296099c1c205d354d30e88c8e4/psycopg/pqpath.c#L385)

**Comment by dvarrazzo** [comment]
Yes for init: would you like to provide a patch?

I don't think for lock: I don't necessarily see [modes of failure](https://linux.die.net/man/3/pthread_mutex_lock) applicable. But if you provided a patch I'd take a look.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by dvarrazzo** [comment]
Why do you open a bug report in form of question? Why don't you answer my questions before making other questions?

> How do you think about to improve static source code analysis also for this software?

I've used this extensively: https://github.com/davidmalcolm/gcc-python-plugin

> Are you interested to apply aspect-oriented software development?

No. Why do you link a C++ reference to a C project?

Would you like to encapsulate error detection and corresponding exception handling as a reusable aspect in this software?

No. I'm ok that on error it gives a good reason instead of segfaulting, 

Errors on the locking fuctions are not the cause of any of the 900 bugs reported so far. I'm ok catching error on the init (even if it's a static structure and I don't think it can possibly fail) so we can put a guard there no problem. Locking on default lock doesn't give errors, just read the links you provided. Unlock might if we unlocked a lock that wasn't taken. But because it would give errors only when unlocking a lock not taken, and all the lock/unlock patterns happen in the same function, I can demonstrate that code correct. Or if it is not it will fail on other errors as well.

You know what has caused bugs in the past? Writing the objects state outside a critical section. Have you got a solution for that? If so, patches are welcome.

**Comment by dvarrazzo** [comment]
The account opening this bug is clearly a bot

- https://github.com/koekeishiya/skhd/issues/67
- https://github.com/fontforge/fontforge/issues/3603

and its activity has been reported to github.

**Comment by elfring** [comment]
>Why do you link a C++ reference to a C project?

* A software development tool like AspectC++ can handle also C source code, can't it?
* You might get more familiar with [programming challenges around cross-cutting concerns](https://en.wikipedia.org/wiki/Cross-cutting_concern#Examples "Description for cross-cutting concerns").

-----

Thanks for [your small source code improvement](https://github.com/psycopg/psycopg2/commit/325aadbf2c598a172a1aaa0e083677bd06c8451e "Check return code of pthread_mutex_init").
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.

**Comment by dvarrazzo** [comment]
@elfring (@ the human controlling it) have a run on the codebase and check if there are meaningful return codes ignored, ta.

**Comment by elfring** [comment]
You know already that a few return codes are still ignored also in this software, don't you?

**Comment by dvarrazzo** [comment]
None which haven't been shown already impossible to fail.

Do you know any function who *can* fail and haven't been checked? This excludes mutex lock/unlock.

Answer another time with a question and this account will be blocked.

**Comment by elfring** [comment]
>This excludes mutex lock/unlock.

I find such a view [insecure](https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors "Detect and handle standard library errors.").

**Comment by dvarrazzo** [comment]
> > This excludes mutex lock/unlock.

> I find such a view insecure.

I don't care.

**Comment by elfring** [comment]
I hope that other software reviewers (besides me) and contributors will care more for complete error detection and corresponding exception handling.
There are some approaches available to improve the situation for affected components.
