### ISSUE TITLE
Some LIKE statements contains Chinese characters return no result

### ISSUE THREAD

**Issue by bruceli** [psycopg/psycopg2#915]
Hi,

I have troubles with some SELECT queries contain Chinese characters. Some of them work, some not.

Here is one of the queries works:
`SELECT roomid FROM house WHERE projectid = '3' AND location LIKE '\xe6\xb8\xad\xe5\x8d\x97\xe5\xb9\xb8\xe7\xa6\x8f\xe5\x9f\x8eA\xe5\x8c\xba04\xe5\x8f\xb7\xe6\xa5\xbc2\xe5\x8d\x95\xe5\x85\x83%2604'`

Here is one of the queries not works:
`SELECT roomid FROM house WHERE projectid = '3' AND location LIKE '\xe6\xb8\xad\xe5\x8d\x97\xe5\xb9\xb8\xe7\xa6\x8f\xe5\x9f\x8eA\xe5\x8c\xba01\xe5\x8f\xb7\xe6\xa5\xbc\xe5\x95\x86\xe9\x93\xba1\xe5\xb1\x820001'`

Both queries return values in tools such as TablePlus. How to make it work?

Thanks.

My work enviroment is
`python3 version: 3.7.3 `
`psycopg2 version: 2.8.2 `

**Comment by dvarrazzo** [comment]
I think this is more a question for the `pgsql-general` mailing list, or for stackoverflow, than for this bug tracker.

You should specify something better if you want an informed answer.

- What is the Python code that generates that query? Have you got a statement like `cursor.execute("SELECT roomid FROM house ... AND location LIKE %s", (pattern,))`? What does the pattern contain (if you `repr()` it in Python)
- What is a record you would like your query to return? Can you run a `cursor.execute("SELECT location FROM house WHERE roomid = X"); print(cursor.fetchone())` for a roomid X you know it should match?

You can try posting these info here: if it's an easy thing you may get an answer, but this is not the right forum for this type of questions.

**Comment by bruceli** [comment]
Thanks for the reply. It will be appreciated if the problem can be solved here.

Below is my code.

    sql_house = 'SELECT roomid FROM house WHERE projectid = %s AND location LIKE %s'
    location = '渭南幸福城'
    if build is None:
        location = location + str(area) + '商铺1层' + str(room)
    elif unit is None:
        location = location + str(area) + str(build).zfill(2) + '号楼商铺1层' + str(room)
    else:
        location = location + str(area) + str(build).zfill(2) + '号楼' + str(unit) + '单元%' + str(room)
    location = str(location)
    cur.execute(sql_house, ('3', location))
    print(cur.query)
    houseids = cur.fetchall()

**Comment by dvarrazzo** [comment]
The else case, when `build` is not None, adds a `%` to the `location`, which acts as a jolly character for the `LIKE` operator, and that query works. The query that doesn't work has no `%` char in the location instead.

I don't follow entirely the logic of your code, as I don't know the model or read the Chinese strings, but, if you don't include a `%`, the `LIKE` will work like an `=` operator. 

I think psycopg is fine as it's not giving bad results because of Chinese character, rather the logic you are composing the location is wrong and doesn't have a jolly where it should.

**Comment by bruceli** [comment]
Is it possible an encoding and decoding problem?

The condition text after `LIKE` operator is: `渭南幸福城A区01号楼商铺1层%0001`, which contains some Chinese characters, one `%` jolly character, one English letter and some numbers.

From the printed query text we can see the condition text was encoded as: `\xe6\xb8\xad\xe5\x8d\x97\xe5\xb9\xb8\xe7\xa6\x8f\xe5\x9f\x8eA\xe5\x8c\xba01\xe5\x8f\xb7\xe6\xa5\xbc\xe5\x95\x86\xe9\x93\xba1\xe5\xb1\x82%0001`

% and numbers are not encoded. If the text is encoded completely, the result should be: `\xe6\xb8\xad\xe5\x8d\x97\xe5\xb9\xb8\xe7\xa6\x8f\xe5\x9f\x8e\x41\xe5\x8c\xba\x30\x31\xe5\x8f\xb7\xe6\xa5\xbc\xe5\x95\x86\xe9\x93\xba\x31\xe5\xb1\x82\x25\x30\x30\x30\x31`

With the completely encoded condition text, below query works in TablePlus.
`SELECT roomid FROM house WHERE projectid = '3' AND location LIKE convert_from(decode(replace('\xe6\xb8\xad\xe5\x8d\x97\xe5\xb9\xb8\xe7\xa6\x8f\xe5\x9f\x8e\x41\xe5\x8c\xba\x30\x31\xe5\x8f\xb7\xe6\xa5\xbc\xe5\x95\x86\xe9\x93\xba\x31\xe5\xb1\x82\x25\x30\x30\x30\x31','\x',''), 'hex'), 'UTF8')`

**Comment by dvarrazzo** [comment]
It is possible that is an encoding and decoding problem because you have doing some things manually of which neither postgres nor psycopg understand.

When the string `渭南幸福城A区01号楼商铺1层%0001` is encoded in utf8 the chars with code <=127 don't become multi-byte: that's just how utf8 works. 

> If the text is encoded completely, the result should be

No not "the result should be": you wrote some sort of binary utf8 conversion which is not what postgres support. if `%` becomes `\x25` of course `LIKE` will not work.

> With the completely encoded condition text, below query works in TablePlus.

Well, in TablePlus you have `convert_from(decode(replace(`... add that to psycopg and it will work the same way.

If you use Python 3 `str` objects and pass them to postgres everything should work fine: the encoding and the `%` operator. This is a test table:

```
$ psql
psql (11.2 (Ubuntu 11.2-1.pgdg18.04+1), server 9.6.12)

piro=# create table zhdata(id serial primary key, data text);
CREATE TABLE
```

This is interaction with that table using `%`, `LIKE`, and chinese chars.

```
$ ipython
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 

In [4]: import psycopg2                                                                                              
In [5]: cnn = psycopg2.connect('')                                                                                   
In [6]: cur = cnn.cursor()                                                                                           

In [14]: cnn.autocommit = True                                                                                       

# Adding 3 records with a variable part and different final numbers
In [15]: cur.execute("insert into zhdata(data) values (%s)", ("渭南幸福城A区01号楼商铺1层XXX0001",))                 
In [16]: cur.execute("insert into zhdata(data) values (%s)", ("渭南幸福城A区01号楼商铺1层XXX0002",))                 
In [17]: cur.execute("insert into zhdata(data) values (%s)", ("渭南幸福城A区01号楼商铺1层YYY0002",))                 

# Looking for strings with a certain final number with a jolly %
In [18]: cur.execute("select * from zhdata where data like %s", ("渭南幸福城A区01号楼商铺1层%0001",))                
In [19]: cur.fetchall()                                                                                              
Out[19]: [(1, '渭南幸福城A区01号楼商铺1层XXX0001')]

# Looking for strings with a different final number
In [20]: cur.execute("select * from zhdata where data like %s", ("渭南幸福城A区01号楼商铺1层%0002",))                
In [21]: cur.fetchall()                                                                                              
Out[21]: [(2, '渭南幸福城A区01号楼商铺1层XXX0002'), (3, '渭南幸福城A区01号楼商铺1层YYY0002')]

In [22]: print(cur.query)                                                                                            
b"select * from zhdata where data like '\xe6\xb8\xad\xe5\x8d\x97\xe5\xb9\xb8\xe7\xa6\x8f\xe5\x9f\x8eA\xe5\x8c\xba01\xe5\x8f\xb7\xe6\xa5\xbc\xe5\x95\x86\xe9\x93\xba1\xe5\xb1\x82%0002'"
```

If you use these facilities out of the box, it works. If you write your own encoding you are on your own: if it doesn't work it is not a psycopg bug.
