### ISSUE TITLE
Allow users to select columns with complex types

### ISSUE THREAD

**Issue by cmenguy** [psycopg/psycopg2#947]
I have a SQL-compliant database that I'm querying with `psycopg2`. A lot of the columns I need are arrays (mostly arrays of floats, and some more nested maps)

However, when getting the results, it seems that everything is converted to strings, and it is unclear how I could get the native types in Python without having to manually parse the strings.

For example the query below which has a column whose type is a list:
```
select my_embeddings from embeddings_table limit 10;
```

This returns data like below where every row is a string containing the array values enclosed in curly braces:
```
'{0.01,0.02,0.03}'
'{0.11,0.12,0.13}'
...
```

Same when dealing with maps, nested or not, everything just comes back as a string.

I've tried `connection.cursor(cursor_factory=DictCursor)` and `connection.cursor(cursor_factory=RealDictCursor)` but this does not seem to make any difference.

I was wondering if there is anything preventing `psycopg2` from natively handling that and returning the proper types. If the type of the column being selected is an array, it would be nice to be able to get some Python lists returned. Unless there is a way to achieve that already that I am not aware of.

**Comment by dvarrazzo** [comment]
psycopg chooses what conversion function (aka typecaster) to use based on the oid of the postgres type. Every postgres type has two oids: one for the normal datum, the other for the array of that type. You can explore by reading the system table pg_types (the oid field is hidden but you can select it explicitly) or checking the cursor.description entry for the column.

psycopg deals ok with array of builtin types, e.g. it will convert a postgres array of dates into a python list of datetime.date, because builtin types have fixed and known oids. However custom data types have unpredictable oids different from db to db.

Once you know the oid for your array of data type you can use [new_array_type](http://initd.org/psycopg/docs/extensions.html#psycopg2.extensions.new_array_type) you can create a typecaster which would convert the array into a list of string, or a list of different python objects, if you specify the correct base caster.

The docs have everything: take a look at [Type casting of SQL types into Python objects](http://initd.org/psycopg/docs/advanced.html#type-casting-from-sql-to-python).
