### ISSUE TITLE
How to import psycopg2-binary

### ISSUE THREAD

**Issue by chrisdel101** [psycopg/psycopg2#982]
I'm trying to import `psycopg2-binary` rather than `psycopg2` since I read that using it might get rid of this warning: 

```
SADeprecationWarning: The 'postgres' dialect name has been renamed to 'postgresql'
  loader = self.auto_fn(name)
```

But I cannot import `psycopg2-binary`. I've tried both of these to no avail which I read about [here](https://stackoverflow.com/questions/7583652/python-module-with-a-dash-or-hyphen-in-its-name)
```
psycopg2_binary = import_module("psycopg2-binary")
psycopg2_binary = __import__("psycopg2-binary")
```
How do I import this? Or use use regular `psycopg2` and not get that warning?

**Comment by dvarrazzo** [comment]
You just `import psycopg2`, and the above error has nothing to do with it.

**Comment by cmdlinebeep** [comment]
Just hoping to point out to others who search on this error message.
I was already using psycopg2-binary, and was still getting the issue.

For me, the issue was resolved by just changing my Postgres DB path from:
"postgres://<user:pass>@localhost:5432/<db_name>"
to:
"postgresql://<user:pass>@localhost:5432/<db_name>"
