### ISSUE TITLE
\Copy not working

### ISSUE THREAD

**Issue by justinkterry** [psycopg/psycopg2#984]
I have a working connection to the database and most commands work, but I have to use /copy because I can't have superuser access to a database. When I run this line of python

`cur.execute('\\COPY passwords (password) FROM \'' + os.getcwd() + '/carriers.csv\' WITH DELIMITER \',\'')
`

I get this error:

```
Traceback (most recent call last):
  File "server.py", line 13, in <module>
    cur.execute('\\COPY passwords (password) FROM \'' + os.getcwd() + '/carriers.csv\' WITH DELIMITER \',\'')
psycopg2.errors.SyntaxError: syntax error at or near "\"
LINE 1: \COPY passwords (password) FROM '/home/justinkterry/Document...
        ^
```

Mind you that regular copy (by removing just the \\ at the beginning) works fine. When I print the python code, it renders as 

`\COPY passwords (password) FROM '/home/justinkterry/Documents/assignment3/carriers.csv' WITH DELIMITER ','
`

Meaning that the problem is clearly with the libraries handling of \copy, not what I'm doing.

**Comment by asqui** [comment]
`\copy` is a client-side [meta-command](https://www.postgresql.org/docs/9.6/app-psql.html#APP-PSQL-META-COMMANDS) of the `psql` client. Since you are not using `psql`, this command is not availabele.

See the [`cursor.copy_from()`](http://initd.org/psycopg/docs/usage.html#copy) method for the psycopg2 equivalent.

(`COPY` is a server-side command; when working with files, these are files on the local filesystem of the postgres server; both the client-side options above use `COPY ... FROM stdin` under the covers, in order to route the data from your local filesystem to the postgres server.)

**Comment by dvarrazzo** [comment]
Even better, [`copy_expert()`](http://initd.org/psycopg/docs/cursor.html#cursor.copy_expert) is the way to go as it allows using all the `COPY` features offered by the target postgres server.
